### ISSUE TITLE
FPS drops dramatically when ARCore's AugmentedImages is enabled.

### ISSUE THREAD

**Issue by arilotter** [google-ar/sceneform-android-sdk#10]
I took the basic HelloSceneForm example, and added this code to set up AugmentedImages:
```
            InputStream inputStream = getActivity().getAssets().open("images.db.imgdb");
            AugmentedImageDatabase imageDatabase = AugmentedImageDatabase.deserialize(session, inputStream);
            Config cfg = new Config(session);
            cfg.setAugmentedImageDatabase(imageDatabase);
            session.configure(cfg);
```

Before I run `session.configure(cfg)`, my frame time is ~30ms

After I run `session.configure(cfg);`, my frame time jumps to ~100ms / frame.

This doesn't happen in the Unity ARCore SDK, Augmented Images works at full framerate there.

**Comment by arilotter** [comment]
That's it! Is there a way to copy the session Config that Sceneform is using, then modify it, rather than creating an empty Config, to avoid problems like this in the future?

**Comment by claywilkinson** [comment]
At this time, there is no way to copy a configuration.  I think it is a great idea.  I've passed it along to the ARCore API team as a feature request.
