### ISSUE TITLE
How to create ViewRenderable above ModelRenderable

### ISSUE THREAD

**Issue by wangtsung** [google-ar/sceneform-android-sdk#1022]
I want when i click to create two renderables one is modelRenderable create at hit point and the other one is ViewRenderable need to create above modelRenderable how to do that,i can only create modelRenderable can't create viewRenderable.

                    Anchor anchor = result.createAnchor();
                    AnchorNode anchorNode = new AnchorNode(anchor);
                    anchorNode.setParent(arFragment.getArSceneView().getScene());
                    anchorNode.setRenderable(hit);
                    anchorNode.setLocalScale(new Vector3(0.02f, 0.02f, 0.02f));

                    ViewRenderable.builder().setView(this, R.layout.arlayout)
                            .build()
                            .thenAccept(viewRenderable -> {
                                viewRenderable.setShadowReceiver(false);
                                viewRenderable.setShadowCaster(false);
                                Vector3 worldPosition = anchorNode.getWorldPosition();
                                Node node = new Node();
                                node.setRenderable(viewRenderable);
                                node.setLocalScale(new Vector3(0.3f,0.3f,0.3f));
                                anchorNode.addChild(node);;
                                TextView tvCount = viewRenderable.getView().findViewById(R.id.tvCount);
                                tvCount.setText(String.valueOf(countObject()));
                            })
                            .exceptionally(throwable -> {
                                Toast toast = Toast.makeText(this, "Unable to load andy renderable", Toast.LENGTH_SHORT);
                                toast.show();
                                return null;
                            });

**Comment by tpsiaki** [comment]
It looks like this is the same issue as #1025 - we're investigating the issue there.

**Comment by wangtsung** [comment]
use addChild() to fix it

ModelRenderable node .addChild (ViewRenderable node) like this
