### ISSUE TITLE
sceneform documentation url 404

### ISSUE THREAD

**Issue by SGTjeong** [google-ar/sceneform-android-sdk#1024]
Hi

I am looking for some sceneform api. But since few days ago, The server has kept responding 404 and nothing fixed yet.

What happened?

**Comment by tpsiaki** [comment]
Thanks for the report.  Because we open sourced the Sceneform SDK in our 1.16 release, all of the javadocs are included in the source code under sceneformsrc in this repro.

There was a bug in our README.md file that pointed to the old location for the sceneform reference docs.  I've updated it now to point to the [legacy reference docs for Sceneform 1.15](https://developers.google.com/sceneform/reference/com/google/ar/sceneform/package-summary).

**Comment by JGregoryAtiba** [comment]
I've looked around for some kind of announcement about 1.16, but can't find anything except the Github release page, which doesn't say much.  Will the Quickstart documentation, etc. at developers.google.com ever be updated?  Is there some kind of migration guide?  If not, what are Google's future plans for Sceneform and ARCore?

We already have an app that is using the SFB format, but now apparently it's deprecated.  Will we not be able to use SFB at all if we upgrade to 1.16?

**Comment by ChanduMnS** [comment]
I've tried to open many documentation pages from google search like [this](https://developers.google.com/ar/reference/java/sceneform/reference/com/google/ar/sceneform/rendering/Renderable). Many of them threw a 404 Error. Kindly help me with this.
Their are many such search results. Kindly add the latest documentation.

**Comment by tpsiaki** [comment]
Apologies for the broken links here.  We are working on fixing them.  For the time being you can find references for Sceneform 1.15 here:

* [Sceneform API overview](https://developers.google.com/sceneform/reference/packages.html)
* [Sceneform gradle plugin overview](https://developers.google.com/sceneform/reference/gradle/com/google/ar/sceneform/plugin/package-summary.html)

We'll have more migration instructions shortly.

**Comment by ChanduMnS** [comment]
Thanks @tpsiaki for your prompt reply :)

**Comment by dakshsrivastava** [comment]
Can this issue be closed then?

**Comment by ChanduMnS** [comment]
Kindly restore the urls in the search since it is causing inconvenience. 
Thanks
Chandu

**Comment by vortice3D** [comment]
Hi **tpsiaki**:

So in order to have access to some plane-text docs we must keep consulting, at the moment, the 1.15 version, isn't it? Is there any milestone to link 1.16 ones?

Best regards.
