### ISSUE TITLE
animation app sample

### ISSUE THREAD

**Issue by ekoRemDev** [google-ar/sceneform-android-sdk#1026]
there is no R.raw.andy_wave_r folder and file in animation sample app

**Comment by tpsiaki** [comment]
Hi @ekoRemDev - the animation sample app that provided andy_wave as an sfb was deprecated in 1.16 in place of using gltf animations with the Filament gltfio loader.  You can look at the gltf sample in 1.16 if you would like to use gltf animations.

If you'd like to continue using your existing sfb animations, we recommend you stick with Sceneform 1.15 which has this support.
