### ISSUE TITLE
Adding images to the scene at run time

### ISSUE THREAD

**Issue by arasbm** [google-ar/sceneform-android-sdk#103]
I was wondering if it is possible to add images to the scene at runtime. The application I am working on is a simple poster board were users can place an image from the gallery or the camera on the board. I have made a 3D model of a paper and trying to set the image on the 3D model but I am not having much luck understanding how I can do this by looking at the API docs. Is this possible to do with either sceneform API or the arcore SDK without using unity?

**Comment by dsternfeld7** [comment]
Does the information in [https://github.com/google-ar/sceneform-android-sdk/issues/41](https://github.com/google-ar/sceneform-android-sdk/issues/41) help you with your use case?
