### ISSUE TITLE
how to include com.google.ar.sceneform.ux:sceneform-ux:1.16.0 in build.gradle

### ISSUE THREAD

**Issue by kulnaman** [google-ar/sceneform-android-sdk#1030]
Hi ,
I am trying to add sceneform-ux:1.16.0 in my build.gradle but it is not available in the gradle, Is this a deliberate decision where the core sceneform library is present in the gradle repository but for the ux lib  we have to download the source code and add it to our project.

**Comment by anacoimbrag** [comment]
As long as I know, you have to clone this repo and setup the `settings.gradle` to recognize the project, just like the [sample](https://github.com/google-ar/sceneform-android-sdk/blob/master/samples/gltf/settings.gradle). 

And then in `app/build.gradle` you'll use `implementation project('sceneformux')` or `implementation project('sceneform')`

**Comment by kulnaman** [comment]
Yeah I did that but I was just thinking why have sceneform-core as a gradle library but not the sceneform ux, and updating the project whenever a new version arrives is quite wasteful, but thanks anyway

**Comment by tpsiaki** [comment]
Starting in 1.16 Sceneform libraries are only available open source.  There is no longer a maven version.

Pre-1.15 the ux package was [available on maven](https://mvnrepository.com/artifact/com.google.ar.sceneform.ux/sceneform-ux)
