### ISSUE TITLE
Rendering glb/gltf in sceneform 1.16

### ISSUE THREAD

**Issue by SGTjeong** [google-ar/sceneform-android-sdk#1033]
Thanks in advance, for adding gltf animation in the new version.

I checked if rendering gltf works with the tiger model in the sample. And it worked well.  

I checked once again with my glb file, but unfortunately I couldn't see the rendered object, but only its shadow.

1. I don't think my glb file did cause the problem because i can see it in the viewer very well. Or maybe i used free converter(gltf to glb) and it might have caused an error. But for sure my glb file doesn't have any problem. Was there any issue like this reported yet?

2. Sample gltfAcitivty only shows how to load glb file. I want to know how to load gltf file from server. 

Thank you again

**Comment by plugxrandroid** [comment]
Same issue And Given gradle library is not working . getting issue while importing time .

**Comment by kulnaman** [comment]
@plugxrandroid  kindly look into the issue https://github.com/google-ar/sceneform-android-sdk/issues/1030
