### ISSUE TITLE
Animation in SceneView

### ISSUE THREAD

**Issue by SGTjeong** [google-ar/sceneform-android-sdk#1061]
In advance, thank you for sceneform 1.16.0 being able to use gltf animation

The sample code only shows how to animate objects in arFragment.

Is there a way to animate objects in SceneView?

**Comment by tellypresence** [comment]
The gltf animation is a property of the renderable node, so there shouldn't
be anything special you need to do to have model animation

**Comment by SGTjeong** [comment]
i was stu
