### ISSUE TITLE
Can arcore's modeling tool only be blender?

### ISSUE THREAD

**Issue by ToadPrincess** [google-ar/sceneform-android-sdk#107]
hi~
       I imported the model with sceneform with various uv-Mapping errors.We've tried obj, FBX, and we haven't solved it.Then we see that blender is mentioned in Andy's MTL file.Then our model engineer use blender and the problem is solved.But what we use a lot is 3dsMax,Unreal,Can arcore's modeling tool only be blender?

**Comment by AdrianAtGoogle** [comment]
Hi @ToadPrincess, thank you for submitting this issue.

There are numerous issues in our 1.0 release; and we're working on getting fixes out to you.  We have no requirement on using Blender - valid asset files from any DCC toolset should work in Sceneform.

We would be happy to assist further if you can say more about these errors.

**Comment by ToadPrincess** [comment]
@AdrianAtGoogle Sure, no problem.
When we encounter uv errors, we try to find the problem. First open the Andy model with 3dsMAX and Unreal, export obj or FBX without any modification, and then import android with sceneform, uv errors will appear.
We have no problem using blender for the same operation. After that, our engineers directly use blender for production, and there is no problem.
And what we found is that if you just make uv-x and uv-y, there's no problem. If you have uv-x,uv-y,uv-w, there's a problem.

**Comment by dsternfeld7** [comment]
@ToadPrincess Are you encountering the same issues using modeling tools other than blender after upgrading to Sceneform 1.3?

**Comment by ToadPrincess** [comment]
@dsternfeld7 After the update, the 3dsMax is displayed correctly.Thanks!
