### ISSUE TITLE
Object is moving along when i move the phone ?!

### ISSUE THREAD

**Issue by danyjoy** [google-ar/sceneform-android-sdk#1076]
I'm trying to add an object to the screen center when the tensor flow classifier detects an object. And it is working properly.

But the renderable is moving when i move the phone to the left, right, to front and back. But there is no problem when i rotate the device without moving it from the place. 

i'm creating an anchor to the center of the screen and placing an anchor node there. 

`Anchor newMarkAnchor = session.createAnchor(
                                    frame.getCamera().getPose()
                                            .compose(Pose.makeTranslation(0, 0, -3f))
                                            .extractTranslation());
                            AnchorNode addedAnchorNode = new AnchorNode(newMarkAnchor);
addedAnchorNode.setRenderable(viewRenderable);
                                addedAnchorNode.setName(nodeCount + "" + result.getTitle());
                                addedAnchorNode.setParent(scene);
`

I'm new to Sceneform and i'm not able to find a solution

**Comment by SGTjeong** [comment]
You need to update the node position relatively to the camera position in onUpdate method.
Or you can set the camera as the node's parent, and adjust node's local position.

**Comment by danyjoy** [comment]
> You need to update the node position relatively to the camera position in onUpdate method.
> Or you can set the camera as the node's parent, and adjust node's local position.

i don't really know how to do that. I'm taking frames from the scene and passing it to the classifier inside onUpdate method. 

How can i update the node position relatively to the camera position ?

**Comment by SGTjeong** [comment]
(1) inside onUpdate method

 val cameraPos = arSceneView.scene.camera.worldPosition
 val cameraForward = arSceneView.scene.camera.forward
 val position = Vector3.add(cameraPos, cameraForward.scaled(distance))
 node.worldPosition = position

(2) Or when you place Node

 ModelRenderable.builder().setSource(context, Uri.parse("model.sfb"))
            .build()
            .thenAccept{
                 var node = Node()
                 node.localPosition = Vector3(0f, -0.2f, -0.5f)
                 node.renderable = it
                 node.setParent(arSceneView.scene.camera)
            }
            .exceptionally {
                null
            }
   }

**Comment by danyjoy** [comment]
@SGTjeong Thanks for the reply. 

I tried using the 2nd step that you gave me. But the object is just sticking to the camera. I also tried another method where i use random coordinates to put the renderable when i detect object. 

```
ModelRenderable
                    .builder()
                    .setSource(this, Uri.parse("andy.sfb"))
                    .build()
                    .thenAccept(renderable -> {


                            Node node = new Node();
                            node.setRenderable(renderable);
                            scene.addChild(node);


                            Random random = new Random();
                            int x = random.nextInt(10);
                            int z = random.nextInt(10);
                            int y = random.nextInt(20);

                            z = -z;

                            node.setWorldPosition(new Vector3(
                                    (float) x,
                                    y / 10f,
                                    (float) z
                            ));



                    });
```

But still, its drifting from the position when i move it to left or right. 

Is there any way that i can link all the anchorNodes to a trackable plane on the scene??

**Comment by danyjoy** [comment]
So, i got a **SOLUTION** for this problem. 

I created a ray from the center of the screen and then placed the renderable 3 meters along the ray and now its not drifting drastically.

`Ray ray = camera.screenPointToRay(point.x / 2f, point.y / 2f);`
`Vector3 vector3 = ray.getPoint(3f);`
                           `AnchorNode addedAnchorNode = new AnchorNode();`
                            `addedAnchorNode.setWorldPosition(vector3);`
