### ISSUE TITLE
No FBX animation support for Imported Sceneform Assets

### ISSUE THREAD

**Issue by haroldmthyng** [google-ar/sceneform-android-sdk#11]
More so confirmation as I've tried everything and imported FBX assets do not retain animation or skeletal animation data. Unless I'm missing something. This is the key major component to ever use a FBX asset over a static OBJ file.

Can you confirm if animated FBX's are supported within the Sceneform binary file format? Will be in an upcoming release? If not, can you generate a much needed feature request for skeletal animation support for Sceneform assets?

**Comment by malik-at-work** [comment]
Sceneform 1.0 does not support skeletal animation.  We are looking into this for future releases.

**Comment by haroldmthyng** [comment]
Please do. That's really to single most important purpose of the FBX format. With that Sceneform would be on par with iOS' SceneKit Collada support, and any other 3D java library that supports skeletal animation.

**Comment by mbhaskar** [comment]
Thanks a lot for making this a feature request. I have been struggling to render fbx/dae as models along with google ar. Though I got some success with libgdx and fbxconv, their performance is not that good. I tried fbx with Sceneform and its very smooth taking up less memory. 
Do we have any timeline on when fbx animations will be supported?

**Comment by Nullifier1571** [comment]
oky,i hope google will provide our  a powerful api for developers

**Comment by malik-at-work** [comment]
This will be in an upcoming release. I'm not able to provide a timeframe on this feature however.

**Comment by juanluislm** [comment]
is there support for morphs and blend shapes? I have been reading the documentation, but I have not found much about this

**Comment by FabianTerhorst** [comment]
@malik-at-work will this be like the SCNSkinner in scenekit?

**Comment by Brianvdb** [comment]
Any news?

**Comment by gorastudio** [comment]
We need animation, pleaseeee!!!

**Comment by pjmcnerney-mlbam** [comment]
+1 on the animation support.

**Comment by malik-at-work** [comment]
The feedback on what features are desired most is appreciated.

**Comment by omihaz** [comment]
I'm also waiting for this feature. FBX and gltf animations will be great feature and make sceneform the excellent framework for AR and 3D.

**Comment by juanluislm** [comment]
@malik-at-work Support for blend shapes, and FBX and gltf animations would be amazing

**Comment by phychem** [comment]
+1 support adding this feature in the next release :)

**Comment by bestog** [comment]
Please add animations for fbx in sceneform. 🙏

**Comment by yashvv** [comment]
Please add expedite this feature. Thank You.

**Comment by steelbytes** [comment]
No animation?  back to fighting artoolkit + openscenegraph :-(

**Comment by CJohnDesign** [comment]
+1 for adding animations :)

**Comment by kunleLaundrapp** [comment]
+1 for animations!!!

**Comment by felipemobile** [comment]
+1 for fbx animations. Roadmap?

**Comment by wasdrqm** [comment]
+1 for animations!

**Comment by haroldmthyng** [comment]
@malik-at-work the demand is definitely growing as this feature is pretty much a must have. Any updates regarding animation support?

Also I haven't checked, but any insights to an open source project that may be addressing this?

**Comment by malik-at-work** [comment]
Thank you! We've definitely noted the requests here.  I believe we have this feature completed in our code so it should be part of an upcoming release.  We can't be more specific on timing yet, it has to go through several more steps before actual release.

**Comment by quickfingers** [comment]
So what is supported? Is it only skeletal animation or it doesn't support any of animation at all? What would be the alternative?

**Comment by spiraloid** [comment]
adding my voice to the choir on getting gltf skeleton animations working.  4 bone linear skinning is fine.

**Comment by stewe93** [comment]
+1 on this. By the way, I saw a demo video online somewhere, In this video there were a lion figure, who reacted to user interaction and light change. Is this possible right now with the public release?

**Comment by zhangruize** [comment]
> +1 on this. By the way, I saw a demo video online somewhere, In this video there were a lion figure, who reacted to user interaction and light change. Is this possible right now with the public release?

Most of these demos are built from ARCore SDK for Unity, NDK etc. They are not created from Android SDK only. I also not sure how well Android SDK will support animation, maybe still need to use Unity to do things like so.

**Comment by kunleLaundrapp** [comment]
> > +1 on this. By the way, I saw a demo video online somewhere, In this video there were a lion figure, who reacted to user interaction and light change. Is this possible right now with the public release?
> 
> @stewe93
> Most of these demos are built from ARCore SDK for Unity, NDK etc. They are not created from Android SDK only. I also not sure how well Android SDK will support animation, maybe still need to use Unity to do things like so.



> > +1 on this. By the way, I saw a demo video online somewhere, In this video there were a lion figure, who reacted to user interaction and light change. Is this possible right now with the public release?
> 
> @stewe93
> Most of these demos are built from ARCore SDK for Unity, NDK etc. They are not created from Android SDK only. I also not sure how well Android SDK will support animation, maybe still need to use Unity to do things like so.

@zhangruize do you do both unity and android development ? I want to learn Unity mainly for AR but worried about the switch from kotlin/java to C#

**Comment by kunleLaundrapp** [comment]
> > +1 on this. By the way, I saw a demo video online somewhere, In this video there were a lion figure, who reacted to user interaction and light change. Is this possible right now with the public release?
> 
> @stewe93
> Most of these demos are built from ARCore SDK for Unity, NDK etc. They are not created from Android SDK only. I also not sure how well Android SDK will support animation, maybe still need to use Unity to do things like so.

@zhangruize do you do both unity development and android ? ... I am keen to try Unity development but worried about the switch from java/kotlin to C# ?

**Comment by Nullifier1571** [comment]
hi all,let's use virocore,and wait google developer.
`https://github.com/viromedia/virocore`

**Comment by kunleLaundrapp** [comment]
> hi all,let's use virocore,and wait google developer.
> [https://github.com/viromedia/virocore](url)

this is a good alternative and can handle 3d animations.

**Comment by juanluislm** [comment]
@malik-at-work  let us know if you would like us to try a beta version!

**Comment by juanluislm** [comment]
@Nullifier1571  @kunleLaundrapp virocore is a good alternative if the type of work that you are doing does not require a GPL or MIT license

**Comment by haroldmthyng** [comment]
> > hi all,let's use virocore,and wait google developer.
> > [https://github.com/viromedia/virocore](url)
> 
> this is a good alternative and can handle 3d animations.

Virocore is a decent alternative for new and especially small projects. Or if you have the time to pivot. But for an existing larger framework it's just not feasible to switch to using Virocore without some heavy refactoring. If I was going to make that heavy of a change at this point, I'd probably just switch over to using Unity where the 3D capabilities open up 10 fold.

**Comment by juanluislm** [comment]
@haroldmthyng  +1 on that. It took me around 30 mins to get my fbx animations/blend shapes up and running in Unity. We ended up postponing this project, but I could have API-fied very quickly a cool experience in Unity if I had had green light.

Performance-wise, I don't know how different Unity would be from a native solution. My intuition is that a native framework or native solution would be faster, but I wouldn't underestimate unity

**Comment by haroldmthyng** [comment]
@juanluislm you sound like me. Dying to make the switch, but holding for that green light. In terms of 3D rendering, the engine is just solid and I would stack it's performance against a native solution any day. Especially when you count in physics, lighting, environment mapping, effects that list just goes on and on. The major drawback is size. Your project and app at a minimum will double.

But have to say the switch to using Sceneform is relatively easy as well. So similar to standard OpenGLES that it's easy to wrap.

**Comment by juanluislm** [comment]
@haroldmthyng  that's corporate life hahaha. I did notice how strong Unity is - and that a small prototype apk was about 15 MB haha. You can't have it all :/ .

I didn't get to do the switch, but from the API and sample projects, I foresaw a relatively easy transition

**Comment by malik-at-work** [comment]
An update on this. Although the code for this is in, the feature did not make the release train for the upcoming release and will not be included in version 1.6.  We hope to get it onto an release train as soon as possible.

**Comment by haroldmthyng** [comment]
@malik-at-work Appreciate the heads up. Was hoping it was in the up coming release, but hopefully it makes in way in after the holidays. Please keep us posted.

**Comment by pjmcnerney-mlbam** [comment]
@malik-at-work Thanks so much!

**Comment by AndroDevMili** [comment]
@haroldmthyng @juanluislm 
Guys I started with sceneform, but now seems like unity is a more complete solution as of now.
Is it worth it to invest time in learning Unity for mobile AR applications ??  
Thanks in advance.

**Comment by szczepanskikrs** [comment]
Any news on this one?

**Comment by MattSich** [comment]
Any update on this guys? Based on release history it looks like releases are made every two months so... early February?

**Comment by FabianTerhorst** [comment]
You can take a look at https://github.com/google/filament/releases to see the release state of the core.

**Comment by malik-at-work** [comment]
FBX based animation is in Sceneform 1.7, https://developers.google.com/ar/develop/java/sceneform/animation/

I'm sure there will be many follow on issues and requests, please open new threads for them.
