### ISSUE TITLE
Shaders

### ISSUE THREAD

**Issue by Jahmale** [google-ar/sceneform-android-sdk#110]
Does Sceneform currently support creating and/or importing shaders? I can't seem to find any documentation on this topic, so if it is supported is there perhaps something I can read through about the process?

**Comment by malik-at-work** [comment]
Custom Shaders are not supported as of v1.0.  They may be exposed in one of our upcoming releases.

**Comment by Jahmale** [comment]
Thank you for the response! Not sure if I should make seperate issues for them or not, since they are they same question, however: 

Does the same answer apply to: Stencil buffers?

**Comment by malik-at-work** [comment]
We do not expose stencil buffers at the moment.
