### ISSUE TITLE
How to create model(.bin, .obj, .gltf or .mtl ) for an .png to use in sceneform Android studio?

### ISSUE THREAD

**Issue by kirankaushal** [google-ar/sceneform-android-sdk#113]

**Comment by phoenixxt** [comment]
If all you wanna do is just show a 2D picture in space you can put that .png inside an ImageView and render the view using ViewRenderable.

**Comment by kirankaushal** [comment]
That's necessary to add 2d images with shades/ If compulsory them how to get shaders for viewing viewRenders in Android Studion

**Comment by malik-at-work** [comment]
Can you give more detail on what's being requested and how it's being used?
