### ISSUE TITLE
Sceneform without Camera session

### ISSUE THREAD

**Issue by marcos-dogonahorse** [google-ar/sceneform-android-sdk#12]
Hi google,

  Thank you so much for releasing Sceneform. I was wondering if there any possible way to use Sceneform without using the camera session. Example, if we wanted to show a 3D model on a static background image without any sort of camera feed. I was hopeing on getting this to work with the "SceneView", "Scene", and the ModelRender but of course that didn't work as expected (The render model appeared several time on the screen with corrupted line across it.) I understand that you guys are trying to focus on AR only but if this library becomes more open like SceneKit from iOS then it would become more helpful and an amazing tool to use 👍 

Thank you,
  - Marcos

**Comment by marcos-dogonahorse** [comment]
@malik-at-work Thanks for the head up. I am looking forward to the update :)

**Comment by malik-at-work** [comment]
Just updating this issue.  We have put this feature into an upcoming release.

**Comment by malik-at-work** [comment]
@nihalmistry can you open a different issue to track the new request? It would be helpful because we will likely close this one once the next release is made public.

**Comment by nihalmistry** [comment]
@malik-at-work Yes sure!

**Comment by Toione** [comment]
@malik-at-work Do you know which version or/and when this feature will released?

**Comment by malik-at-work** [comment]
I can not give a more specific ETA other than to say the code in our tree and will have to go through our internal release process to be released.  1.0 is the current version, so this would be fixed in our next release.

**Comment by Toione** [comment]
@malik-at-work Thanks for your attention, regards.

**Comment by malik-at-work** [comment]
We are aiming for release date in about a week.  This is not set in stone, many things could possibly come up to change release timing.

**Comment by dsternfeld7** [comment]
Fixed in Sceneform V1.3

**Comment by marcos-dogonahorse** [comment]
@dsternfeld7 Is there any documentation of how to do this with v1.3?
