### ISSUE TITLE
Model with double sided normals

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/sceneform-android-sdk#126]
Hello.

When I import a model[1] with double sided normals, the faces are displayed only one sided after importing it as Sceneform asset with the Android Studio plugin. The model is displayed correctly in MeshLab, for example.

How to get double sided normals displayed with Sceneform?

[1] Dennis Haupt, https://www.blendswap.com/blends/view/62419

**Comment by malik-at-work** [comment]
If the converter is outputting a one sided material, I think the next step would be to create a custom 2 sided material for this.  Custom material are released for Sceneform V1.3.  Docs are at https://developers.google.com/ar/develop/java/sceneform/custom-material

**Comment by michaelvogt** [comment]
Thanks for letting me know.

When I understand correctly, I need to create a .mat file, and add the path to this file in the materials object of the .sfa file. Is this correct?

There is actually a default .sfm file for two sided objects in the sceneform build folder, that contains the culling: none setting. When I enter the path to this file in the .sfa, the model is still displayed one-sided - also when I add doubleSided: true to the file.

Looks like I'm misunderstanding something.

**Comment by romainguy** [comment]
Here is a complete tutorial on how to use custom materials: “Custom Materials with Google Sceneform and ARCore” @bjdgames https://medium.com/@benjdoherty/custom-materials-with-google-sceneform-and-arcore-a930a30f867d

Note that setting doubleSided to true implies culling: none.

**Comment by michaelvogt** [comment]
Thanks Romain.

Looks like I did use it correctly yesterday, arriving at the wrong conclusion in the end though.

Going through the tutorial, the custom material also didn't work in the beginning. Until Android Studio crashed at one point. Reopening it showed the model as defined in the custom material.

What I didn't do yesterday was deleting the .sfa file.

Anyway, works now. Seeing the object double sided as set in the custom material.

Definitely a great new feature.

**Comment by michaelvogt** [comment]
I guess this issue can be closed.
The reason why I wasn't able to use custom material in the beginning was, that it seems to be necessary to delete a previously created .sfa file when adding a custom material.
