### ISSUE TITLE
Is it possible to download models and textures from server in real time?

### ISSUE THREAD

**Issue by geraldika** [google-ar/sceneform-android-sdk#130]

**Comment by malik-at-work** [comment]
Yes this is covered at https://github.com/google-ar/sceneform-android-sdk/issues/94

**Comment by geraldika** [comment]
@malik-at-work Is it possible to download from server textures and obj. files? I see the issue only about sfb

**Comment by malik-at-work** [comment]
Assets need to be converted to sfb first, we do not load obj at runtime.
