### ISSUE TITLE
How to place object not on surface?

### ISSUE THREAD

**Issue by Deishelon** [google-ar/sceneform-android-sdk#139]
Hello! 
Is there any way to place an object **not** on a surface (e.g table, floor), but somewhere in the world like in Just a line app

Thanks!

**Comment by malik-at-work** [comment]
Yes.  

The first thing to know is that you can create a node between the renderable you want to show and any anchor thats been created.  This has the effect of shifting your renderable.  


In the solar system demo the function [createPlanet](https://github.com/google-ar/sceneform-android-sdk/blob/c238849f050d1dfbb72fbb61bd931bd047f9cb5b/solarsystem/app/src/main/java/com/google/ar/sceneform/samples/solarsystem/SolarActivity.java#L415) does this.

Now for something floating in space, the "trick" is that it's not really floating completely free in space. It's just been created relative to some anchor position and has enough of an offset to not look like it is attached to the anchor.  You can calculate the distance between the phone and an anchor then add in an "offset" node to create something that has the appearance of floating in space.

**Comment by dsternfeld7** [comment]
You can create an anchor at an arbitrary location like this:

```
// Create an ARCore Anchor at the position.
Pose pose = Pose.makeTranslation(position.x, position.y, position.z);
Anchor anchor sceneView.getSession().createAnchor(pose);

// Create the Sceneform AnchorNode
AnchorNode anchorNode = new AnchorNode(anchor);
anchorNode.setParent(sceneView.getScene());
```
