### ISSUE TITLE
How capture image of the rendering model and save to local as png or jpg.

### ISSUE THREAD

**Issue by RavindraVirat** [google-ar/sceneform-android-sdk#140]
I want to capture the image of the model and save to local folder.
To achieve this I tried some code like arFragment.getArSceneView().getArFrame().acquireCameraImage()
this is giving Image class object, I thought from here I will get bitmap object but bitmap is always null.
Please update how to achieve this functionality.

**Comment by SimonMarquis** [comment]
You can use the `PixelCopy` API as described in the following codelabs:
https://codelabs.developers.google.com/codelabs/sceneform-intro/index.html?index=..%2F..%2Fio2018#14

**Comment by RavindraVirat** [comment]
Thanks, its working fine.
