### ISSUE TITLE
Gray lines in emulator camera view

### ISSUE THREAD

**Issue by geraldika** [google-ar/sceneform-android-sdk#141]
How to solve it?
![0230940e-430b-436b-b4c2-cf6538db1374](https://user-images.githubusercontent.com/17886201/41934659-f70d5ca6-798f-11e8-8107-eca72cb51666.jpeg)

**Comment by malik-at-work** [comment]
This looks like a bug. Can you give us any more info on your setup?

**Comment by jwmcglynn** [comment]
Both Sceneform 1.4 and the emulator fixed a few bugs that could explain this.  Please give Sceneform 1.4 and the emulator 28.0.1 canary a try (instructions in bug #148) and see if it resolves your issue.

Feel free to reopen and provide more information on your setup if you are still encountering the issue.
