### ISSUE TITLE
Translation across different planes

### ISSUE THREAD

**Issue by AKKamath** [google-ar/sceneform-android-sdk#144]
When a vertical plane and a horizontal plane intersect, when translating the object, it allows the object to move from a horizontal plane to a vertical plane. Can this be stopped, or can you force an object to only translate along a vertical/horizontal plane?

**Comment by gstanlo** [comment]
Are you using [TransformableNode](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/ux/TransformableNode)? That's how the TransformableNode works, which is utilizing [TranslationController](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/ux/TranslationController) which is doing the actual plane switching. 

You can disable horizontal planes, or you can implement your own Node type to use the TranslationController differently. Or this might be a useful feature to configure the TranslationController with.

**Comment by dsternfeld7** [comment]
As of Sceneform 1.4, this is now possible.


    `transformableNode.getTranslationController().setAllowedPlaneTypes(EnumSet.of(Plane.Type.HORIZONTAL_UPWARD_FACING));`
