### ISSUE TITLE
how to show boundingbox of a node?

### ISSUE THREAD

**Issue by scolar** [google-ar/sceneform-android-sdk#147]
can sceneform show boundingbox lick this:
![image](https://user-images.githubusercontent.com/11267256/42011282-5437f6c6-7ac5-11e8-8c60-dabfa79784d2.png)

**Comment by dsternfeld7** [comment]
There currently is no debug functionality for showing the bounding  box of a node. However, you can write some code to render the bounds yourself like this:

```
            // Create the andy and add it to the anchor.
            Node andy = new Node();
            andy.setParent(anchorNode);
            andy.setRenderable(andyRenderable);

            // Create node to display the bounds of the andy
            Node boundsNode = new Node();
            boundsNode.setParent(andy);
            MaterialFactory.makeTransparentWithColor(this, new Color(0.8f, 0.8f, 0.8f, 0.5f))
                .thenAccept(
                    material -> {
                      Box box = (Box) andyRenderable.getCollisionShape();
                      Renderable renderable =
                          ShapeFactory.makeCube(box.getSize(), box.getCenter(), material);
                      renderable.setCollisionShape(null);
                      boundsNode.setRenderable(renderable);
                    });
```

**Comment by RichardSantillan** [comment]
The code above is a good start! 
Change the following line:
`Renderable renderable = ShapeFactory.makeCube(box.getSize(), box.getCenter(), material);`
- Above creates a box, masking your object. You can use the center-point and the size of the box to create each individual outline edge. 

`box.getSize()` and `box.getCenter()` are Vector3(x, y, z) objects. So you can manipulate your cube into a line (or edge), then position each line accordingly (ex. `new Vector3(box.getCenter().x + box.getSize().x/2, box.getCenter().y, box.getCenter().z)`)

- Make a boundsNode for each line, then make andy the parent of all those boundNodes! Hope this helps anyone in the future!

**Comment by hshapley** [comment]
But this relies on a renderable having a CollisionShape, and currently only Box and Sphere shapes are supported. More importantly, CollisionShapes have to be created by the developer anyway. Is there any way to get the "extents" or "size" of an unknown/arbitrary model in code?

**Comment by chnouman** [comment]
@dsternfeld7 getCollisionShape returning null.
