### ISSUE TITLE
Diffuse texture does not appear when converting from .obj on Sceneform plugin

### ISSUE THREAD

**Issue by terezo** [google-ar/sceneform-android-sdk#150]
Hi again,

I am having troubles with getting diffuse texture when rendering `.sfb` converted by Sceneform plugin from `.obj`. Interesting is, that models converted by latest version of `google-ar-asset-converter` works (thanks to @necrostylery https://github.com/necrostylery/google-ar-asset-converter).

![sceneform_plugin](https://user-images.githubusercontent.com/38944393/42088358-8ae52db8-7b99-11e8-84ed-2f1cc73c8b3a.png)
**Sceneform plugin result**

![necrostylery](https://user-images.githubusercontent.com/38944393/42088410-a3dfe89e-7b99-11e8-804b-e3d3a76865b5.png)
**google-ar-asset-converter result**

**Setup:**
Android Studio 3.1.3
Build #AI-173.4819257, built on June 4, 2018
JRE: 1.8.0_152-release-1024-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-23-generic

**Assets, with both results:**
[sceneform_vs_necorstylery.zip](https://github.com/google-ar/sceneform-android-sdk/files/2149065/sceneform_vs_necorstylery.zip)

Any suggestions how to proceed are appreciate. We are debugging our assets with modelers and this inconsistency makes the process a bit insecure. I notice also troubles with shadow of sofa, which is better for Sceneform. Any advice on what could be wrong with our model would be amazing too.

**Comment by tpsiaki** [comment]
@terezo - Are you using the 1.3.0 version of the Sceneform gradle plugin or an earlier version?  You should see a dependency in your project gradle file that looks like this `classpath 'com.google.ar.sceneform:plugin:1.3.0'`

**Comment by terezo** [comment]
@tpsiaki my mystake, I was using earlier version. I was thinking I've got 1.3.0, since I reinstalled plugin from `settings` where I saw `Install v1.3.0`. It did not update my gradle dependency, I think that's not intuitive.

**Comment by abramyan** [comment]
@terezo Thanks. Can you please file a separate request for auto updating the gradle dependency?
