### ISSUE TITLE
Custom TwoPassesOneSide material

### ISSUE THREAD

**Issue by c0deminded** [google-ar/sceneform-android-sdk#151]
Hello.

I'm trying to create a custom material containing a two-pass fragment Shader to render a part of the model with an alpha channel.
I created a material definition file and managed to render the model part with the alpha channel correctly. But there is a problem with drawing this part from the outside of the model, because depthCulling is enabled.
I was able to achieve the desired effect in Unity, but I have no idea how to get the same in Sceneform.

The result in Android Studio.
![demo](https://user-images.githubusercontent.com/36959512/42100532-26088efa-7bc9-11e8-8f93-630f92207329.png)

The result I want to achieve.
![demo2](https://user-images.githubusercontent.com/36959512/42100624-5deef354-7bc9-11e8-9780-c30f199f778f.png)

The important thing is, this model has only one mesh and one material. 
So is it possible to achieve such a result without splitting this model mesh into two separate meshes with different materials?
By the way, this works correctly in scenekit with PBR shader.
There are more than thousand models created like this one, so that would be a real problem.

Here's material definition I used.

```
material {
    name: "Custom material",
    parameters: [
        {
            //BaseColor rgba factor
            name: "baseColorFactor",
            type: "float4",
        },
        {
            //BaseColor map sampler
            name: "baseColor",
            type: "sampler2d",
        },
        {
            //Normal map sampler
            name: "normal",
            type: "sampler2d"
        },
        {
            //Metallic factor
            name: "metallicFactor",
            type: "float",
        },
        {
            //Roughness factor
            name: "roughnessFactor",
            type: "float",
        },
        {
            //MetallicRoughness map sampler
            name: "metallicRoughness",
            type: "sampler2d"
        }
    ],
    requires: [
        "uv0",
        "color"
    ],
    shadingModel: "lit",
    blending: "transparent",
    transparency : "twoPassesOneSide",
}
fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor = materialParams.baseColorFactor * texture(materialParams_baseColor, getUV0());
        material.normal = texture(materialParams_normal, getUV0()).xyz;
        float3 metallicRoughnessSample = texture(materialParams_metallicRoughness, getUV0()).xyz;
        material.metallic = materialParams.metallicFactor * metallicRoughnessSample.b;
        material.roughness = materialParams.roughnessFactor * metallicRoughnessSample.g;
    }
}
```

And the code in shaderlab that shows the desired result.

```
Shader "Custom/Diffuse ZWrite" {
    Properties
    {
        _Color ("Main Color", Color) = (1,1,1,1)
        _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
    }
    SubShader
    {
        Tags
        {
            "Queue"="Transparent"
            "IgnoreProjector" = "True"
            "RenderType"      = "Transparent"

        }
        LOD 200
        Blend SrcAlpha OneMinusSrcAlpha
        Pass
        {
	    Cull Off
            ZWrite On
	    SetTexture [_MainTex] {
                Combine Primary * Texture
            }
        }
        UsePass "Transparent/Diffuse/FORWARD"
    }
    FallBack "Transparent"
}
```

**Comment by gstanlo** [comment]
I think multiple materials is the way to go here. There's fundamentally two different things being rendered, right? An opaque part, and a transparent part. 

The shaderlab code appears to be using depth testing and writing as well. What are you trying to do with a two pass material? I could see it working by masking opaque and then transparent parts of the texture, but that might be inefficient and isn't supported.

**Comment by c0deminded** [comment]
What do you mean by material? Material definition or material such as lambert? 

> There's fundamentally two different things being rendered, right?

Yes, I have to render two parts one of which should look like glass.

According to this [article](https://developers.google.com/ar/develop/java/sceneform/custom-material#material_block) depth testing and writing are enabled by default.
The documentation says 
> that the transparent object is first rendered in the depth buffer, then again in the color buffer

So I tried to use a another model with several meshes and materials and I was able to achieve the desired result by using two material definitions, but as long as I know there is no such option to create sfb with two material definitions.

**Comment by romainguy** [comment]
Two passes one side is not going to do what you wanted. Try twoPassesTwoSides or simply the default.

**Comment by c0deminded** [comment]
Yes, thank you, the glass was able to render as it should. 
Would like to know if it is possible to assign custom material definitions in the runtime? Or get submesh **by name** and assign materials using materialFactory?

**Comment by malik-at-work** [comment]
Closing this issue as resolved, for the second question we should open a new thread if it's still an active question.
