### ISSUE TITLE
How to export metallic/roughness textured assets from 3dsmax to sceneform

### ISSUE THREAD

**Issue by EugenioMiolo** [google-ar/sceneform-android-sdk#152]
Hi there,

What is the proper way to export an asset from 3dsmax with metallic/roughness maps to sceneform? I've attached an example .max file that I wish to get into sceneform, with the Specular map as Metallic, and Glossiness map as Roughness.

Here's a image from Sketchfab of how it should look like.
![image](https://user-images.githubusercontent.com/40700230/42108822-ff68ba16-7bb1-11e8-841a-4f518e335320.png)

Thanks in advance,
Eugenio

[Checker.zip](https://github.com/google-ar/sceneform-android-sdk/files/2150473/Checker.zip)

**Comment by gstanlo** [comment]
We would recommend trying to export it as FBX or glTF/2.0.

**Comment by EugenioMiolo** [comment]
Thanks for the answer @gstanlo,

Unfortunately it's not that simple. Have you tried to export this cube above in FBX/glTF and got metallic/roughness maps carried over to sceneform correctly?

Since there's no PBR material in 3dsmax, which one should I use to export the FBX? With a Standard material, where should I plug the Metallic and Roughness maps?

I was trying with my Metallic map in the Specular Color map, and Roughness in the Glossiness map. But after banging my head on the wall like hell for getting a lot of "Duplicate field name: BaseColor" errors, I found out that _the .sfb converter can only read the textures on 3 channels from the 3dsmax Standard material_: **_Diffuse_**, **_Specular Color map_**, and **_Reflection Map_**. Put a texture anywhere else and it will try to use it in the diffuse channel, therefore if you already have one there, it will throw you an error. So in the end I used the Metallic map in the Specular Color and Roughness in the Reflection slots in the 3dsmax Standard material.

This will avoid errors on the conversion, but will not do what I want, which is to have textures properly applied as metallic and roughness after the conversion. For that I had to edit the .sfm to remap the properties to their proper places. 

Regards,
-Eugenio

**Comment by AdrianAtGoogle** [comment]
Hi @EugenioMiolo, thanks for submitting this issue.
You're correct, the default material setup in 3dsmax does not support PBR; however, we support [stingray](https://www.autodesk.com/products/stingray/overview) materials.  A 3dsmax asset with a stingray PBR material exported to FBX should correctly import into sceneform.

**Comment by EugenioMiolo** [comment]
HI @AdrianAtGoogle,

Maybe I did something wrong, but I've tested exporting with a Stingray (a.k.a Interactive) material from 3dsmax and it didn't work. The converter gives me an error. IIRC, the docs only mention support for Stingray for Maya. I suppose it's because the way to setup a stingray material is different on them. In 3dsmax we have to plug into a DirectX material , while in Maya you have full Stingray PBS material.

You could give it a try with the cube above. But again, it didn't work for me.

Kind regards,
Eugenio

**Comment by AdrianAtGoogle** [comment]
Hi @EugenioMiolo, thanks for the clarification; what you describe definitely sounds like a bug.

Could I trouble you to export+upload the `Checker.max` file in your zip as an FBX?  I don't have a seat of 3dsmax available.

**Comment by EugenioMiolo** [comment]
Sorry for the very late reply @AdrianAtGoogle, I was involved in other projects and completely forgot about this.

I've attached the cube above exported as an ASCII FBX with embedded textures. It's using the DirectX Shader set to Interactive. Here's a screenshot of the shader in 3dsmax:
![stingray_material](https://user-images.githubusercontent.com/40700230/42588280-ba4a493e-8513-11e8-958d-dae1f7070c33.png)

[Cube.zip](https://github.com/google-ar/sceneform-android-sdk/files/2185473/Cube.zip)
Kind regards,
Eugenio

**Comment by AdrianAtGoogle** [comment]
Thanks @EugenioMiolo I'll follow up when I know more

**Comment by AdrianAtGoogle** [comment]
Hi @EugenioMiolo - Thank you for uploading the export.

Investigation yielded a few issues on our end to be fixed in an upcoming release.  After addressing them I was able to perform a default import of your asset; here is a screenshot you'll be able to reproduce once the fixes go out:
![image](https://user-images.githubusercontent.com/26070065/42777785-e4ce445a-88ef-11e8-9c82-d33f2a52a0e2.png)

**Comment by EugenioMiolo** [comment]
Looks great @AdrianAtGoogle ! Thanks a lot!

**Comment by AdrianAtGoogle** [comment]
Hi @EugenioMiolo - this issue should be fixed in the 1.4 release; base color alpha should control transparency as expected.
