### ISSUE TITLE
Rotating scene

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/sceneform-android-sdk#154]
I see a simple scene rotating around an augmented image anchor. Asked the question in the arcore tracker but was asked to open an issue here.

Here is a short video showing the effect:
https://drive.google.com/file/d/1Ot69sOUlIRn7YhvKTwmZM_VEw4Li3bzY/view?usp=sharing

The code is more or less taken from the samples:
`    Anchor anchor = image.createAnchor(image.getCenterPose());
     AnchorNode anchorNode = new AnchorNode(anchor);
     anchorNode.setParent(arFragment.getArSceneView().getScene());

    MaterialFactory
        .makeTransparentWithColor(context, new Color(1, .5f, .5f, .5f))
        .thenAccept(color -> {
           Renderable renderable = ShapeFactory.makeCube(
             new Vector3(0.42f, 0.0001f, 0.24f),
             new Vector3(-0.22f, 0, -0.10f), color);        

           Node node = new Node();
           node.setRenderable(renderable);
           node.setParent(anchorNode);
})`

**Comment by claywilkinson** [comment]
The Scene object in Sceneform is not rotatable.  If I understand your question correctly, you can add a node as a child of the anchorNode (as you did above), then call [setLocalRotation](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/Node.html#setLocalRotation(com.google.ar.sceneform.math.Quaternion)) on the node to rotate the node relative to the anchor.

**Comment by michaelvogt** [comment]
No, this rotation is not intentional, happens automatically and unwanted. This rotation is coming from either ARCore or Sceneform which I consider a bug.

**Comment by dsternfeld7** [comment]
This looks to me like it is a tracking issue with the Anchor, and not specifically related to Sceneform. You may be able to minimize the impact in Sceneform by doing anchorNode.setSmoothed(false). You may want to post a question about this in the [ARCore Android SDK github](https://github.com/google-ar/arcore-android-sdk/issues) as well.

**Comment by michaelvogt** [comment]
Thank you for your answer.

When you read the first sentence I original wrote you see that I already did create an[ issue for ARCore](https://github.com/google-ar/arcore-android-sdk/issues/460), which was closed as invalid with the 'suggestion' that I should open an issue here.

Is this meant to be a joke? I don't think this is funny, but horribly annoying.

**Comment by dsternfeld7** [comment]
I missed your reference to the other issue in your original post, sorry about that. Thanks for linking it!

Sceneform does not do any additional processing to the pose from the anchor except for doing a linear interpolation to the pose. The linear interpolation is turned off by doing anchorNode.setSmoothed(false).

As a test, you can also ignore using the AnchorNode class and set the position/orientation of the node to the pose from the anchor yourself (this must be done every frame). However, this shouldn't be functionally different from using AnchorNode with setSmoothed set to false.

```
Vector3 desiredPosition = new Vector3(pose.tx(), pose.ty(), pose.tz());
Quaternion desiredRotation = new Quaternion(pose.qx(), pose.qy(), pose.qz(), pose.qw());
node.setWorldPosition(desiredPosition);
node.setWorldRotation(desiredRotation);
```

Are you able to reproduce the issue using the augmented images sample in the Android ArCore SDK GitHub? If so, that could help us narrow down the cause. Has there been a noticeable difference in tracking quality from your experimentation with the arcoreimg tool?

Thanks!

**Comment by michaelvogt** [comment]
Thank you for your answer.

I hope you understand that the situation is pretty frustrating, seeing you and in the ARCore issue fingerpointig to each other. You are probably both even sitting in the same campus. 

I set setSmoothed to false as you suggested, with the problem still happening when pointing to the respective image on the computer screen. Which is the same as before. Can't test on location right now.

Yes, when I add my marker image to the sceneform augmented image sample, it looks to me as if the same effect happens, also pointing to the screen. I just changed the DEFAULT_IMAGE_NAME to 'office.png' (not sure why its a png) and USE_SINGLE_IMAGE. to true.

You can find the images I used here
https://photos.app.goo.gl/nZ4x4P1svjUzi5pa7

**Comment by michaelvogt** [comment]
Handled on the ARCore side now
