### ISSUE TITLE
Sceneform in build.gradle. Core not necessary?

### ISSUE THREAD

**Issue by malulleybovo** [google-ar/sceneform-android-sdk#161]
I noticed in multiple projects that I can ommit the line
```implementation "com.google.ar.sceneform:core:1.3.0"```
Leaving in gradle only the line
```implementation "com.google.ar.sceneform.ux:sceneform-ux:1.3.0"```
And the projects still build and run as usual.
I was wondering how that is possible since I thought "core" was necessary. Can I get some clarification on this? Is core only necessary if I am directly using OpenGL instead on sceneform or something similar?

**Comment by claywilkinson** [comment]
If you look at the dependencies of sceneform-ux, which are specified in the [.pom file](https://dl.google.com/dl/android/maven2/com/google/ar/sceneform/ux/sceneform-ux/1.3.0/sceneform-ux-1.3.0.pom), you can see that sceneform.core is declared as a dependency.  Gradle resolves the transitive dependencies when building, so declaring sceneform.core and sceneform-ux as dependencies in the sample is redundant.

The sceneform.core package contains the basic views and scene classes.  It can be used without the sceneform-ux package which contains  high level user interaction classes and helper classes.

You mentioned OpenGL.  Internally Sceneform uses OpenGL, but it not accessible by the callers.  We did this intentionally to keep the API simple to use and hide the complexities of low level OpenGL programming.
