### ISSUE TITLE
Capture rendered scene with custom resolution for video stream

### ISSUE THREAD

**Issue by dev4711** [google-ar/sceneform-android-sdk#164]
Capturing the screen of the rendered scene is working by calling captureScreenshot on the SceneView renderer in a regular interval or at every update. But it always provides a buffer of the image in the rendered resolution. This resolution can be very high and I need to scale it down to have a fluent stream when transmitting it over the network.
Is there a way to get the image in another resolution than the size it is rendered on the screen, so I do not need to scale it on the CPU?

**Comment by phoenixxt** [comment]
Can you provide the code you're using for creating a video  stream?

**Comment by dev4711** [comment]
I'm sorry I cannot provide you the code we use for video stream. But I can explain what we do.

I just call captureScreenshot on every frame like this:
arFragment.arSceneView.scene.setOnUpdateListener {
    arFragment.arSceneView.renderer.captureScreenshot(screenshotListener)
}

Then I use this image from the Renderer.OnScreenshotListener and process it in our own video stream module. This module does some tweaks to send the images as smooth as possible. For example only sending the diff between the images or dropping frames.
If the connection is not that good it is very helpful to send the image in a lower resolution than FullHD. To archive this it would be great to get the image from Sceneform in a custom resolution for example 720p or even less.

**Comment by malik-at-work** [comment]
We recommend using [PixelCopy](https://developer.android.com/reference/android/view/PixelCopy) which captures a Surface to a Bitmap.

The [Codelab for Sceneform](https://codelabs.developers.google.com/codelabs/sceneform-intro/index.html?index=..%2F..%2Fio2018#14) has an example on how to do this.

The renderer class used above is an internal implementation class and likely to change/move in future releases.

**Comment by SimonMarquis** [comment]
If I remember correctly my previous tests with the `PixelCopy` API, it worked fine but I don't think it was meant to be used to record a video stream since the time it took to render the scene to the bitmap was sometimes ~1 second.

**Comment by malik-at-work** [comment]
@SimonMarquis Looking at this, you are right this may be too slow for video recording.

**Comment by SimonMarquis** [comment]
After some more tests, I was definitely wrong...
The `PixelCopy.request()` API took on average 40 ms to copy pixels to a (already created) bitmap.
The `Renderer.captureScreenshot()` API took on average 250 ms to get the `ByteBuffer` and copy pixels to a (already created) bitmap.

With `PixelCopy`  you could achieve ~25fps.
I did not try but it might be possible to call this API on each AR frame update, granted you have 'ready-to-use' bitmap queue.

**Comment by dev4711** [comment]
I just need the ByteBuffer / byte array not a actual Bitmap. So PixelCopy it not really useful for me.

@malik-at-work Why does Sceneform provide something like captureScreenshot when you shouldn't use it?

**Comment by malik-at-work** [comment]
@dev4711  The class Renderer was intended as an internal support/implementation class only.  I'd consider it a bug that it's it's not named or behind a function that clearly indicates that.  Currently this function isn't actually used anymore in our code, we've switched over to using PixelCopy so it was never exposed.

It's fair to request a supported version of captureScreenshot for use cases PixelCopy doesn't support, but if that happens it would likely be moved to another class and be written differently.

**Comment by SimonMarquis** [comment]
Also, it seems that `PixelCopy.request()` is run on the main rendering thread...
When I try to request copies as fast as possible (from a background thread, and start a request after every callback), the framerate of the ArView becomes very low, and the application no longer feels responsive.

**Comment by claywilkinson** [comment]
You can use [SceneView.startMirroringToSurface()](https://developers.google.com/ar/reference/java/sceneform/reference/com/google/ar/sceneform/SceneView#startMirroringToSurface(android.view.Surface,%20int,%20int,%20int,%20int)) to mirror the SceneView contents to another surface.

See https://developers.google.com/ar/develop/java/sceneform/video-recording for more details and the [Video Recording Sample](https://github.com/google-ar/sceneform-android-sdk/tree/master/samples/videorecording).

**Comment by ranaaditya** [comment]
Hi , i am taking screenshot of my device  to a surface  using Android's  MediaProjection API and when i am trying to convert the surface  into bitmap using PixelCopy.request(), I am getting a blurred bitmap .
How can i solve this problem , plz help me to  get out of this problem _/ \_
