### ISSUE TITLE
Error while Import scene from 3D object from Android studio

### ISSUE THREAD

**Issue by Sudhakaraks03** [google-ar/sceneform-android-sdk#168]
ERROR: Jsonnet Error: [1]: RUNTIME ERROR: Duplicate field name: "BaseColor"
i tried to Import scene from 3D Asset in the Google quick start project Solar system while import i got the above Error
3D Asset Link:https://www.mixamo.com/#/?page=1&type=Motion%2CMotionPack 

Thanks

**Comment by gstanlo** [comment]
Somehow the model is working fine for me -- I downloaded as a regular FBX file `xbot.fbx` and imported it into Sceneform 1.3. Is that what you did?

**Comment by malik-at-work** [comment]
Is this still an issue? Please retry with our latest release.
