### ISSUE TITLE
Drawing directly to arSceneView with OpenGL (Custom renderers)

### ISSUE THREAD

**Issue by johnwedgbury** [google-ar/sceneform-android-sdk#169]
There seems to be plenty of opportunities to perform events directly before each frame is drawn, such as 
Scene.OnUpdateListener and Node.onUpdate, but is there a way to draw on top of the background?

My understanding is that ArSceneView is probably a feature-rich SurfaceView from the earlier versions, so is there a way to tap into onDrawFrame after the background has been rendered? We'd really like to use Sceneform in conjuction with custom renderers.

Apologies if this isn't the best place for our query.

**Comment by malik-at-work** [comment]
Thanks for question! The current implementation of Sceneform is backed by OpenGL ES, but we've intentionally put it on another thread and completely behind our API as future versions of Sceneform may not be on OpenGL ES at all.  This has the effect that Sceneform is really not intended to mix with custom rendering.

If I absolutely needed a custom renderer I would build on ARCore directly and handle all the rendering.

**Comment by romainguy** [comment]
Could you give more information about what your custom rendering needs are? The underlying renderer can do a lot more than what is currently exposed through the Sceneform APIs. You can also use custom materials as of Sceneform 1.3.

**Comment by johnwedgbury** [comment]
Thanks for your responses.

Specifically at the moment is the need for rendering videos, due to the lack of VideoView support with ViewRenderable - was hoping it would become possible through this avenue.

**Comment by johnwedgbury** [comment]
Great - thanks. I'll keep an eye on release notes for future versions.

**Comment by romainguy** [comment]
Yes (provided you find using the camera APIs easy :).

**Comment by JessHolle** [comment]
Can I just go ahead and setBackground(Drawable) within Scene.OnUpdateListener() or SceneView.doFrame(long) for now?  In other words, do I really need the external textures support just to produce the camera background?

(And, no, I won't be using the camera APIs, but rather Vuforia's access to the camera pixels.)

**Comment by romainguy** [comment]
This would only work if Sceneform lets you render on a transparent background. I don't know if this currently works. Also using a Drawable to draw the camera stream will be quite inefficient.

**Comment by JessHolle** [comment]
Both of those are what I was afraid of.  I guess I'll anxiously await a new version providing this feature.

**Comment by romainguy** [comment]
`SceneView` is a `SurfaceView` which can't draw a background. The documentation should be clearer. The way `SurfaceView` works make it a bit difficult to do what you want actually. BTW I'm not sure how you'd use a camera frame with a `Drawable` anyway. If Vuforia gives you a `Bitmap` you can use it as a texture in Sceneform already.

**Comment by JessHolle** [comment]
Vuforia gives raw data from which I can easily produce a YuvImage.  In any case, looking at the Texture and Texture.Builder APIs, I'm not sure how one applies dynamic image data as a texture in SceneForm (nor how one dynamically defines a material shader for that matter -- but that's another matter entirely).

**Comment by dsternfeld7** [comment]
Sceneform 1.4 has some new APIs that should help with this.

There is an example [here](https://github.com/google-ar/sceneform-android-sdk/tree/master/chromakeyvideo) that shows how to play a chroma keyed video using an ExternalTexture. This sample also shows how to write a custom material, the custom material reference is [here](https://developers.google.com/ar/develop/java/sceneform/custom-material).

As of Sceneform 1.4, you can also create a Texture using an android bitmap.

`CompletableFuture<Texture> bitmapTextureFuture = Texture.builder().setSource(bitmap).build();`

Please feel welcome to open new issues for problems you encounter using the new APIs.
