### ISSUE TITLE
When the arcore will support the recognition of qr code

### ISSUE THREAD

**Issue by slavayus** [google-ar/sceneform-android-sdk#173]

**Comment by malik-at-work** [comment]
Thanks for the question.
How exactly are you using the QR Code? I'd like to understand the use case better.

**Comment by slavayus** [comment]
As augmented images pictures only without saving them in the database. Also get text from qr code.

**Comment by gstanlo** [comment]
This is a cool idea but I think this is more of an [ARCore](https://github.com/google-ar/arcore-android-sdk/issues) feature request. There's also a possibly related thread here: https://github.com/google-ar/arcore-android-sdk/issues/401.

**Comment by claywilkinson** [comment]
Closing this here since the feature request would be part of ARCore, and is not related to rendering or the Sceneform API.
