### ISSUE TITLE
Unable play Animation for Animated 3D objects 

### ISSUE THREAD

**Issue by Sudhakaraks03** [google-ar/sceneform-android-sdk#176]
Hi, i'am  downloading Animated 3D objects from https://www.mixamo.com/#/?page=1&type=Motion%2CMotionPack and the Animation Effect Added are unable to play and it's showing it as a plain 3D object how should render or play the Animation of 3D objects using sceneForm 
Thanks...

**Comment by malik-at-work** [comment]
Thanks for the question!

Sceneform 1.3 doesn't support fbx animation. We're tracking the request in #11

**Comment by dsternfeld7** [comment]
Closing as duplicate.
