### ISSUE TITLE
Can we add 3D Texts in AR using Sceneform?

### ISSUE THREAD

**Issue by rohitagarwal3011** [google-ar/sceneform-android-sdk#177]
Can we take text as input and create 3D object with the same text and show it in AR using Sceneform and ARCore?

**Comment by rohitagarwal3011** [comment]
So using this, if I render a TextView then it will show up as a 3D Text View in AR?

**Comment by gstanlo** [comment]
Yup, you can see a preview of it [here](https://developers.google.com/ar/develop/java/sceneform/create-renderables).
![image](https://user-images.githubusercontent.com/26283995/42469750-74e02672-836d-11e8-850b-38fc50b4a38d.png)

**Comment by rohitagarwal3011** [comment]
Awesome.. Thanks a ton!!

**Comment by rohitagarwal3011** [comment]
@gstanlo Thanks a ton.

**Comment by ShivamGarg2910** [comment]
Is it possible to create multiple instances of these TextView in order to create textboxes with different texts in them?
