### ISSUE TITLE
Can we render 3D objects from Google Poly in an AR in real-time ?

### ISSUE THREAD

**Issue by rohitagarwal3011** [google-ar/sceneform-android-sdk#178]
Can we fetch .obj and .mtl files from Google Poly API and convert them to  .sfa and .sfb files programmatically in real-time?

**Comment by gstanlo** [comment]
Unfortunately you cannot due to the conversion tools not being available on Android.

**Comment by rohitagarwal3011** [comment]
How will i get the necessary .sfa and .sfb files for the 3D objects?

**Comment by agselling** [comment]
Use this: https://github.com/necrostylery/google-ar-asset-converter
with Linux script for Linux shell and you can convert to .sfa and .sfb

**Comment by rohitagarwal3011** [comment]
@agselling  Awesome .Thanks a ton!!
