### ISSUE TITLE
Low camera framerate with ViewRenderable ImageView

### ISSUE THREAD

**Issue by eugenelozada** [google-ar/sceneform-android-sdk#181]
I'm using a ViewRenderable that has an ImageView and I noticed that with certain kinds of images, for example the mipmap/ic_launcher icon and the one I below:

![stock_image](https://user-images.githubusercontent.com/21036287/42490464-f63eba46-8442-11e8-9c13-0f3087e9a440.jpg)

The camera framerate drops considerably when I display the renderable.  Any idea what might be causing this?

Other images work fine though.  For example the default sceneform hand scanning image, when displayed on that same view renderable seems to be ok.

**Comment by romainguy** [comment]
Is this the actual image you are using? Could you please let me know how large (in pixels) the images you've tried are?

**Comment by dsternfeld7** [comment]
ViewRenderable's are inherently a performance sensitive feature because of how it requires the Views to be drawn and then copied to an OES texture. ViewRenderable's with large images or particularly complex view hierarchies will cause performance issues.

However, there is a performance improvement coming in an upcoming release that will significantly improve the performance of static content in views. It should solve this issue for large static images, though if the ViewRenderable is also displaying animation the performance benefit will be small.

In the meantime, if all you are doing is displaying a static image, then you could work around this by creating an SFB of a quad with this image as the texture, which will be more performant.

**Comment by eugenelozada** [comment]
@romainguy - The embedded image is what I used.  It's a 600x527px, 32bit JPEG.  I've tested reducing the size 50% and while there is an improvement, the choppiness of the camera is still noticeable.  This is my view hierarchy and it's not very complicated:

 
CardView
    |- Linear Layout
             |- TextView
             | - ImageView

I've tested a ViewRenderable with just an ImageView and same choppiness.

In my testing, using the same view hierarchy  the default android launcher icon created which is a 144x144 32 bit PNG also causes this issue.  The other image I tested is a the default image used plane finding controller (drawable/sceneform_hand_form) which is a 192x192 16-bit PNG has way better performance.  I'll do some tests later when I get back to the office if it's the color depth that's causing the problem.

@dsternfeld7 - yeah I've tried displaying that same image as a texture in a quad that I just imported in as an asset and it was ok.  Unfortunately, I'm prototyping an indoor location/points of interest using AR for a client so the content is meant to be dynamic.  ViewRenderable makes this extremely easy since I found that manipulating the View objects also conveniently updates the renderable.

Anyway looking forward to any update you may have.  I'd much rather do this prototype in Kotlin/Sceneform rather than Unity given other features I'm being asked to build.

**Comment by dsternfeld7** [comment]
Thanks! I'll investigate the performance characteristics of those specific images. Regardless, I believe this problem will go away with the next release.

**Comment by dsternfeld7** [comment]
Sceneform 1.4 was just released, which I believe should help resolve this performance problem for you. Can you try it out and let us know if it helps?

**Comment by eugenelozada** [comment]
Hi @dsternfeld7  - I tried the exact app with the original image I linked at the start of this thread and the performance is significantly improved. There are a few dropped frames when the ViewRenderables are first spawned, but after that the frame rate stabilises.  I think we can consider this item closed.

Thanks!

**Comment by bhavikshah1995** [comment]
@eugenelozada How did you use ImageView within ViewRenderable? Could you perhaps give me an example code segment?
