### ISSUE TITLE
Animated 3D Objects are not working 

### ISSUE THREAD

**Issue by Sudhakaraks03** [google-ar/sceneform-android-sdk#182]
Hai i downloaded 3D Animated object and i'am importing it using sceneForm successfully in my Android Studio, but i'am not getting Any animation Effect can u help me how to make that work in my app.(I'am trying to do like google demo App - scaring lion Animation )
Thanks.

**Comment by malik-at-work** [comment]
Thanks for the question!

Sceneform 1.3 doesn't support fbx animation.  We're tracking the request in https://github.com/google-ar/sceneform-android-sdk/issues/11

**Comment by lynnmyatminn** [comment]
https://developers.google.com/ar/develop/java/sceneform/animation/

**Comment by Sudhakaraks03** [comment]
That's Great and Thank you Very Much for your Information
