### ISSUE TITLE
Rotating proper TransformableNode

### ISSUE THREAD

**Issue by terezo** [google-ar/sceneform-android-sdk#183]
Hi,

why the `RotationController` on TransformableNode does not work the same way as `TranslationController`? I mean it's called (rotated) even the gesture does not collide with TransformableNode. I assume `TranslationController` uses CollisionShape to decide whether translate the node or not. `RotationController` appears to be called on currently selected node, even the selected node is out of view and user is viewing different node.

Rotating something out of view it's not intuitive, especially when comparing to TranslationController logic (which I think is intuitive).

Am I doing something wrong? Any suggestions how to rotate only visible node (to user) which collide with twisting gesture, not anywhere on the screen?

**Comment by chnouman** [comment]
@malik-at-work  any update on this because I want to enable rotation only with one finger swipe.
