### ISSUE TITLE
Objects are not placed on the surface.?

### ISSUE THREAD

**Issue by rohitagarwal3011** [google-ar/sceneform-android-sdk#189]
I have added objects from google poly but now when i add them, they are not placed on the surface. They keep floating at a height above the surface. So what properties of the object i should change that they will be placed on the surface.

**Comment by rohitagarwal3011** [comment]
@claywilkinson It will be great if you can help me out with this issue asap. Thanks.

**Comment by claywilkinson** [comment]
The issue probably is the origin of the model.  For example it could be in the center of the model causing it be half above and half below the plane.  In your case it sounds like the origin is below the mesh of the model, causing it to float.

The options are: 
1. adjust the model using a modeling tool.
2. manually set  the local position below the anchor node.
3. Wait for the feature of resetting the origin in the .sfa file. In an upcoming release, you'll be able to reset the model's origin in the .sfa file.

**Comment by rohitagarwal3011** [comment]
Okay great. Thanks for the promt help.

**Comment by vishalvanpariya** [comment]
@rohitagarwal3011 can you give a solution of this problem?
