### ISSUE TITLE
Texture Tiling is not available

### ISSUE THREAD

**Issue by AadeshEx2** [google-ar/sceneform-android-sdk#190]
Hi,
I want to use seamless textures to the 3D Model, but unfortunately I can not tile the textures. Please help me out to do this.

Regards,
Aadesh

**Comment by dsternfeld7** [comment]
You can tile textures by setting the wrap mode in the sampler. This can be done in the .sfa file by setting the wrap_s and wrap_t to Repeat. Documentation for this can be found [here](https://developers.google.com/ar/develop/java/sceneform/sfa).

If you are loading the Texture at runtime, you can create a [Texture.Sampler](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/rendering/Texture.Sampler) and call setSampler on the Texture or Texture.Builder

**Comment by AadeshEx2** [comment]
I meaning to ask that UV tiling for textures in numeric. Lets say by default texture is at 1X1 tiling, but I want to make it 20X20 tiling to repeating the texture on the 3D model. Please resolve this issue, if possible.
![repeat_1x1](https://user-images.githubusercontent.com/41145805/42673493-58b21432-8689-11e8-8718-c31653cbda40.JPG)
![repeat_20x20](https://user-images.githubusercontent.com/41145805/42673494-5919bdb2-8689-11e8-92a6-18646daa3f22.JPG)

**Comment by gstanlo** [comment]
It looks like there's a bug in the viewer that makes it appear that wrapping isn't working, but it should work on device.

I don't believe there's a way to set a UV scale in an SFA file -- you could use a custom material and do it there. Otherwise, baking in the wrapped UVs into the model is the best bet.

**Comment by AdrianAtGoogle** [comment]
Hi @AadeshEx2 - Thank you for reporting this issue; The plugin does not interpret wrap modes in the SFA correctly, so a model with texture coordinates outside the range [0..1] will not preview correctly (wrap modes are interpreted correctly by the runtime).  This is fixed in an upcoming release.

**Comment by AdrianAtGoogle** [comment]
Fixed in the 1.4 release - thanks again
