### ISSUE TITLE
TransformableNode with attached renderable has null collision shape

### ISSUE THREAD

**Issue by carterhudson** [google-ar/sceneform-android-sdk#191]
I get the impression from https://github.com/google-ar/sceneform-android-sdk/issues/104 that a TransformableNode should get its collision shape from its attached renderable, but this doesn't seem to be happening in my case. Upon inspection of my TransformableNode instances, all of their collision shapes are null, despite rendering on the screen properly.

**Comment by dsternfeld7** [comment]
The CollisionShape on the node itself acts as an override for the collision shape from the renderable. If you need to access the collision shape, try doing Renderable.getCollisionShape().

**Comment by carterhudson** [comment]
I'm mostly trying to see what kind of Physics simulation, if any, get provided out-of-the-box. I'm trying to implement an AR dice rolling app, but I'm struggling with the docs and API. I'm beginning to think what I want to accomplish isn't possible through Sceneform?

**Comment by dsternfeld7** [comment]
Sceneform does not include physics. You can test when two objects are overlapping using Scene.overlapTest and Scene.overlapTestAll, but it doesn't provide contact information, or any kind of collision resolution / rigid body.

However, it is possible to use a physics library and then drive the positions of the nodes from that physics library yourself. You could also consider using Unity for your use-case.

**Comment by carterhudson** [comment]
Thanks, I'll look at starting over with Unity

**Comment by thomasflynn** [comment]
If you want to stick with AndroidStudio and Java, you can take a look at the GearVR Framework (gearvrf.org github.com/GearVRf).  We have a bullet physics extension and a 'mixed reality' extension (arcore support).

**Comment by carterhudson** [comment]
I'll check that out as well; thanks for the suggestion!
