### ISSUE TITLE
Failed to call function: ArSession_createImplementation

### ISSUE THREAD

**Issue by RavindraVirat** [google-ar/sceneform-android-sdk#193]
I got this issue when I am launching Sceneform activity - 

E/StandardArFragment: Exception: com.google.ar.core.exceptions.UnavailableException
com.google.ar.core.exceptions.FatalException: Application manifest must contain meta-data com.google.ar.core.min_apk_version

For the exception above I mentioned meta-data in manifest - 
meta-data android:name="com.google.ar.core.min_apk_version" android:value="24"

then I am getting below exception - 
[blaze-out/android-arm64-v8a-opt/genfiles/third_party/arcore/ar/core/android/arcore_c_shim_function_impls.inc:463] CHECK failed: expression='"false"' Failed to call function: ArSession_createImplementation, 
this function version: 171127000 is higher than requested min apk version.

Please guide the solution here.

**Comment by gstanlo** [comment]
Which activity is this? Do the ARCore samples work for you, such as hello_ar_java?

**Comment by gstanlo** [comment]
You should be able to remove the min_apk_version line and make sure that in your app build.gradle file. If that doesn't work, can you share the list of dependencies in your app build.gradle file?

**Comment by RavindraVirat** [comment]
Thanks for reply.

Scenform is working properly as a separate app what I downloaded from GitHub.

In the same app I have put hello_ar_java related code also for that too I am getting the same error.

Now I put all sceneform code to my another application, after putting all when I am trying to run then I am getting the issues I mentioned above.

I am using compileSDk version and targetsdkvrsion as 27, and dependency is 27.1.1

**Comment by claywilkinson** [comment]
Can you look at your AndroidManifest.xml and compare it to the working sample? 
The arcore.aar does merge in additional metadata when building.  You should not need to set min_apk_version (in fact, it will probably break the app).

 The important entries are in the `<manifest>` element:
```
    <!-- Always needed for AR. -->
    <uses-permission android:name="android.permission.CAMERA" />
    <!-- This tag indicates that this application requires ARCore. This results in the application
        only being visible in the Google Play Store on devices that support ARCore. -->
    <uses-feature android:name="android.hardware.camera.ar" android:required="true"/>
```

And in the `<application>` element:
```
        <!-- This tag indicates that this application requires ARCore. This results in the
            application only being visible in the Google Play Store on devices that support
            ARCore. -->
        <meta-data android:name="com.google.ar.core" android:value="required" />
```

**Comment by RavindraVirat** [comment]
I tried this but still same error.
I think arcore aar file is not merging properly, could please guide some steps to check whether .aar file is merged and if still not working then can we have some manual steps for merging.

**Comment by gstanlo** [comment]
Are you still receiving the error `Failed to call function: ArSession_createImplementation,
this function version: 171127000 is higher than requested min apk version.` ?

**Comment by claywilkinson** [comment]
@RavindraVirat  - this thread has become idle.  Did you resolve your issue?  Can this issue be closed?  Thanks!

**Comment by RavindraVirat** [comment]
Hi,

Issue still exist.

**Comment by abramyan** [comment]
Can you please check your project build setup? This looks like a build issue. You should not need to set min_apk_version.

**Comment by abramyan** [comment]
@RavindraVirat were you able to resolve your build issue? Please make sure to have the latest ARCore and Sceneform releases.
