### ISSUE TITLE
[question]make Viewrenderable have thickness 

### ISSUE THREAD

**Issue by ernieboogie** [google-ar/sceneform-android-sdk#194]
Hi guys, i'm using sceneform for developing ar gallery on android.

so i added imageview on my surfaceview and it worked well.

but i want my artwork viewrenderable become more thicker like 3d cube

is there any way to adjust Viewrenderable's thickness programmatically?
(i'm not saying metertopixel ratio.)

thank you for your good product, and sorry for my bad english.

**Comment by gstanlo** [comment]
What if you drew a box model behind the ViewRenderable that was scaled to the same size?

**Comment by ernieboogie** [comment]
i also thought that way, but i didn't try
cause, all the artworks has different (x,y) ratio.
so we need different box model for each artworks

**Comment by eugenelozada** [comment]
Create the box using the 4 corners of a frame.  Then align them to the corners of your image by offsetting them from the center using rhe known height and widthnof the image.

**Comment by ernieboogie** [comment]
really thank you, for your answers!
i will try and and update this issue

thank you !

**Comment by ernieboogie** [comment]
hi guys, 
i found a way to make 3d cube programmatically, when i read issue#197
(https://github.com/google-ar/sceneform-android-sdk/issues/197)

he used Shapefactory for rendering 3d cube, and it can scale size by input
i think this way can solve the thickness problem by 2 way
1) draw box model behind imageview renderable
2) or make artwork image texture for box renderable

i don't know whick one is better, but when i apply that code the box model appear.
so i think this issue should be closed

really thanks you guys i love you
