### ISSUE TITLE
Sceneform Tools(Beta) Viewer make Mac os Frozen

### ISSUE THREAD

**Issue by wangkunlin** [google-ar/sceneform-android-sdk#2]
Android Studio 3.1.2
Build #AI-173.4720617, built on April 14, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.1

Once change Viewer size , the whole osx will frozen

In osx Activity Monitor  , kernel_task use 4.5 GB memory, AS use 1.07 GB

then I have to force shut down system and restart

**Comment by tpsiaki** [comment]
@wangkunlin - thank you for the report.  We are looking into this.  A couple of questions to help us debug:

Do you recall whether it froze immediately when you started resizing the window, or was it after trying a few different sizes?  At the time, was Android studio running on an external monitor, or on a built-in screen (i.e. MacBook, iMac screen)?

Additionally, if you're able to, will you send the gpu model(s) that your mac was running (System Information > Graphics/Displays > Click each GPU and attach the detail information displayed).

Thank you!

**Comment by wangkunlin** [comment]
@tpsiaki AS run at external monitor (dell U2414H) , I think it froze immediately.
sorry ,my computer language is Chinese.
Is this information you need?

Intel Iris Pro：
  芯片组型号：	Intel Iris Pro
  类型：	GPU
  总线：	内建
  VRAM（动态，最大值）：	1536 MB
  供应商：	Intel
  设备 ID：	0x0d26
  修正版 ID：	0x0008
  Metal：	支持，功能集 macOS GPUFamily1 v3
  显示器：
彩色 LCD：
  显示器类型：	内建 Retina LCD
  分辨率：	2880 x 1800 Retina
  帧缓冲深度：	24 位彩色 (ARGB8888)
  主显示器：	是
  镜像：	关
  联机：	是
  旋转：	支持
  自动调节亮度：	否
DELL U2414H：
  分辨率：	1920 x 1080 @ 60 Hz
  帧缓冲深度：	24 位彩色 (ARGB8888)
  显示器序列号：	GN64V6BE30YL
  镜像：	关
  联机：	是
  旋转：	支持
  自动调节亮度：	否
  连接类型：	DisplayPort

**Comment by wangkunlin** [comment]
other system information
版本  10.13.1 (17B1003)
MacBook Pro (Retina, 15-inch, Mid 2014)
处理器  2.2 GHz Intel Core i7
内存  6 GB 1600 MHz DDR3
图形卡  Intel Iris Pro 1536 MB

**Comment by tpsiaki** [comment]
@wangkunlin - thank you for the system info.  We are looking into this further and will update here once we have more information.

**Comment by izdi** [comment]
I had the same issue running on external monitor Dell U2515H. 
I resized a few times and the selected the file `andy.sfa` and it's frozen.

My specs if it could help

Intel Iris Plus Graphics 640:

  Chipset Model:	Intel Iris Plus Graphics 640
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x5926
  Revision ID:	0x0006
  Metal:	Supported, feature set macOS GPUFamily1 v3
  Displays:
Color LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2560 x 1600 Retina
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
DELL U2515H:
  Resolution:	2560 x 1440 (QHD/WQHD - Wide Quad High Definition)
  UI Looks like:	2560 x 1440 @ 60 Hz
  Framebuffer Depth:	30-Bit Color (ARGB2101010)
  Display Serial Number:	9X2VY57M052L
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Adapter Type:	Apple USB-C Digital AV Adapter
  Automatically Adjust Brightness:	No
  Adapter Firmware Version:	2.35

**Comment by tpsiaki** [comment]
The system-hang occurring from resize is fixed in the latest version of the Sceneform Tools plugin.

To ensure you are on latest, in Android Studio, check for updates and apply the Google Sceneform Tools (Beta) 1.0.0 -> 1.0.1 update.
