### ISSUE TITLE
Texture added to ShapeFactory Cube shows up horizontally flipped

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/sceneform-android-sdk#202]
Not sure if this is a bug or not, just wondering if I'm doing something wrong or missing a setting, but textures added to a ShapeFactory cube show up horizontally flipped for me. 

          Texture.builder()
              .setSource(getApplicationContext(), R.drawable.magistrates_office_jp)
              .build()
              .thenAccept(texture -> {
                MaterialFactory.makeOpaqueWithTexture(getApplicationContext(), texture)
                    .thenAccept(material -> {
                      ModelRenderable cube = ShapeFactory.makeCube(
                          new Vector3(new Vector3(1f, 1f, 1f)), Vector3.zero(), material);
                      
                      Node node = new Node();
                      node.setRenderable(cube);
                      node.setParent(anchorNode);
                    });
              });

**Comment by Berenice2018** [comment]
@michaelvogt I have the same problem !!

**Comment by michaelvogt** [comment]
Yes, I have seen it mentioned in several issues, but it was never talked about directly. So I thought creating a separate issue might be a good idea. Originally I thought its just me doing something stupid.

**Comment by dsternfeld7** [comment]
Thanks for the report, this is definitely a bug. I've verified it and it will be fixed in an upcoming release.

**Comment by dsternfeld7** [comment]
This is now fixed in Sceneform 1.4.
