### ISSUE TITLE
Detect closest feature point

### ISSUE THREAD

**Issue by smahurkar** [google-ar/sceneform-android-sdk#203]
If I hit test using a 2D coordinate on the screen, often the HitResult list can be empty. Is it possible to return the closest point that is a trackable instead of an empty list?

**Comment by gstanlo** [comment]
I believe this would be a better question for the ARCore team: https://github.com/google-ar/arcore-android-sdk/issues/new

**Comment by smahurkar** [comment]
Thank you.
Created at: https://github.com/google-ar/arcore-android-sdk/issues/495
