### ISSUE TITLE
How to batch the transformation model

### ISSUE THREAD

**Issue by ToadPrincess** [google-ar/sceneform-android-sdk#204]
We have plenty of models(obj and. Sfa model format) .How to batch conversion model..Is there any batch conversion tools. Or a 3 ds Max plug-in, generated SFB file directly.Or another does not rely on Android Studio tool.

**Comment by gstanlo** [comment]
The android studio tool uses the converter.exe tool that should be in your project directory.

Additionally, you can specify directories in gradle. For example: 

```
sceneform.asset('sampledata/lots_of_models_in_this_directory/',
        'default',
        'sampledata/models/',
        'src/main/res/raw/')
```

**Comment by ToadPrincess** [comment]
Thank you for your reply 

Maybe you didn't understand my point,Because we have many models, we need a tool that can transform multiple models at once.

I used the sceneform plug-in in Android Studio, but only converted one at a time.It relies on Android stuidio, which is not easy for model developers to use. So I need a tool to convert many models at one time

**Comment by ToadPrincess** [comment]
@necrostylery thank you so much.
I found this last week and it's already in use.
This works well and we want a GUI because it's for use by modeling engineers.

Thanks!!
