### ISSUE TITLE
OnTapListener only partially available

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/sceneform-android-sdk#208]
When creating a Shapefactory cube (either with color or texture) and attach a OnTapListener, only the lower right quarter of its surface reacts to tabs. Did not specifically check with a sphere, but I remember having had the problem that a sphere also did react to taps only from a specific location.

The is the code used in HelloSceneform
          `          MaterialFactory.makeOpaqueWithColor(getApplicationContext(), new Color(0.f, .5f, .5f, 1))
              .thenAccept(material -> {
                andyRenderable = ShapeFactory.makeCube(new Vector3(1f, 0.0001f, 1f), Vector3.zero(), material);
                Node node = new Node();
                node.setRenderable(andyRenderable);
                node.setParent(anchorNode);

                node.setOnTapListener((hitTestResult, motionEvent1) -> {
                  if (motionEvent1.getActionMasked() == MotionEvent.ACTION_UP) {
                    node.getRenderable().getMaterial().setFloat4(MaterialFactory.MATERIAL_COLOR, new Color((float) Math.random(),(float) Math.random(),(float) Math.random(), 1));
                  }
                });
              });
`

**Comment by dsternfeld7** [comment]
Tanks for the report! I this is a known bug that will be fixed in an upcoming release.

**Comment by dsternfeld7** [comment]
This is now fixed in Sceneform 1.4.
