### ISSUE TITLE
SFB baseColorTint set to grey instead of original colors

### ISSUE THREAD

**Issue by itanbp** [google-ar/sceneform-android-sdk#209]
Hi,
I download several models from Google Poly. Many of the objects look grey, instead of the original model colors.
For example, this [candy corn](https://poly.google.com/view/emLjPKTkMvN) looks in Android Studio's viewer grey:
![grey](https://i.imgur.com/nMkj95j.jpg)
But this is how the original model looks:
![original](https://i.imgur.com/kX5x2oy.jpg)

Important to mention that there are models that Sceneform plugin rendered correctly, for example this 
[licorice](https://poly.google.com/view/5cggNrGKKpo) model. 
More models that didn't render correctly: [cherry](https://poly.google.com/view/aJgYH6O01OM) and [gummy bear](https://poly.google.com/view/5zl16PPAItW)

Working with Sceneform plugin version 1.3.0 on Windows.

SFA code:
```
{
   materials: [
      {
         name: "DefaultMaterial",
         parameters: [
            {
               baseColor: null,
            },
            {
               baseColorTint: [
                  0.59999999999999998,
                  0.59999999999999998,
                  0.59999999999999998,
                  1,
               ],
            },
            {
               metallic: 0,
            },
            {
               roughness: 1,
            },
            {
               opacity: null,
            },
         ],
         source: "build/sceneform_sdk/default_materials/obj_material.sfm",
      },
   ],
   model: {
      attributes: [
         "Position",
         "TexCoord",
         "Orientation",
      ],
      collision: {},
      file: "sampledata/models/249_Candy_Corn.obj",
      name: "249_Candy_Corn",
      scale: 0.099334000000000006,
   },
   version: "0.51:1",
}
```

**Comment by gstanlo** [comment]
This looks like a bug. In the top of the obj file, you can see the lines:


```
g Candy_Corn
mtllib 249_Candy Corn.mtl
```

As a workaround, transpose those two lines so it reads 
```
mtllib 249_Candy Corn.mtl
g Candy_Corn
```

**Comment by itanbp** [comment]
@gstanlo thanks!

**Comment by dimov96** [comment]
@gstanlo  thank you for this post. I am currently facing the same problem but in my case the .obj file starts with these lines and still:

```
mtllib object_ga_25.mtl
o Barrel
v 0.793174 1.064640 -0.168964
...

```

Has anyone found solution to this problem?
