### ISSUE TITLE
Using sceneform just to render 3D models without AR fragment

### ISSUE THREAD

**Issue by atul109** [google-ar/sceneform-android-sdk#213]
To make app compatible for non-ARCore devices, is it possible to render 3D models, so that I can show them with camera preview in background in 3DOF sensor devices.

**Comment by SimonMarquis** [comment]
I think [SceneView](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/SceneView) is the UI widget you'll need to use instead of `ArSceneView`.

**Comment by romainguy** [comment]
That's correct, [SceneView](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/SceneView) is what you're looking for.

**Comment by shaileshiyer** [comment]
For those who are trying to get sceneview tot work without ar
https://medium.com/@harivigneshjayapalan/arcore-cupcakes-1-render-a-scene-without-ar-for-phones-without-arcore-27d61a43a130

**Comment by roshanpatel6040** [comment]
@romainguy  @SimonMarquis 
Can you tell me how we can scale / rotate model in Sceneview ?

**Comment by tigran-babajanyan** [comment]
@roshanpatel6040 did you find how to scale/rotate model in sceneview?
