### ISSUE TITLE
How to set ModelRenderable center (origin)?

### ISSUE THREAD

**Issue by itanbp** [google-ar/sceneform-android-sdk#216]
Hi,
When creating a [cube](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/rendering/ShapeFactory.html#makeCube(com.google.ar.sceneform.math.Vector3,%20com.google.ar.sceneform.math.Vector3,%20com.google.ar.sceneform.rendering.Material)) or a sphere, one can define the center of the geometry.

I'm wondering how can I set the origin of `ModelRenderable` created from `sfb`?
My intention is to rotate the model from the right-top corner for example.

Thanks!

**Comment by gstanlo** [comment]
Presently you can acquire the collision bounds of a model, and use that as an approximation for the center of its visual geometry. 

See: https://developers.google.com/ar/reference/java/com/google/ar/sceneform/collision/Box.html#getCenter()

Additionally, you will be able to specify the origin in the SFA file in an upcoming release.

**Comment by jwmcglynn** [comment]
Sceneform 1.4 is now available, and includes a way to set the origin on the `model.recenter` [SFA attribute](https://developers.google.com/ar/develop/java/sceneform/sfa#attributes).

This transformation is applied at build time, if you want to dynamically have a different origin at runtime you can wrap the model's `Node` in another `Node` with a local position set.  For example, here is how to modify HelloSceneform to make the Andy model have a different origin:

```java
// Create the transformable andy and add it to the anchor.
TransformableNode andy = new TransformableNode(arFragment.getTransformationSystem());
andy.setParent(anchorNode);

// Create an andyModel node and setLocalPosition to change the TransformationSystem's
// rotation origin.
Node andyModel = new Node();
andyModel.setParent(andy);
andyModel.setRenderable(andyRenderable);
andyModel.setLocalPosition(new Vector3(0.0f, 0.1f, 0.0f));
```

Give Sceneform 1.4 a try, and feel free to reopen or create a new issue if you are still having issues.
