### ISSUE TITLE
Sceneform for non-AR app?

### ISSUE THREAD

**Issue by rongguodong** [google-ar/sceneform-android-sdk#22]
My understanding is that Sceneform is a powerful render engine which is orthogonal to AR (kinds of Google's version of Apple's SceneKit?). So can I use it for non-AR app?

For example, if I am currently using Ogre for a 3D game. Is it possible to switch to Sceneform to enjoy its physical based rendering on phones that do not support ARCore?

**Comment by claywilkinson** [comment]
Thanks for the question @rongguodong.  Currently we're focused on AR applications, but we definitely interested in expanding it beyond AR.

**Comment by rongguodong** [comment]
Hope Sceneform can decouple with ARCore soon, so that I can enjoy it on phones not supporting ARCore for apps which do not need tracking ability.

**Comment by rongguodong** [comment]
Is there any workaround to use Sceneform on non-ARCore-compatible phones right now?

**Comment by iRYO400** [comment]
Hi! How is it going? Can we use for non AR purposes?
Thanks!

**Comment by claywilkinson** [comment]
Filament is currently the underlying rendering engine.  Sceneform adds to the rendering simplifying the interactions with ARCore when developing AR applications.  The other part that is added is management of 3D models, known as renderables.  You can use Sceneform without ARCore by using the [Sceneview](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/SceneView) class.

**Comment by iRYO400** [comment]
@rongguodong yeah, currently downloading it

@claywilkinson is this possible to use SceneView to render 3D models without ARCore installed on phone(currently it doesn't support HTC's flagships)?

**Comment by shaileshiyer** [comment]
So has anyone actually tried using sceneform without arcore.

**Comment by iRYO400** [comment]
@shaileshiyer yes. It works. But still has uncovered areas.
Check official documentation page.

**Comment by claywilkinson** [comment]
I am working on publishing an article about how to use Sceneform in non-AR mode.  You can take a peek at the project in my [Personal GitHub Project](https://github.com/claywilkinson/poly-sample-android/tree/master/PolySampleARCore).  I basically create a fragment to hold the SceneView view.

If you have specific issues it's probably best to open a new issue vs. commenting on this closed issue.  Broader questions are more appropriate for [Stackoverflow](https://stackoverflow.com/questions/tagged/sceneform)

**Comment by iRYO400** [comment]
> I am working on publishing an article about how to use Sceneform in non-AR mode. You can take a peek at the project in my [Personal GitHub Project](https://github.com/claywilkinson/poly-sample-android/tree/master/PolySampleARCore). I basically create a fragment to hold the SceneView view.
> 
> If you have specific issues it's probably best to open a new issue vs. commenting on this closed issue. Broader questions are more appropriate for [Stackoverflow](https://stackoverflow.com/questions/tagged/sceneform)

Thanks! Nice example with using Poly. 
Please can you check the latest issue I posted here #376

**Comment by jpsarda** [comment]
> I am working on publishing an article about how to use Sceneform in non-AR mode. You can take a peek at the project in my [Personal GitHub Project](https://github.com/claywilkinson/poly-sample-android/tree/master/PolySampleARCore). I basically create a fragment to hold the SceneView view.
> 

I haven't found this article, is it somewhere ? I've been looking into "PolySampleARCore" on your github. It's not completely clear for me : Can the app run on devices not supporting arcore ? Not sure how I'll do this, but my plan is to modify/simplify the app to test a simple .obj file rendering.
For my project I'll need to render the camera preview in background. It seems there's also a discussion about it here https://github.com/google-ar/sceneform-android-sdk/issues/274
