### ISSUE TITLE
Make Transparent Material

### ISSUE THREAD

**Issue by aayc** [google-ar/sceneform-android-sdk#223]
Hi,

I've been playing around with ARCore and was able to easily make an opaque red cube by doing the following:

```
ModelRenderable cube;
MaterialFactory.makeOpaqueWithColor(this, new Color(android.graphics.Color.RED))
            .thenAccept(material ->
                cube = ShapeFactory.makeCube(new Vector3(0.01f, 0.01f, 0.01f), new Vector3(0, 0, 0), material));
```

I figured that by changing the word "opaque" to "transparent" I should be able to get a transparent red cube with the following:
```
ModelRenderable cube;
MaterialFactory.makeTransparentWithColor(this, new Color(android.graphics.Color.RED))
            .thenAccept(material ->
                cube = ShapeFactory.makeCube(new Vector3(0.01f, 0.01f, 0.01f), new Vector3(0, 0, 0), material));
```
However executing that code just gives me an opaque cube.  I was hoping to have a transparent cube that I could see through (such that if I placed the cube on a table and looked at it, I would see the table's surface underneath it).  What am I doing wrong?

Thanks for your help!

**Comment by gstanlo** [comment]
Try something like `new Color(1, 0, 0, 0.5)` for the color. android.graphics.Color.RED is going to be an opaque, solid red. The transparent material means that it allows for colors with an alpha channel, but if you give it an opaque color it will mostly look opaque still.

**Comment by aayc** [comment]
Hooray!  It works.  Thanks again!
