### ISSUE TITLE
[Question] How to draw a line similar to JustALine?

### ISSUE THREAD

**Issue by dakshsrivastava** [google-ar/sceneform-android-sdk#232]
Hey. 
I've been trying to build something similar to [JustALine](https://justaline.withgoogle.com/) using Sceneform. I'm able to augment multiple `ViewRenderable`s mid air by anchoring the first camera `Pose` and adding every newly added object relative to the first object. I'm placing multiple 2D circles at this point. How do I draw a smooth line using SceneForm how JustALine does it probably using standard ARCore library?

**Comment by gstanlo** [comment]
You can possibly use a [ModelRenderable.Builder](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/rendering/ModelRenderable.Builder) to procedurally create a line.

**Comment by dakshsrivastava** [comment]
An example would be very helpful @gstanlo.

**Comment by malik-at-work** [comment]
@dakshsrivastava  There is a sample posted which creates geometry dynamically to draw a line. You can download the sample repository from https://github.com/googlesamples/sceneform-samples and try the drawing app.

The sample code you are looking for is at https://github.com/googlesamples/sceneform-samples/blob/master/drawing/app/src/main/java/com/google/ar/sceneform/samples/drawing/ExtrudedCylinder.java which creates a cylinder shaped segments and joins them along list of points.

**Comment by dakshsrivastava** [comment]
Thanks for the links @malik-at-work. I see the implementation is minutely different from what I was doing to place the objects. I was using the camera pose directly whereas the example uses a Ray. As for the drawing, heck! Just the thing I was looking for. Thanks a ton!

**Comment by khurramengr** [comment]
@malik-at-work is there any way we could draw this line over some object rather than in the air and make that drawing stick to that object by attaching it to some anchor?
Something like [this](https://vivar.me/).
I've been looking for the solution for a long time, any help in this regard would be highly appreciated.

**Comment by dpproduction** [comment]
Drawing sample shows how to draw 3d line as cilynder. 
But how to draw 2d line like in JustALine app using Sceneform?
I see JustALine source but there is opengl rendering and it's not compatible with Sceneform.
