### ISSUE TITLE
Create Texture from OpenGL texture

### ISSUE THREAD

**Issue by evodabas** [google-ar/sceneform-android-sdk#237]
Following up on this issue: https://github.com/google-ar/sceneform-android-sdk/issues/81#event-1768673219 I'd like to propose a feature to allow somehow populating a SceneForm texture from a native OpenGL texture handle. The specific use case here would be to texture geometry in a SceneForm scene with a video texture (such as from video rendered onto a SurfaceTexture). 

Any means of supporting this would be a fine I think: constructing a Texture from a user-defined GL texture id, or Texture being able to provide a GL id that the user is able to do their own copy to, etc.

**Comment by dsternfeld7** [comment]
In Sceneform 1.4 we did release an api for ExternalTexture's, there is an example [here](https://github.com/google-ar/sceneform-android-sdk/tree/master/chromakeyvideo) showing how to use it to play chroma keyed videos. It doesn't allow you to pass in an arbitrary texture id though, instead it provides a SurfaceTexture for you to render onto.

**Comment by evodabas** [comment]
Oh interesting, that might be all we need then. Feel free to close this issue then, thanks!
