### ISSUE TITLE
rotate a node 

### ISSUE THREAD

**Issue by basitsaleemmb** [google-ar/sceneform-android-sdk#238]
@inio @richlowenberg @jwmcglynn 
how can i rotate a node to x or y-axis in scene view.

**Comment by dakshsrivastava** [comment]
Use a `TransformableNode`. It supports basic transformations OTB. You can read about it [here](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/ux/TransformableNode).

**Comment by aayc** [comment]
Here's an example:
```
Pose p = new Pose(new float[] {0, 0, 0, 0}, new float[] {0, 0, 0, 0});
AnchorNode anchorNode = new AnchorNode(sceneView.getSession().createAnchor(p));
anchorNode.setParent(sceneView.getScene());
TransformableNode node = new TransformableNode(arFragment.getTransformationSystem());
// Uses z axis and 180 degrees to return new quaternion
node.setLocalRotation(Quaternion.axisAngle(new Vector3(0, 0, 1f), 180));
node.setParent(anchorNode);
node.setRenderable(modelrenderable);
```

**Comment by basitsaleemmb** [comment]
Thankyou @aayc 
i m not using arFragment, i m using arsceneView so how can i create transformable node from arSceneView  or you can proivde any other  alternative.

**Comment by aayc** [comment]
No problem.

As far as I know,a  TransformableNode requires a transformation system, and the AR Fragment can supply it.  Are you sure you don't have access to your AR fragment, for example are you using rendering the scene without AR?

If you're using AR then I think it's likely you're also using an AR fragment somewhere...let me know and I'll try to help!

**Comment by basitsaleemmb** [comment]
@aayc  i am rendering scene with arSceneView. 
here you go [](https://github.com/appoly/ARCore-Location). I referred this library to place my modelrenderable at some lat/lng. now i want to rotate my model. that's it.

**Comment by basitsaleemmb** [comment]
@aayc @inio 
i don't want to see hand moving in scene. how can i remove it from scene

**Comment by aayc** [comment]
I don't know much about using sceneform without an AR fragment; this is the code I used to disable the hand moving:

```
arFragment.getPlaneDiscoveryController().hide();
arFragment.getPlaneDiscoveryController().setInstructionView(null);
```
[also this issue on the hand motion](https://github.com/google-ar/sceneform-android-sdk/issues/68)

As far as the rotation goes, I'm not sure how to do that without using the AR Fragment..

**Comment by basitsaleemmb** [comment]
thanku @aayc 
ok i solved it closing it by now! :)

**Comment by claywilkinson** [comment]
This looks like a missing dependency for ArFragment.  Can you add 
`    implementation "com.android.support:appcompat-v7:27.1.1"`
to your project?

[requireActivity()](https://developer.android.com/topic/libraries/support-library/revisions#new-apis_3) was added in 27.1.0

**Comment by malik-at-work** [comment]
We resolved this @basitsaleemmb's app crashing issue in https://github.com/google-ar/sceneform-android-sdk/issues/248

**Comment by MuhammadAasharib** [comment]
> @aayc , @inio, @dakshsrivastava i am rendering scene with arSceneView.
> here you go https://github.com/appoly/ARCore-Location.
> I referred this library to place my modelrenderable at some lat/lng. now i want to rotate my model. that's it.

@basitsaleemmb
Have you found any solution for rotating models while using Appolly/ArCore-Location? I am also stuck with the same problem. Can you help me please?

**Comment by basitsaleemmb** [comment]
@MuhammadAasharib  
to rotate a single  Model Renderable 
  arFragment.getArSceneView()
                .getScene()
                .setOnUpdateListener(
                        frameTime -> {
                            if (!hasFinishedLoading) {
                                return;
                            }

                            Frame frame = arFragment.getArSceneView().getArFrame();


                            if (frame == null) {
                                return;
                            }

                            if (frame.getCamera().getTrackingState() != TrackingState.TRACKING) {
                                return;
                            }

                            if (locationScene == null) {
                                // If our locationScene object hasn't been setup yet, this is a good time to do it
                                // We know that here, the AR components have been initiated.
                                locationScene = new LocationScene(this, this, arFragment);

                                // Now lets create our location markers.
                                // First, a layout
                                LocationMarker layoutLocationMarker = new LocationMarker(
                                        74.2510,
                                        31.4231,
                                        getExampleView()
                                );


                                // An example "onRender" event, called every frame
                                // Updates the layout with the markers distance
//                                layoutLocationMarker.setRenderEvent(new LocationNodeRender() {
//                                    @Override
//                                    public void render(LocationNode node) {
//                                        View eView = exampleLayoutRenderable.getView();
//                                        TextView distanceTextView = eView.findViewById(R.id.textView2);
//                                        distanceTextView.setText(node.getDistance() + "M");
//                                    }
//                                });
                                // Adding the marker
                                locationScene.mLocationMarkers.add(layoutLocationMarker);


//                                Pose p = new Pose(new float[] {10, 10, 10, 10}, new float[] {0, 0, 0, 1});
                                AnchorNode anchorNode = new AnchorNode(arFragment.getArSceneView().getSession().createAnchor(frame.getCamera().getPose()));
                                anchorNode.setParent(arFragment.getArSceneView().getScene());
                                node = new TransformableNode(arFragment.getTransformationSystem());

                                node.setParent(anchorNode);
                                node.select();
                                node.setLocalScale(new Vector3(0.3f, 0.3f, 0.3f));
//                                node.getRotationController().setRotationRateDegrees(90);


                                rotateableAndy.setParent(node);
                                rotateableAndy.setRenderable(andyRenderable);

                                // Adding a simple location marker of a 3D model
                                locationScene.mLocationMarkers.add(
                                        new LocationMarker(
                                                74.2510,
                                                31.4231,
                                                node));
                            }

                            if (rotateableAndy!=null) {
                                Quaternion rotation1 = Quaternion.axisAngle(new Vector3(0.0f, 3.0f, 0.0f), frameTime.getStartSeconds() * 100);
                                Quaternion rotation2 = Quaternion.axisAngle(new Vector3(0.0f, 3.0f, 0.0f), frameTime.getStartSeconds() * 100);
                                rotateableAndy.setLocalRotation(Quaternion.multiply(rotation1,rotation2));
                            }

                            if (locationScene != null) {
                                locationScene.processFrame(frame);
                            }

//                            if (loadingMessageSnackbar != null) {
//                                for (Plane plane : frame.getUpdatedTrackables(Plane.class)) {
//                                    if (plane.getTrackingState() == TrackingState.TRACKING) {
//                                        hideLoadingMessage();
//                                    }
//                                }
//                            }
                        });


        // Lastly request CAMERA & fine location permission which is required by ARCore-Location.
        ARLocationPermissionHelper.requestPermission(this);
    }

**Comment by basitsaleemmb** [comment]
@MuhammadAasharib 

`  arFragment.getArSceneView()
                .getScene()
                .setOnUpdateListener(
                        frameTime -> {
                            if (!hasFinishedLoading) {
                                return;
                            }

                            Frame frame = arFragment.getArSceneView().getArFrame();


                            if (frame == null) {
                                return;
                            }

                            if (frame.getCamera().getTrackingState() != TrackingState.TRACKING) {
                                return;
                            }

                            if (locationScene == null) {
                                // If our locationScene object hasn't been setup yet, this is a good time to do it
                                // We know that here, the AR components have been initiated.
                                locationScene = new LocationScene(this, this, arFragment);

                                // Now lets create our location markers.
                                // First, a layout
                                LocationMarker layoutLocationMarker = new LocationMarker(
                                        74.2510,
                                        31.4231,
                                        getExampleView()
                                );


                                // An example "onRender" event, called every frame
                                // Updates the layout with the markers distance
//                                layoutLocationMarker.setRenderEvent(new LocationNodeRender() {
//                                    @Override
//                                    public void render(LocationNode node) {
//                                        View eView = exampleLayoutRenderable.getView();
//                                        TextView distanceTextView = eView.findViewById(R.id.textView2);
//                                        distanceTextView.setText(node.getDistance() + "M");
//                                    }
//                                });
                                // Adding the marker
                                locationScene.mLocationMarkers.add(layoutLocationMarker);


//                                Pose p = new Pose(new float[] {10, 10, 10, 10}, new float[] {0, 0, 0, 1});
                                AnchorNode anchorNode = new AnchorNode(arFragment.getArSceneView().getSession().createAnchor(frame.getCamera().getPose()));
                                anchorNode.setParent(arFragment.getArSceneView().getScene());
                                node = new TransformableNode(arFragment.getTransformationSystem());

                                node.setParent(anchorNode);
                                node.select();
                                node.setLocalScale(new Vector3(0.3f, 0.3f, 0.3f));
//                                node.getRotationController().setRotationRateDegrees(90);


                                rotateableAndy.setParent(node);
                                rotateableAndy.setRenderable(andyRenderable);

                                // Adding a simple location marker of a 3D model
                                locationScene.mLocationMarkers.add(
                                        new LocationMarker(
                                                74.2510,
                                                31.4231,
                                                node));
                            }

                            if (rotateableAndy!=null) {
                                Quaternion rotation1 = Quaternion.axisAngle(new Vector3(0.0f, 3.0f, 0.0f), frameTime.getStartSeconds() * 100);
                                Quaternion rotation2 = Quaternion.axisAngle(new Vector3(0.0f, 3.0f, 0.0f), frameTime.getStartSeconds() * 100);
                                rotateableAndy.setLocalRotation(Quaternion.multiply(rotation1,rotation2));
                            }

                            if (locationScene != null) {
                                locationScene.processFrame(frame);
                            }

//                            if (loadingMessageSnackbar != null) {
//                                for (Plane plane : frame.getUpdatedTrackables(Plane.class)) {
//                                    if (plane.getTrackingState() == TrackingState.TRACKING) {
//                                        hideLoadingMessage();
//                                    }
//                                }
//                            }
                        });


        // Lastly request CAMERA & fine location permission which is required by ARCore-Location.
        ARLocationPermissionHelper.requestPermission(this);
    }`

**Comment by basitsaleemmb** [comment]
@MuhammadAasharib  put this code in your update lister to rotate 3D model

 
 Pose p = new Pose(new float[] {10, 10, 10, 10}, new float[] {0, 0, 0, 1});
                                AnchorNode anchorNode = new AnchorNode(arFragment.getArSceneView().getSession().createAnchor(frame.getCamera().getPose()));
                                anchorNode.setParent(arFragment.getArSceneView().getScene());
                                node = new TransformableNode(arFragment.getTransformationSystem());

                                node.setParent(anchorNode);
                                node.select();
                                node.setLocalScale(new Vector3(0.3f, 0.3f, 0.3f));
//                                node.getRotationController().setRotationRateDegrees(90);


                                rotateableAndy.setParent(node);
                                rotateableAndy.setRenderable(andyRenderable);

                                // Adding a simple location marker of a 3D model
                                locationScene.mLocationMarkers.add(
                                        new LocationMarker(
                                                74.2510,
                                                31.4231,
                                                node));
                            }

                            if (rotateableAndy!=null) {
                                Quaternion rotation1 = Quaternion.axisAngle(new Vector3(0.0f, 3.0f, 0.0f), frameTime.getStartSeconds() * 100);
                                Quaternion rotation2 = Quaternion.axisAngle(new Vector3(0.0f, 3.0f, 0.0f), frameTime.getStartSeconds() * 100);
                                rotateableAndy.setLocalRotation(Quaternion.multiply(rotation1,rotation2));
                            }

**Comment by basitsaleemmb** [comment]
@aayc @malik-at-work  @claywilkinson 
  can i add rotation to my list of model renderables (andyrenderable)

**Comment by ishaang10** [comment]
how can i rotate the same model using the gestures? i mean in a particular direction
