### ISSUE TITLE
TransformableNode does not translate on vertical planes

### ISSUE THREAD

**Issue by rubixhacker** [google-ar/sceneform-android-sdk#24]
When using vertical plane detection I am unable to translate a renderable using a TransformableNode, I am able to scale and rotate correctly.

**Comment by malik-at-work** [comment]
Thanks for the feedback. The Transformation System in Sceneform 1.0 was really designed for horizontal planes.  For future releases we will look into this and there are probably many other things in the Transformation System that we will want to change for vertical planes.

**Comment by malik-at-work** [comment]
Just updating this issue.  We have put this feature into an upcoming release.

**Comment by malik-at-work** [comment]
Fixed in Sceneform 1.3
