### ISSUE TITLE
release log mistake

### ISSUE THREAD

**Issue by morevar** [google-ar/sceneform-android-sdk#243]
release logs for [Sceneform SDK for Android v1.4.0](https://github.com/google-ar/sceneform-android-sdk/releases)

-  New APIs and capabilities

   - Added API **Scene.setOnPeekTouchListener** making it possible to connect multiple peek touch listeners to the scene.
     - it should be **Added API Scene.addOnPeekTouchListener** here

**Comment by claywilkinson** [comment]
Thanks for pointing that out!
