### ISSUE TITLE
SceneForm Camera and ARCore camera

### ISSUE THREAD

**Issue by Alpkant** [google-ar/sceneform-android-sdk#244]
I was trying to convert a world point to screen pixels and i saw that [this ](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/Camera.html#worldToScreenPoint(com.google.ar.sceneform.math.Vector3)) function is just what i need. But i tried to use this and saw that arcore.Camera and sceneform.Camera are two different classes and i couldn't figured it how to access sceneform.Camera . Can you help me about this or give a clue to how to use this function? Thank you!

**Comment by dsternfeld7** [comment]
You can access the sceneform camera by doing arFragment.getArSceneView().getScene().getCamera().

**Comment by Alpkant** [comment]
Thank you this solved my problem. However it was hard  to find from the documentation, probably it was my fault.
