### ISSUE TITLE
Plane Rendering similar to HelloAR sample in sceneform

### ISSUE THREAD

**Issue by Alpkant** [google-ar/sceneform-android-sdk#245]
Hi i was trying to cover the whole surface of the detected plane with a texture. Using OpenGl enables me do this like this [screenshot ](https://prntscr.com/kghjm6) . However i want to switch to Sceneform and i only could get something like [this](https://prntscr.com/kghk6g) by following other questions in the Github.
These are the codes that i used currently for texture rendering. To conclude, i do not want this spotlight texture on the plane. I want to cover whole detected plane like my first screenshot. Thank you! 

     Texture.Sampler sampler =
                Texture.Sampler.builder()
                        .setMagFilter(Texture.Sampler.MagFilter.LINEAR)
                        .setMinFilter(Texture.Sampler.MinFilter.LINEAR)
                        .setWrapMode(Texture.Sampler.WrapMode.REPEAT)
                        .build();

        CompletableFuture<Texture> trigrid = Texture.builder()
                .setSource(this, R.drawable.gray)
                .setSampler(sampler).build();

        PlaneRenderer planeRenderer = arSceneView.getPlaneRenderer();
        planeRenderer.getMaterial().thenAcceptBoth(trigrid, (material, texture) -> {
            material.setTexture(PlaneRenderer.MATERIAL_TEXTURE, texture);
        });`

**Comment by dsternfeld7** [comment]
What is your use case for doing this? Outside of debugging, rendering the entire plane is typically something that we discourage for UX purposes.

I haven't tested this, but I believe you could achieve this by doing this:

```
    PlaneRenderer planeRenderer = arFragment.getArSceneView().getPlaneRenderer();
    Material planeMaterial = planeRenderer.getMaterial().join();
    if (planeMaterial != null) {
      planeMaterial.setFloat(PlaneRenderer.MATERIAL_SPOTLIGHT_RADIUS, Float.MAX_VALUE);
    }
```

Make sure to put this block of code in the body of an onUpdate function, otherwise the spotlight radius value will get overridden.

**Comment by Alpkant** [comment]
I am trying to make an app that takes photos of the plane and plane renderer used as feedback mechanism. To illustrate, user detects plane and took photos of that plane part by part and every part colored after photo is taken.So i need something like int my first screenshot. I tried  your code but it still getting a spotlight effect when plane is big.
