### ISSUE TITLE
SceneView - Screenshot using PixelCopy image issue

### ISSUE THREAD

**Issue by morevar** [google-ar/sceneform-android-sdk#257]
I captured a screenshot with PixelCopy and saved it as a Bitmap, but **the bitmap has some black dots**.

![pic_20180815115354](https://user-images.githubusercontent.com/14886798/44131036-f3820f22-a082-11e8-9014-61287bf95aba.png)

Is there any way to avoid that? or any better way to capture a better screenshot?

**Comment by romainguy** [comment]
Pixelcopy just does a straight copy of the framebuffer, it should reflect what's on screen. Could you take a screenshot with ADB or Android studio at the same time so we can compare the content?

**Comment by morevar** [comment]
Yes, you are right.
The screenshot with Pixelcopy does reflect what's on screen, but when ARCore is running, i dont see any black dots on screen, however the screenshot has black dots.
I run the test on Samsung Galaxy S8, Android 7.0.
![003](https://user-images.githubusercontent.com/14886798/44387720-da1f7580-a558-11e8-851f-5a4c67fc3bab.png)

**Comment by khonakr** [comment]
+1 Even I am getting the same black artifacts.

**Comment by malik-at-work** [comment]
Please retest this in Sceneform 1.5.  We haven't seen this issue, but did find some and fix similar issues.

**Comment by claywilkinson** [comment]
Please reopen this issue if it is still happening with the latest version of Sceneform.
