### ISSUE TITLE
Rendering models issues

### ISSUE THREAD

**Issue by itanbp** [google-ar/sceneform-android-sdk#26]
Hi,
I tried to render several assets from the Poly project. While many of the assets were displayed correctly, other failed to display.

1. Obj file with implicit face normals - In this [submarine](https://poly.google.com/view/8PgPdFGg3MO) object, the vertex normal indices are implicit.
We can see it when looking at the "faces" lines, for example: `f 40/91 41/90 37/89 36/88`.
**the issue:** the model's faces seems curved, instead of the polygon-style look.

![curves](https://github.com/itanbp/android-ble-peripheral-central/blob/master/screenshots/Screenshot_20180515-1521351_LI.jpg?raw=true)
![no curves](https://github.com/itanbp/android-ble-peripheral-central/blob/master/screenshots/submarine_polygon_LI.jpg?raw=true)

2. obj file + mtl file, without png texture file. When trying to anchor this two files, nothing happened - the virtual object wasn't added to the scene graph. The assets are a [tablet](https://poly.google.com/view/dTjviKNzecd) and a [laptop](https://poly.google.com/view/4UuDHXFJ7I0). Just to mention that other obj + mtl assets were successfully displayed, a [cup](https://poly.google.com/view/a22X3YocUp-) for example.

3. this [cup](https://poly.google.com/view/a22X3YocUp-) rendering looks good, but the rotation of the cup is wrong, it's laying instead of standing. In the [poly](https://poly.google.com/view/a22X3YocUp-) page the rotation looks right.

I will be happy the know if the above are known issues? maybe a wrong configuration in the `.sfa` files?
Thanks!

**Comment by AdrianAtGoogle** [comment]
Hi @itanbp, thank you for reporting these issues.

* Issue 1 will be addressable in an upcoming release: we will provide model configuration to specify a limit angle which determines when hard edges are automatically softened when processing geometry with implicit normals.  Currently this is hard-coded to 45 degrees.
* Issue 2 needs more investigation; will update this bug when I have more information
* Issue 3 will be addressable in an upcoming release as well, via model properties in the `sfa` which can apply axis remapping to the source asset

**Comment by tpsiaki** [comment]
For issues 1 and 2 here, we recommend that you now use the glTF option for downloading/importing from Poly.  If you use the glTF import then both of those issues should be resolved.

For Issue 3 with the current asset import support, you have to rotate the cup in the runtime by applying a rotation to the node when it is created.  Someday we may have a way of remapping the axes, but that work is not currently planned.
