### ISSUE TITLE
sceneform 1.4.0 does not run in emulator OpenGL ES 3.0, re issue #220

### ISSUE THREAD

**Issue by Berenice2018** [google-ar/sceneform-android-sdk#260]
Hello,

I refer to the issue #220 
I followed the instructions https://developers.google.com/ar/develop/java/emulator
In my ARCore project, I use:
```
implementation 'com.google.ar:core:1.4.0'
    implementation 'com.google.ar.sceneform:core:1.4.0'
    implementation 'com.google.ar.sceneform.ux:sceneform-ux:1.4.0'
```

The logcat shows the OpenGL version  3 0 (see the following screenshot) 
<img width="945" alt="bildschirmfoto 2018-08-16 um 11 13 27" src="https://user-images.githubusercontent.com/35174799/44200162-3859ec00-a146-11e8-9939-cffb88bd35ef.png">

While running my app in the emulator, the AR activity will not start: (screenshot)
<img width="304" alt="bildschirmfoto 2018-08-16 um 11 14 21" src="https://user-images.githubusercontent.com/35174799/44200308-92f34800-a146-11e8-9487-af9d8421d6a0.png">

I am on MacOS 10.13.5 (High Sierra)

Is there anything I can do here? 
My project is for an examination. I may not submit it without getting running in the emulator. The deadline is this week, it would be great, if I could fix it in time.

**Comment by jwmcglynn** [comment]
Hey @Berenice2018, the code that displays the "Sceneform requires OpenGL ES 3.1 or later" dialog is actually part of the sample code.  You should be able to modify your app to change that to OpenGL ES 3.0 or remove that check entirely.

Here is where the check is implemented in hellosceneform: https://github.com/google-ar/sceneform-android-sdk/blob/master/hellosceneform/app/src/main/java/com/google/ar/sceneform/samples/hellosceneform/HelloSceneformActivity.java#L114

**Comment by Berenice2018** [comment]
OMG! I got it. Thanks for your hint, @jwmcglynn ! 
I will close this thread.
