### ISSUE TITLE
Is there a way to use CloudAnchors with Sceneform?

### ISSUE THREAD

**Issue by vicmns** [google-ar/sceneform-android-sdk#264]
Just as the title says, I'm trying to build up a quick demo just to see if our idea it's possible; but one of the features needs CloudAnchors. The thing is that I don't want to spent time implementing all the rendering logic using OpenGL instructions (which it's the only way I found using ArCore), when Sceneform makes it so easily :stuck_out_tongue_closed_eyes:

**Comment by claywilkinson** [comment]
Yes, you can use all ARCore features with Sceneform, and it is much easier (in my opinion) than OpenGL for most things you'll want to render.

We're working on getting the Sceneform version of the sample published in the official site, but in the meantime, feel free to clone it from my personal fork:  https://github.com/claywilkinson/arcore-android-sdk/tree/sceneform-samples/samples/cloud_anchor_java

**Comment by vicmns** [comment]
Brilliant you're a life saver! I was looking at the code and found the way to do it. But with this project I can start right away :+1:

**Comment by claywilkinson** [comment]
Good luck with your app!
