### ISSUE TITLE
Sceneform available ABIs

### ISSUE THREAD

**Issue by itanbp** [google-ar/sceneform-android-sdk#266]
In the `build.gradle` documentation it is mentioned that `Sceneform is available for the following ABIs: arm64-v8a, armv7a, x86_64 and x86`.

I'm am creating an app that works only with sceneform SDK, without any Arcore calls. I'm trying to increase the number of devices that can run the app, so I added to the `abiFilters` (inside the build.gradle) also `armeabi-v7a` - and it worked! The app was successfully running on a device that supports none of `arm64-v8a, armv7a, x86_64 and x86`, but does support `armeabi-v7a`.

Is this a documentation mistake?

**Comment by claywilkinson** [comment]
I think this is a typo in the comment.  `armv7a` == `armeabi-v7a`

I'll update the comment in the next release.
