### ISSUE TITLE
How to remove pinch (scale) listener from TransformableNode?

### ISSUE THREAD

**Issue by dementia2029** [google-ar/sceneform-android-sdk#268]
The question above

**Comment by dementia2029** [comment]
Sorry, i close the question. Simply extend BaseTransformableNode and do not add ScaleController.

**Comment by Jhonnybsg** [comment]
You can also do the following:

TransformableNode tansformableNode = new TransformableNode(arFragment.getTransformationSystem());
tansformableNode.getScaleController().setSensitivity(0);

**Comment by karntrehan** [comment]
Or transformableNode.scaleController.isEnabled = false
