### ISSUE TITLE
Error when creating custom Unlit material

### ISSUE THREAD

**Issue by itanbp** [google-ar/sceneform-android-sdk#269]
Hi,
I'm trying to create an `Unlit model`, following this [post](https://github.com/google-ar/sceneform-android-sdk/issues/222).
When importing the obj file I'm getting the error `Jsonnet Error: [1]: RUNTIME ERROR: Field does not exist: parameters `.

I created a `*.mat` file, with the content:
```
material {
    name : "Custom material",
    shadingModel : unlit
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor = vec4(0.0);
    }
}
```

After clicking "Import Sceneform Asset", in the "Import Wizard" I select the path of the custom material, and then I receive the error.

**Comment by claywilkinson** [comment]
You need to have at least one Parameter defined, I am marking it a bug.  In the material element add
```
parameters : [
        {
           type : float,
           name : unused
        }
```

**Comment by itanbp** [comment]
@claywilkinson that indeed solved the error, but now the model color is black, instead of the model's original colors.
I'm following @romainguy suggestion in my previous question [Setting environment lighting](https://github.com/google-ar/sceneform-android-sdk/issues/222)

the `*.mat` file:
```
material {
    name : "Custom material",
    shadingModel : unlit,
    parameters : [
        {
           type : float4,
           name : baseColor
        }, 
	 {
           type : float4,
           name : emissive
        }

    ]
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor = vec4(0.0);
    }
}
```

**Comment by romainguy** [comment]
Your material sets a black color:

```
material.baseColor = vec4(0.0);
```

It should probably be:

```
material.baseColor = materialParams.baseColor;
```

**Comment by itanbp** [comment]
@claywilkinson @romainguy it worked!
I still needed to manually set the `baseColor` values in the `sfa` file, as they were all zero by default, I assume it isn't the expected behavior?
Appreciate your help!

**Comment by claywilkinson** [comment]
Yes, that is expected.
