### ISSUE TITLE
Unwrap, NormalMap and Texture issue while importing FBX into scenform

### ISSUE THREAD

**Issue by jagsrajput21** [google-ar/sceneform-android-sdk#27]
I think Sceneform is generating UV channel by itself. It's damaging unwrapping for FBX created with MAX. Existing UV channel should remain same as we have done in 3ds Max. How to disable generating UV unwrap Channel? It is misbehaving with Textures on the model. 
![screen shot 2018-05-16 at 12 20 11 pm](https://user-images.githubusercontent.com/6915256/40100970-86be4d36-5903-11e8-8088-280f4f892bc9.png)

The correct model looks like - 
![correct_texture](https://user-images.githubusercontent.com/6915256/40101020-adc7def6-5903-11e8-86f6-4d3d8049c2f9.JPG)

Please suggest if we are doing anything wrong.

**Comment by AdrianAtGoogle** [comment]
Hi jagsrajput21, thank you for reporting this issue.  Sceneform doesn't generate UV's, but you're correct that they're not making it over from the `.fbx` file correctly.

Can you try adding the following line to the `model` block of your `.sfa`?
`   flip_texture_coordinates: true,`

**Comment by jagsrajput21** [comment]
I have tried it. Still not working.

<img width="1285" alt="screen shot 2018-05-18 at 10 31 12 am" src="https://user-images.githubusercontent.com/6915256/40216834-e36355de-5a86-11e8-9084-c5c9574e6636.png">

**Comment by jagsrajput21** [comment]
@AdrianAtGoogle Can you please help me regarding this?

**Comment by AdrianAtGoogle** [comment]
Hi jagsrajput21, this is definitely a bug; `flip_texture_coordinates: true` does not work with FBX models.  We will fix this in the next release; sorry about the hassle.

**Comment by jagsrajput21** [comment]
Ok, Thanks @AdrianAtGoogle

**Comment by rramprasad** [comment]
@AdrianAtGoogle issue #37 also related to this issue?

**Comment by AdrianAtGoogle** [comment]
@rramprasad issue #37 isn't affected by this issue; flip_texture_coordinates works on `.obj` and `.gltf` source files in 1.0.1; it will work for `.fbx` files in 1.0.3.

**Comment by ToadPrincess** [comment]
I have the same problem.

right:
![001](https://user-images.githubusercontent.com/20888254/41340821-d901704a-6f2a-11e8-9055-141ceb78e176.png)
After using sceneform:
![002](https://user-images.githubusercontent.com/20888254/41340826-dd063cb6-6f2a-11e8-81cd-3913e67329a4.png)

**Comment by AdrianAtGoogle** [comment]
This issue with FBX UV's is fixed in 1.4 - thank you for reporting the issue
