### ISSUE TITLE
How to get width and height of particular object using sceneform SDK?

### ISSUE THREAD

**Issue by mistrydarshan99** [google-ar/sceneform-android-sdk#271]
Hi,

I have to measure particular 3D object height and width. Is it possible to measure width and height using scene form SDK?

In ios ARKit measuring the height and width of 3D object is possible so how to achieve in android arcore.

**Comment by dementia2029** [comment]
Box box = (Box) modelNode.getRenderable().getCollisionShape();
Vector3 vector3 = box.getSize();

**Comment by mistrydarshan99** [comment]
@dementia2029 I want to get width and height of a live object such as water bottle, a notebook, keyboard, etc.. so my question is how to get width and height of a live object. 

Using the above code I will get of renderable 3D object width and height, not a real-time object such as water bottle, a notebook.

**Comment by claywilkinson** [comment]
This type of question is better suited for [StackOverflow](https://stackoverflow.com/questions/tagged/arcore) once you have a some code written and are running into a roadblock.

Measure uses taps to perform a hittest for the points, skipping the computer vision part.  If you have 2 anchors you can subtract the position of one from the other to get the size in meters.

Sceneform is a rendering library for drawing 3D objects from models and interacting with them.  Object detection would be part of ARCore.

Object detection is not currently a feature of ARCore, so you might want to create a feature request in the [ARCore for Android SDK GitHub Project](https://github.com/google-ar/arcore-android-sdk/issues) to start the discussion of what types of objects you are looking to identify.

As a start you might want to explore the computer vision sample from ARCore which has a simple edge detector filter which you could use to find the edges of objects in the camera image.  From there, you'd need to do hit tests to find oriented points near the edge of your object.  The hittest will map the 2D coordinate into 3D space.  From there you can use arithmetic to calculate the dimensions.  The coordinate system in world space uses meters as the units.

Please feel free to posts specific issues about Sceneform API usage here as you encounter them.

Good luck with your app!
