### ISSUE TITLE
How to draw all surface of detected plane? 

### ISSUE THREAD

**Issue by dementia2029** [google-ar/sceneform-android-sdk#272]
How to draw all surface of detected plane (dots), not only a small part. I.e. i want to draw the dots everywhere where plane detected. Or maybe i can adjust a radius for drawing plane area?

**Comment by dementia2029** [comment]
It seems it is a bug, because if we look in update method of PlaneRenderer.java, we can see the hardcoded line:
`seeplaneMaterial.setFloat("radius", 0.5F)`
so if we set radius via
`material.setFloat(PlaneRenderer.MATERIAL_SPOTLIGHT_RADIUS, 10f);`
it will not change anything, because the variable
`private static final float SPOTLIGHT_RADIUS `
is never used.

**Comment by dementia2029** [comment]
Anyone?

**Comment by dementia2029** [comment]
The fix is here:
```
fragment.onUpdate(frameTime);
PlaneRenderer planeRenderer = fragment.getArSceneView().getPlaneRenderer();
planeRenderer.getMaterial().thenAccept(material -> {
   material.setFloat(PlaneRenderer.MATERIAL_SPOTLIGHT_RADIUS, 100f);
});
```

**Comment by cantor1616** [comment]
@dementia2029 can you explain how you solved this? I am trying to implement the fix you posted 28 days ago but am getting "Cannot resolve symbol 'frameTime'". I placed it in onCreate, is this the correct location?
![image](https://user-images.githubusercontent.com/43049401/45846804-dff2ad00-bcf6-11e8-8d63-44fdd67d97ee.png)

from onUpdate:
![image](https://user-images.githubusercontent.com/43049401/45846844-fbf64e80-bcf6-11e8-983d-1c38f9398d52.png)

from frameTime:
![image](https://user-images.githubusercontent.com/43049401/45846873-15979600-bcf7-11e8-8a6f-ff19d6dc63a8.png)

**Comment by dementia2029** [comment]
@cantor1616 
```
 fragment.getArSceneView().getScene().addOnUpdateListener(frameTime -> {
                fragment.onUpdate(frameTime);
                PlaneRenderer planeRenderer = fragment.getArSceneView().getPlaneRenderer();
                planeRenderer.getMaterial().thenAccept(material -> {
                    material.setFloat(PlaneRenderer.MATERIAL_SPOTLIGHT_RADIUS, 100f);
                });
}
```
