### ISSUE TITLE
Custom material for ViewRenderable

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/sceneform-android-sdk#280]
Any possibility we can get shaders for ViewRenderables?

Current requirement is fading out the edges of Images displayed inside a ViewPager.

**Comment by dsternfeld7** [comment]
It should be possible to do this right now actually, though it isn't a documented feature.

Make a .obj file for a 1x1 quad. The origin of the quad should be the bottom center.

Make your .mat file for the ViewRenderable. It needs to include a parameter of type "samplerExternal" named "viewTexture". 

An example of what a basic material would look like for a View Renderable is this:

```
material {
    "name" : "View",
    "defines" : [
        "baseColor"
    ],
    "parameters" : [
        {
           "type" : "samplerExternal",
           "name" : "viewTexture"
        }
    ],
    "requires" : [
        "position",
        "uv0"
    ],
    "shadingModel" : "unlit",
    "blending" : "transparent",
    "doubleSided" : true
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);

        vec2 uv = getUV0();

        if (!gl_FrontFacing) {
          uv.x = 1.0 - uv.x;
        }

        material.baseColor = texture(materialParams_viewTexture, uv);
        material.baseColor.rgb = inverseTonemapSRGB(material.baseColor.rgb);
    }
}
```

Then, generate a .sfb with the .obj and the .mat file. When you create your ViewRenderable, use ViewRenderable.builder().setSource to set the ViewRenderable to use the .sfb you passed in.

It's possible to use meshes other than a quad. However, ViewSizers, ViewRenderable alignment, and touch propagation to ViewRenderable's will not work correctly if you do that.

**Comment by michaelvogt** [comment]
@dsternfeld7 
Wow, thank you very much for your quick and detailed response. 
Works as expected. Awesome 👍

**Comment by darek607** [comment]
@dsternfeld7 
What do you mean by " The origin of the quad should be the bottom center"? Could you show quad definition?

I have something like this, but the view is not showing:
`v -0.5 0.0 0.0
v 0.5 0.0 0.0
v 0.5 1.0 0.0
v -0.5 1.0 0.0
f 1 2 3 4`

**Comment by darek607** [comment]
If someone looked for the obj file:
```
o Plane
v -0.500000 0.000000 0.000000
v 0.500000 0.000000 0.000000
v -0.500000 1.000000 0.000000
v 0.500000 1.000000 0.000000
vt 0.0000 0.0000
vt 1.0000 0.0000
vt 1.0000 1.0000
vt 0.0000 1.0000
vn 0.0000 0.0000 1.0000
s off
f 1/1/1 2/2/1 4/3/1 3/4/1

```
(with a new line at the bottom!)
