### ISSUE TITLE
WebView as ViewRenderable

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/sceneform-android-sdk#282]
I just tried to use a WebView as a View for a ViewRenderable, but see some strange behaviour. Before spending time looking for the causes, I'd like to ask if this should actually work.

Reason for using WebView: I think the Android text system is lacking big time, especially that it isn't able to display top to bottom text (chinese / japanese). As this is easy to do with HTML, having a WebView available would be very helpful for me.

**Comment by michaelvogt** [comment]
Would like to extend this question with the com.google.vr.sdk.widgets.pano.VrPanoramaView. That would allow tourists to see the interior of a building even outside of the opening hours.

**Comment by romainguy** [comment]
`WebView` is quite a special type of `View` and doesn't work through `ViewRenderable` currently. Other views based on `SurfaceView` won't work either.

**Comment by michaelvogt** [comment]
Any chance to have these Views available at some time in the future, or is this out of reach?

**Comment by romainguy** [comment]
It might be possible with virtual displays but I wouldn't put too much hope on this. Also note that a `WebView` is an expensive view and re-routing it through a virtual display/surface texture for display in AR is also quite expensive. If you don't need interactive text I would recommend rendering your text into a `Bitmap` and using that bitmap as a texture in AR (you can make a `WebView` render into a `Bitmap`'s `Canvas` for instance).

**Comment by michaelvogt** [comment]
Ok, thanks a lot
