### ISSUE TITLE
Soft shadows

### ISSUE THREAD

**Issue by c0deminded** [google-ar/sceneform-android-sdk#283]
Hello, I'm looking for a way to make objects cast soft shadows.
The light is projected from the top down, so shadows look too hard.
I added unlit plane under my objects to recieve shadows as shown [here](https://developers.google.com/ar/develop/java/sceneform/custom-material#material_block)
How can I create one more pass to make them look blurry or is there some light options to reach this?

**Comment by romainguy** [comment]
The shadows are already softened through filtering, there's no extra support to make them appear blurry. The best thing to do for ambient shadows at the moment is to use baked textures (which works for the ground plane only).

**Comment by hshapley** [comment]
@romainguy Can you explain more? How would I make soft shadows for the "ground plane" in a SceneView without ARCore?

ARKit and Apple's QuickLook have had soft shadows for a long time.
