### ISSUE TITLE
Layering problem

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/sceneform-android-sdk#285]
When I create a plane, based on a ShapeFactory cube, and want to place other objects on top of it, I see lots of problems in regards of layering, where objects that are placed behind other objects suddenly cover objects in front of them. This happens based on the rotation of the phone.

Here is the effect in action:
https://photos.app.goo.gl/DA7gt1QZZMjLgQXf8

The code looks like this:
`          Texture.builder()
              .setSource(getApplicationContext(), R.drawable.boardbackground)
              .build()
              .thenAccept(backtexture ->
                  MaterialFactory.makeTransparentWithTexture(getApplicationContext(), backtexture)
                      .thenAccept(backmaterial -> {
                        ModelRenderable backrenderable = ShapeFactory.makeCube(new Vector3(1f, 0.01f, 1f), Vector3.zero(), backmaterial);

                        Node background = new Node();
                        background.setLocalPosition(Vector3.up());
                        background.setParent(anchorNode);
                        background.setRenderable(backrenderable);

                        Texture.builder()
                            .setSource(getApplicationContext(), R.drawable.img_20180609_115300)
                            .build()
                            .thenAccept(texture ->
                                MaterialFactory.makeTransparentWithTexture(getApplicationContext(), texture)
                                    .thenAccept(material -> {
                                      ModelRenderable renderable = ShapeFactory.makeCube(new Vector3(0.5f, 0.01f, 0.5f), Vector3.zero(), material);

                                      Node foreground = new Node();
(x)                                      foreground.setLocalPosition(new Vector3(0.2f, 0.1f, 0f));
                                      foreground.setParent(background);
                                      foreground.setRenderable(renderable);
                                    })
                            );

                      })
              );
`
(x) This effect is for example triggered, when a value other than 0 for x or z is entered here. Keeping these values to 0 'fixes' this problem. The problem shows up when the top layer is a child of the `anchorNode` or `background`.

Any idea why this happens?

**Comment by michaelvogt** [comment]
Any comment on this one? Am I doing something wrong, can you replicate it? Need to get rid of this problem quickly.

**Comment by michaelvogt** [comment]
@romainguy 
Yes, in the app there are 2 overlapping objects - an image in the background and a text partially covering it. I want the image to fade out below the text, and the text to be visible behind the text.

@malik-at-work 
Thank you for your explanation. 

So, what you are saying is, that the order in the scene graph isn't enough to ensure the correct object is drawn above? 

I'll play around with the render priority and let you know how it turns out.

**Comment by romainguy** [comment]
The order in the scene graph is usually enough but transparent close to each other can create issues, especially when they are plane-like objects.

**Comment by michaelvogt** [comment]
Romain, thank you for your continued answers that help me to understand whats going on.

With center of the object, do you mean the center set here?
`ModelRenderable renderable = ShapeFactory.makeCube(new Vector3(0.5f, 0.01f, 0.5f), Vector3.zero(), material);`

It is set to zero in this case, but when I set it to the value set as localPosition, and set the localPosition to `Vector3.zero()` instead, the effect is the same.

**Comment by romainguy** [comment]
It's the calculated center of the bounding box, transformed by the object's position/rotation/scale.

**Comment by michaelvogt** [comment]
As the position of the centers is so 'far' away in this case, both horizontally and vertically, I think there should be a way to improve this calculation.

**Comment by romainguy** [comment]
It's the distance of the centers to the camera plane. And like I said earlier the issue is that other ways of computing the distances break in other cases (I know some engines let you choose which distance algorithm you want precisely for that reason).

**Comment by michaelvogt** [comment]
Obviously I don't know enough about the rendering process to understand the problem here. I just notice this as another weird behaviour of Sceneform I have to work around.

Good thing is, setting the render priority to 0 for the background seems to finally solve this problem.
