### ISSUE TITLE
Different default rotation for horizontal and vertical plane

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/sceneform-android-sdk#286]
While doing some tests for another issue just reported, I saw this effect: 
the rotation of the nodes is different when dropped on a horizontal plane or a vertical plane. Is there something basic wrong with the [code](#285), or is it just necessary to always initialize the rotation of objects? Any ideas?

Please let's assume for a moment that everything is fine with ARCore.

**Comment by michaelvogt** [comment]
I realized that this was already discussed at #65, which is closed but the issue still exists. 

While there seems to be a reason for the rotation (which explanation I didn't understand), but to me it looks pretty much arbitrary. Everytime I attach mit objects to the plane, they are rotated differently, even when standing in the exact same location.

The mentioned workaround in the ticket mentioned above worked for me.

**Comment by malik-at-work** [comment]
Looks like you've already found the info you need for this one, but to add a little bit more info:
We use ArCore's rules for hit testing which are described here: https://developers.google.com/ar/reference/java/com/google/ar/core/HitResult#getHitPose()  Anchors are typically created from these results.

The rules for hit result is the same for vertical and horizontal planes.  When placing a poster or image you actually will want a different orientation than this default one however.
