### ISSUE TITLE
How to animate an Object up and down

### ISSUE THREAD

**Issue by yashvv** [google-ar/sceneform-android-sdk#288]
Hi,

I'm trying to animate an object up and down once the Renderable has been set to a Node. 

Node OrbNode = new Node();
OrbNode.setParent(parentNode);
OrbNode.setRenderable(webOrbRenderable);
OrbNode.setLocalScale(new Vector3(0.15f, 0.15f, 0.15f));
OrbNode.setLocalPosition(new Vector3(0.2f, 0.15f, -0.1f));

For Spinning I'm currently using this code:
private static ObjectAnimator createSpinI tAnimator() {
        // Node's setLocalRotation method accepts Quaternions as parameters.
        // First, set up orientations that will animate a circle.
        Quaternion orientation1 = Quaternion.axisAngle(new Vector3(1.0f, 0.0f, 0.0f), 0);
        Quaternion orientation2 = Quaternion.axisAngle(new Vector3(1.0f, 0.0f, 0.0f), -40);

        ObjectAnimator orbitAnimation = new ObjectAnimator();
        orbitAnimation.setObjectValues(orientation1, orientation2);

        // Next, give it the localRotation property.
        orbitAnimation.setPropertyName("localRotation");

        // Use Sceneform's QuaternionEvaluator.
        orbitAnimation.setEvaluator(new QuaternionEvaluator());

        //  Allow orbitAnimation to repeat forever
        orbitAnimation.setRepeatCount(ObjectAnimator.INFINITE);
        orbitAnimation.setRepeatMode(ObjectAnimator.RESTART);
        orbitAnimation.setInterpolator(new LinearInterpolator());
        orbitAnimation.setAutoCancel(true);

        return orbitAnimation;
    }

I tried drop animation using:
  private static ObjectAnimator createDropAnimator() {

        Vector3 vector1 = new Vector3(0.2f, 0.15f, -0.1f);
        Vector3 vector2 = new Vector3(0.5f, 0.15f, -0.1f);

        ObjectAnimator dropAnimation = new ObjectAnimator();
        dropAnimation.setObjectValues(vector1, vector2);
        dropAnimation.setPropertyName("dropAnimation");

        dropAnimation.setEvaluator(new Vector3Evaluator());

        dropAnimation.setInterpolator(new LinearInterpolator());
        dropAnimation.setAutoCancel(true);

        return dropAnimation;
    }

any changes needed?

**Comment by siny-yao** [comment]
Have you solved this problem? I also want to implement this function.

**Comment by siny-yao** [comment]
I work in this code :
` Vector3 vector1 = new Vector3(getRandom(), getRandom(), playNode.getLocalPosition().z);
        ObjectAnimator dropAnimation = new ObjectAnimator();
        dropAnimation.setObjectValues(vector1);
        dropAnimation.setPropertyName("localPosition");

        dropAnimation.setEvaluator(new Vector3Evaluator());
        dropAnimation.setRepeatCount(ObjectAnimator.INFINITE);
        dropAnimation.setRepeatMode(ObjectAnimator.RESTART);
        dropAnimation.setInterpolator(new LinearInterpolator());
        dropAnimation.setAutoCancel(true);

        return dropAnimation;`
