### ISSUE TITLE
ARCore not compatible with moto G5S Plus

### ISSUE THREAD

**Issue by gitikadaswani** [google-ar/sceneform-android-sdk#29]
I am trying to run the sample app on Moto G5S plus. However it giving me an error saying not compatible. Please help me out here.

**Comment by dhruvesh13** [comment]
Even i am facing the same issue.

**Comment by malik-at-work** [comment]
ARCore's list of supported devices is at https://developers.google.com/ar/discover/supported-devices

https://github.com/google-ar/arcore-android-sdk/issues would be a good place to discuss device support.
