### ISSUE TITLE
How to implement custom material with normal map

### ISSUE THREAD

**Issue by yashvv** [google-ar/sceneform-android-sdk#293]
Hello,

I'm trying to use a custom material with normal map for an object. Is there any example for similar implementation?

Thank You
Yash

**Comment by romainguy** [comment]
Normal maps are supported without custom materials, as documented here: https://developers.google.com/ar/develop/java/sceneform/sfa (see the `normal` and `normalMap` parameters for GLTF and FBX). If you need a custom material, please refer to https://developers.google.com/ar/develop/java/sceneform/custom-material, section "prepareMaterial function". It shows an example of normal mapping.
