### ISSUE TITLE
Sceneform ArFragment Auto Permission Handling messing with MULTIPLE PERMISSION 

### ISSUE THREAD

**Issue by MuhammadAasharib** [google-ar/sceneform-android-sdk#296]
Hi,
I am trying to take multiple permissions. But when I first time run app after installation app pops up "request permission" windows only for ARCore Camera permission (which is i think Automatic permission for ArFragment). When I open application for next time then it asks for remaining permissions.
My question for developers is whether sceneform sdk messes with the permissions I set in the android manifest?

Thankyou.

**Comment by abramyan** [comment]
Are you overriding [getAdditionalPermissions](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/ux/ArFragment.html#getAdditionalPermissions()) in ArFragment or BaseArFragment?

**Comment by abramyan** [comment]
Were you able to resolve your issue?

**Comment by MuhammadAasharib** [comment]
Thanks for the help I have resolved the issue myself.

**Comment by ishaang10** [comment]
can you be more specefic.im also having the same issue and using customArfragment by subclassing arfragment.
