### ISSUE TITLE
Is there any event for asset changed position/orientation ?

### ISSUE THREAD

**Issue by gkverma** [google-ar/sceneform-android-sdk#298]
I am building a multiplayer app using cloud anchors where two or more people can interact on one or more asset. When the asset changes it's position , how to get the event to broadcast to other connected users ? 
Help !

**Comment by ManuelTS** [comment]
You could try [TranslationController#isTransforming()](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/ux/TranslationController.html#isTransforming()), but since there is no documentation on this method it is hard to tell without conducting own tests.

**Comment by nandantal** [comment]
any update on this ?

**Comment by malik-at-work** [comment]
Yes we've added a listener to notify on position changes.  You would still have to implement the networking aspects of this.  This code is committed and will be part of an upcoming release

**Comment by nandantal** [comment]
Thanks for the update. It will be a great help for multiplayer apps/games.

**Comment by malik-at-work** [comment]
Fixed in 1.6
