### ISSUE TITLE
Sceneform Tools (Beta) Plugin does not correctly import gltf files with pbrSpecularGlossiness material

### ISSUE THREAD

**Issue by pradnya11** [google-ar/sceneform-android-sdk#3]
I tried importing a .gltf file with pbrSpecularGlossiness material. I did not get any error, and the .sfa and .sfb files were generated. However, both the .sfa and .sfb files do not contain any specular information.

Also, the app/build/sceneform_sdk/default_materials/gltf_material.sfm file contains information for just the pbrMetallicRoughness material, and not for pbrSpecularGlossiness.

It will be great if pbrSpecularGlossiness material is supported as well.

Google Sceneform Tools (Beta) Version: 1.0.0
Android Studio 3.1.1
Build #AI-173.4697961, built on April 4, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.4

**Comment by tpsiaki** [comment]
Thanks for the request!  We don't yet support gltf extensions in Sceneform (pbrSpecularGlossiness or unlit), but we are working to expand the material variations that we support for importing, so stay tuned.

**Comment by claywilkinson** [comment]
pbrSpecularGlossiness is now supported starting with version 1.4.
