### ISSUE TITLE
SceneForm with Geolocation 

### ISSUE THREAD

**Issue by naderz** [google-ar/sceneform-android-sdk#30]
Is there a sample or guidance on how Geolocation can be integrated with Sceneform? 
What im trying to achieve is to be able to open the camera and see in which direction are places around me geographically according to long and lat and my long and lat.

Is there any guidance of how i can utilise sceneform to achieve that ?

**Comment by malik-at-work** [comment]
We don't have a sample of this since it's a larger scope than Sceneform.

You could hack together something with Maps API (Places API, for example has a lot of geolocation capabilities) or Android's sensors then use Sceneform to render whatever you decide needs to be shown.
