### ISSUE TITLE
A problem with texture

### ISSUE THREAD

**Issue by arvifox** [google-ar/sceneform-android-sdk#303]
Hi everyone.
I built sfb file from obj. You can see at the image below.
![img-2018-09-05-10-37-26](https://user-images.githubusercontent.com/7602319/45078094-c0a13080-b0f7-11e8-817d-8b7ee4dc9ea8.png)
If I change the texture I get a problem.
![screenshot_20180905-034117](https://user-images.githubusercontent.com/7602319/45078427-b16eb280-b0f8-11e8-9254-676921860d1f.png)
In the center of model texture is correct, and on the right and left side texture is stretched.
Where is the problem?

**Comment by arvifox** [comment]
The code is here https://github.com/arvifox/sceneformsofatest

**Comment by dsternfeld7** [comment]
Are you changing the texture at runtime or in the sfb? If it is at runtime, you likely need to set the sampler for the texture so that the texture repeats.

```
    Texture.Sampler sampler = Texture.Sampler.builder().setWrapMode(WrapMode.REPEAT).build();
    Texture.builder().setSampler(sampler);
```

**Comment by arvifox** [comment]
@dsternfeld7 thanks. it works.
