### ISSUE TITLE
Black texture on 3D objects

### ISSUE THREAD

**Issue by rramprasad** [google-ar/sceneform-android-sdk#305]
I am using Sceneform SDK 1.4 and it renders good on other devices except On Samsung S7. It shows black texture on 3DObject. This kind of issue I have seen in  [Native ARCore SDK rendering](https://github.com/google-ar/arcore-android-sdk/issues/231). Is this issue fixed in Sceneform SDK or need to do any workaround to fix?

![samsung_s7_issue](https://user-images.githubusercontent.com/5563948/45133881-50f17b00-b1b5-11e8-940b-7d7315a091d8.jpg)

**Comment by malik-at-work** [comment]
We are able to reproduce this and are tracking it as a bug.

**Comment by claywilkinson** [comment]
This has been fixed in 1.6 of Sceneform.  Please re-open the issue if you are still experiencing this problem after updating your application to use 1.6.

**Comment by asbhattara** [comment]
The same problem was spotted with latest sceneform in Google Pixel 2 XL phone. Had to downgrade to sceneform 1.13.0 to remove the error.

**Comment by c4software** [comment]
Same problem on a P20Pro 😟
