### ISSUE TITLE
How can I add a ViewRenderable fit the floor?

### ISSUE THREAD

**Issue by stevenduan17** [google-ar/sceneform-android-sdk#319]

**Comment by malik-at-work** [comment]
It's possible to do something like this but it would require a lot of work beyond ArCore or Sceneform.  ArCore returns planes as soon as it find them.  This means the planes will start small and then grow as ArCore find out more about the room.  To "fit" the floor you'd need to wait until ArCore understands the room very well and has a large plane detected before you start rendering.

The you would use something like https://developers.google.com/ar/reference/java/com/google/ar/sceneform/rendering/ViewSizer to get the ViewRenderable to the right size.

**Comment by ChanduMnS** [comment]
Hi @malik-at-work ,
Your solution is relevant to my use case. Can you give any example that shows the implementation. Your help will be very much appreciated. Thank you.
