### ISSUE TITLE
BaseArFragment always calls requestPermissions in onCreateView

### ISSUE THREAD

**Issue by guerwan** [google-ar/sceneform-android-sdk#32]
Meaning even if we already have the camera permission any activity containing an ArFragment is paused just after its creation and resumed just after.

**Comment by malik-at-work** [comment]
Thanks for the feedback, I've communicated this to the team.

**Comment by malik-at-work** [comment]
If you'd like to change this behavior before our next release you can override BaseArFragment.requestDangerousPermissions() in your fragment to do nothing when you have the permissions you want.

**Comment by malik-at-work** [comment]
Fixed in Sceneform V1.3
