### ISSUE TITLE
Unreliable result of hitTestResult.getPoint().x

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/sceneform-android-sdk#322]
I have a custom material added to a cube shape object. In the touchListener I get the x value from the hitTestResult parameter, and set this value in the material.

`material.setFloat("dividerLocation", hitTestResult.getPoint().x);`

In the fragment shader I use this value to display one texture on the left side from this point, and another one on the right side (see image below)

```
float dividerMask = step(dividerLeft, uv.x) * (1.0 - step(dividerRight, uv.x));
material.baseColor = mix(material.baseColor, materialParams.dividerColor, dividerMask);
```
1) This works quite well on my Pixel 2, but on the Zenfone AR the point provided by hitTestResult seems kind of random. Sometimes only a bit, other times so much that the divider is stuck at the left or right side. 
**So, I wonder if I can actually use the provided x value from hitTestResult directly like I do, or are there any additional calculations necessary?**

2) When I set a localScale to the background, values provided by hitTestResult result in the divider being moved faster or slower relative to the finger, depending of the scale value being above or below 1. 
**Is this to be expected or a bug?**

Just in case someone wonders about the dots of the plane showing up on top of the objects: The background is actually positioned 10cm in front of the anchornode of the plane, but still showing the dots like this.

![screenshot_20180915-204939](https://user-images.githubusercontent.com/231274/45586179-41003680-b92d-11e8-9ecb-e6f78994935f.jpg)

**Comment by dsternfeld7** [comment]
I'm not sure about the issue on zenfoone, we will try to reproduce that. In the meantime, I'll try to answer your question about scale.

Based on my current understanding of what you are doing, it sounds like what is happening with scale is expected. I think it's likely that it's caused by a coordinate space mismatch. The result of `hitTestResult.getPoint()` will be in world coordinate space, so you may want to convert it to the local coordinate space of the node before you pass it into the material by using `Node.WorldToLocalPoint`. You'll have to make sure that `dividerLeft`, `dividerRight`, and `dividerLocation` are all in the same coordinate space. How were you setting `dividerLeft` and `dividerRight`?

**Comment by michaelvogt** [comment]
Thank you for your answer. Calling `worldToLocalPoint `for the point provided by `hitTestResult `seems to improve the reliability, according some quick tests inside. Thank you very much. 

To answer your question, the `dividerleft `and `dividerRight `just define the with of the white line between the 2 images as seen in the image above

```
        float dividerLeft = materialParams.dividerLocation - materialParams.dividerWidth;
        float dividerRight = materialParams.dividerLocation + materialParams.dividerWidth;

```
`dividerLocation `is the value provided by `hitTestResult`, `dividerWidth `is defined in the .sfa file as 0.003.

What's been surprising to me is, that the positioning of the divider was different between starts of the AR session, even when standing that the same place with the device pointing more or less to the same location of the wall.

The same problem as described above showed up yesterday also on the Pixel2, so it isn't strictly a problem with the Zenfon AR, but the Pixel2 shows the problem much less for me.

**Comment by michaelvogt** [comment]
Seems like the worldToLocalPoint conversion did the trick. Worked reliably since the change on both phones.

Thanks
