### ISSUE TITLE
How to use a stream of images to be the background of SceneView?

### ISSUE THREAD

**Issue by sandeepbangalore** [google-ar/sceneform-android-sdk#323]
I have a phone with ARCore enabled and I am sending the video feed as images to another phone. I want to use this stream of images as a background in the other phone instead of invoking the Camera. ExternalTexture seems to be the way to go but I am having a problem understanding how to implement it. Though there is a sample project which renders a video, I would like to understand how I can use the same concept towards real time video rendering. I am using OpenTok for sending and receiving the video feed. Some help in this direction is greatly appreciated.

**Comment by dsternfeld7** [comment]
Does the information in issue [274](https://github.com/google-ar/sceneform-android-sdk/issues/274) that shows how to render an ExternalTexture as a background help you with this?

**Comment by sandeepbangalore** [comment]
I did have a look at issue 274 but it seems like those images are being passed through the camera's setPreviewDisplay. Is there a way to do it without having to use the camera API?

**Comment by dsternfeld7** [comment]
Yes, you can use the technique described in issue 274 to render an ExternalTexture as a background, and then render anything you want to the ExternalTexture's surface.

**Comment by sandeepbangalore** [comment]
I will try that out, thanks. Will get back to you if I have any issues.

**Comment by dsternfeld7** [comment]
The y coordinates in your obj file are going  from 0 - 1, but they should be -1 to 1.

**Comment by sandeepbangalore** [comment]
I did try it with -1 to 1 but had no luck. I anyways found a work around to my bigger problem and have decided to go with an ArSceneView itself. Thanks!
