### ISSUE TITLE
Some gltf items are not rendered properly

### ISSUE THREAD

**Issue by bkkite** [google-ar/sceneform-android-sdk#324]
Hi, I have problems trying to convert from gltf to sfb.

Original in gltf viewer
![viewr](https://user-images.githubusercontent.com/20543680/45693269-011f9600-bb5d-11e8-8136-a7bdf4611df3.png)

Sfb in AndroidStudio viewer
![androidstudio](https://user-images.githubusercontent.com/20543680/45693346-2e6c4400-bb5d-11e8-9d25-c51c8b6ecbfe.png)

Using default matrial in Gradle pluging.

This are files:
[files.zip](https://github.com/google-ar/sceneform-android-sdk/files/2393025/files.zip)

Why color of materials are so differents? and What are these  black blocks?

**Comment by gstanlo** [comment]
The colors are probably different because the two viewers are using different environment lighting.

The black blocks appear to be from NaNs stored in the glTF's tangents and bitangents. The Sceneform converter uses those attributes, while the online viewer ignores them and regenerates them on its own, which is why there's a difference. Notice that there's a significant amount of errors present in the glTF file as reported by the glTF validator.

**Comment by bkkite** [comment]
> The colors are probably different because the two viewers are using different environment lighting.

How can i setup this in ArCore sceneform?

> The black blocks appear to be from NaNs stored in the glTF's tangents and bitangents. The Sceneform converter uses those attributes, while the online viewer ignores them and regenerates them on its own, which is why there's a difference.

Yes we don't export tangents and bitangest, but why you don't do the same as online viewer and recreate them? i know is not the best solution. But it's better than drawing black blocks, right?

> Notice that there's a significant amount of errors present in the glTF file as reported by the glTF validator.

We created the gltf from an automatic process reading a database where we saved our building objects. About errors, we are working to solve them. But we don't think this is the problem. Most of them are information that is not in use or precission problems when we write to text and what is saved as binary.

Thanks!

**Comment by romainguy** [comment]
We should definitely detect NaNs and generate our own tangent/bitangent in that case.

**Comment by gstanlo** [comment]
That's my mistake, I looked at the output which contained NaNs and assumed they came from the input buffer, but none of the primitives appear to be specifying tangents/bitangents. Sceneform should be generating them, and it appears to be a bug that it's generating NaNs.

**Comment by tpsiaki** [comment]
This is fixed as of Sceneform 1.7
