### ISSUE TITLE
Sceneview setBackground Drawable overlaps the 3D model

### ISSUE THREAD

**Issue by khonakr** [google-ar/sceneform-android-sdk#332]
Hello,
While using SceneView setBackground there is some inconsistency happening.
sceneView.setBackground(someColorDrawable);
works fine, sets the background to the specific Color

![screenshot sep 21 2018 3_43_06 pm](https://user-images.githubusercontent.com/3877104/45902698-4fc76d00-bdb5-11e8-9691-e3b9a08811f2.png)

Where as,
sceneView.setBackground(drawable);
for some reason, does not work fine and brings up the image on top of the 3D model in the Sceneview as opposed to background. Hence after adding the Drawable background the 3D model does not render any more.

![screenshot_20180921-153826](https://user-images.githubusercontent.com/3877104/45902723-6b327800-bdb5-11e8-8926-e65ae073edf7.png)

I have tried both java / xml ways to set the drawable as well as tried multiple of those.

**Comment by romainguy** [comment]
Only color drawables are supported. `SceneView` is a `SurfaceView`, which doesn't support the concept of background really.

**Comment by khonakr** [comment]
@romainguy Any workarounds to to achieve something like this?
I even tried the second solution from here after extending SceneView:
https://stackoverflow.com/questions/5981098/set-the-background-image-of-a-surfaceview

It draws it, but overlaps my model.

**Comment by romainguy** [comment]
You can do it this way but it's expensive, I would recommend against it. You could simply draw a textured quad or triangle in the 3D scene.

**Comment by khonakr** [comment]
@romainguy Thanks for the tip! I placed an ViewRenderable with ImageView+Drawable far away (in z) from the origin and scaled it appropriately to act like a backdrop. This way it doesn't interfere with my 3d model in the front.

**Comment by renjithkn** [comment]
@khonakr hi, could you please help on this, am also looking for the same solution, could you please share the code or sample of this.
