### ISSUE TITLE
Is there any ways to detect plain wall?

### ISSUE THREAD

**Issue by meetVora1994** [google-ar/sceneform-android-sdk#335]
I am trying to scan the plain white colored wall, but not getting any Plane reference points.
Is there any way how I could achieve this as I want to place a 3D object on that wall (for example a wall fan).

Or is there any ways in which I can create the Plane manually and then place the object on it?

**Comment by abramyan** [comment]
ARCore detects visually distinct features in the captured camera image called feature points and uses these points to compute its change in location. The plain white wall might not have enough distinct features.

There isn't a way to create an ARCore Plane manually.  While you can theoretically place an object in the world, tracking it will be flaky if the device cannot compute its location.
