### ISSUE TITLE
Reopen: Sceneform Objects when resolved from Cloud Anchors are not placed on the surface.

### ISSUE THREAD

**Issue by luislukas** [google-ar/sceneform-android-sdk#337]
Hi,
just wanted to check whether we could reopen the following issue: https://github.com/google-ar/sceneform-android-sdk/issues/170 
I'm not the original author but I'm exactly experiencing the same situation plus I've added information around that and how I'm resolving and using Cloud Anchors.
Let me know if it's best to track in this ticket or the original.
Thanks.

**Comment by malik-at-work** [comment]
I reopened that issue. Let's track there.
