### ISSUE TITLE
blending mode "fade" available?

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/sceneform-android-sdk#338]
In #196 @romainguy said he had implemented internally a new 'fade' blending mode. Is this available publicly with version 1.5? Just checked the Custom Material Reference page, where it isn't added so far.

**Comment by romainguy** [comment]
It is available yes. Set blending to fade instead of transparent in your custom material.

**Comment by michaelvogt** [comment]
Sorry for not reporting back. Can't test in my app right now.

But I don't see this ticket as closed, as the custom material documentation is still not updated.

**Comment by abramyan** [comment]
Thanks for calling it out. We'll update the documentation.

**Comment by claywilkinson** [comment]
The documentation has been updated and I confirmed the [blending mode](https://developers.google.com/ar/develop/java/sceneform/custom-material#blending) contains fade.
