### ISSUE TITLE
[Question] How to improve render quality?

### ISSUE THREAD

**Issue by pilgr** [google-ar/sceneform-android-sdk#339]
Here is I draw lines using cylinders, but the overall image quality is not so good. Is it possible to improve it? Some sort of antialiasing? I couldn't find it in API. 

Here is the screenshot from Pixel 1 running Android 9.

Sorry if that is a stupid question, newbie in graphics speaking.

![device-2018-09-28-213357](https://user-images.githubusercontent.com/429345/46226987-95140d80-c366-11e8-99b5-28205c184cc2.png)

**Comment by romainguy** [comment]
Antialiasing is turned on by default already, you can actually see it in your screenshot. The type of antialiasing used by default — FXAA — works better on lower-contrast scenes. I would recommend using a background in your scene in this case. The renderer can also use MSAA which would work better in this particular case but Sceneform doesn't provide APIs to switch the antialiasing mode at this time.

**Comment by pilgr** [comment]
Thank you!
