### ISSUE TITLE
How to draw a line?

### ISSUE THREAD

**Issue by NiaNingXue** [google-ar/sceneform-android-sdk#34]
I only find the Ray api

**Comment by dsternfeld7** [comment]
Currently, there is no API specifically for rendering lines in Sceneform. One way to render a line would be to use a model of a cylinder and then rotate, scale, and position a node to visualize the cylinder as a line between two points. Could you provide more information on what you need for your use case?

**Comment by NiaNingXue** [comment]
@dsternfeld7  I want to write a AR ruler app

**Comment by dsternfeld7** [comment]
Very cool! Closing out this issue. Please make a new ticket for additional issues/questions related to your use-case.
