### ISSUE TITLE
Unresolved reference RenderableSource

### ISSUE THREAD

**Issue by cgathergood** [google-ar/sceneform-android-sdk#340]
Hey team,

I've just upgraded to Sceneform 1.5

Top level build.gradle
`classpath 'com.google.ar.sceneform:plugin:1.5.0'`

App level build.gradle
`implementation 'com.google.ar.sceneform.ux:sceneform-ux:1.5.0'`

But the new class [RenderableSource](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/assets/RenderableSource) cannot be resolved.

Let me know if I can provide any more information

**Comment by luislukas** [comment]
Hi @cgathergood ,
There's a new library they mention in the release notes that has that class. Just import
`implementation 'com.google.ar.sceneform:assets:1.5.0'`

**Comment by cgathergood** [comment]
Hey @luislukas I must have skimmed over that when reading the notes. Thanks so much!
