### ISSUE TITLE
Quaternion.lookRotation instability?

### ISSUE THREAD

**Issue by DrPaulT** [google-ar/sceneform-android-sdk#345]
It's always possible that I have not understood the intention of this method, but I am seeing some odd behaviour!

Here's a code snippet:

    Vector3 UP = new Vector3(0, 1, 0);
    Quaternion quaternion = Quaternion.lookRotation(new Vector3(
                                0, (float) Math.sin(-elevation), 1).normalized(), UP);
    node.setLocalRotation(quaternion);
    Log.i("TOUCH_EVENT", "elevation = " + elevation + " sin = " + Math.sin(-elevation)
          + " q = w " + quaternion.w + " x " + quaternion.x + " y " + quaternion.y + " z " + quaternion.z);

As elevation changes from a little below zero, through zero and above, the quaternion flips round through 180 degrees, then flips back to where it should be.

Here's the log output for TOUCH_EVENT:

elevation = -0.0632377 sin = 0.06319555732131173 q = w -0.9995022 x 0.031550206 y 0.0 z 0.0
elevation = -0.0510032 sin = 0.05098108928597383 q = w -0.99967575 x 0.025464354 y 0.0 z 0.0
elevation = -0.03836636 sin = 0.03835694701724931 q = w 6.122109E-17 x -1.1736956E-18 y 0.99981624 z -0.019167902
elevation = -0.025491359 sin = 0.02548859804805906 q = w 6.122737E-17 x -7.801733E-19 y 0.9999188 z -0.012741196
elevation = -0.012491358 sin = 0.012491033600450603 q = w 6.123115E-17 x -3.8240529E-19 y 0.9999805 z -0.006245152
elevation = 7.586414E-4 sin = -7.586413266721479E-4 q = w 6.1232336E-17 x 2.3226692E-20 y 0.99999994 z 3.7932064E-4
elevation = 0.014777074 sin = -0.014776535850863751 q = w 6.123067E-17 x 4.523639E-19 y 0.9999727 z 0.007387663
elevation = 0.029266331 sin = -0.02926215366642778 q = w 6.122579E-17 x 8.956075E-19 y 0.999893 z 0.01462638
elevation = 0.043891333 sin = -0.04387724199763511 q = w 6.1217625E-17 x 1.3423843E-18 y 0.9997597 z 0.021922797
elevation = 0.058641333 sin = -0.0586077295504146 q = w 0.9995716 x 0.029266477 y 0.0 z 0.0
elevation = 0.07364133 sin = -0.07357478800228877 q = w 0.9993259 x 0.0367129 y 0.0 z 0.0

So we have a look vector (0, y, 1) which should always work with an up vector of (0, 1, 0).  There shouldn't be any instability or gimbal lock for these values.

Have I misunderstood how lookRotation should work or is this a defect?

**Comment by dsternfeld7** [comment]
There shouldn't be any instability with those values, that is true. However lookRotation is always going to give you the shortest rotation from Vector3.forward() to the specified forward direction, which may be why you're seeing the quaternion flip. Can you share a screenshot or  video showing what the issue looks like?

**Comment by dsternfeld7** [comment]
I looked into this a bit more closely, this actually does create an unstable rotation.

lookRotation creates a rotation from the specified forward direction to Vector3.forward by calling Quaternion.rotationBetweenVectors, while trying to align the y-axis with up in world. This means that when elevation is at or near zero, the specified forward is (0, ~0, 1), and Vectror.forward is (0, 0, -1).

Try calling Quaternion.rotationBetweenVectors(new Vector3(
                            0, (float) Math.sin(-elevation), 1).normalized(), Vector3.forward()); and you will see essentially the same behavior that you are seeing now, and it will be more obvious why the rotation is unstable.

**Comment by dsternfeld7** [comment]
No problem, I'm glad that was helpful!
