### ISSUE TITLE
For TramsformableNode, Pinch getsture doesn't work at the first time.

### ISSUE THREAD

**Issue by CranberryYam** [google-ar/sceneform-android-sdk#347]
Pinch gesture only works after the first touch events, either users touch the 3d object first or drag the 3d object first.

**Comment by dsternfeld7** [comment]
To scale a TransformableNode, it must be selected. You can ensure that the TransformableNode is selected when it is first created by calling TransformableNode.select().

**Comment by CranberryYam** [comment]
> To scale a TransformableNode, it must be selected. You can ensure that the TransformableNode is selected when it is first created by calling TransformableNode.select().

Aha, really appreciate it!!!
