### ISSUE TITLE
Is there a way to load models from server

### ISSUE THREAD

**Issue by RavindraVirat** [google-ar/sceneform-android-sdk#35]
In Sceneform sample app we are loading models from model folder, in case I have more then 20 models assume for any shopping app then if I put all those models in asset folder, apk size will increase, so my question is can we load models means 'model related files like obj, mtl, png, sfa, sfb' from server and save to local then go for rendering.

**Comment by dsternfeld7** [comment]
The generated sfb file contains all of the data for the model, so if you copy just the sfb file to a web server, you can then load the renderable via a url:

`ModelRenderable.builder().setSource(this, Uri.parse("https://www.foo.com/bar.sfb")).build();`

The download will automatically happen on a background thread.

Alternatively, you could write your own mechanism for downloading the .sfb files (zipped together or otherwise) and load them using a file:// URI or from an InputStream.

**Comment by RavindraVirat** [comment]
Thank you for reply.

In sceneform sample app I observed that the model is already configured in gradle file as below - 
sceneform.asset('sampledata/models/andy.obj',
        'default',
        'sampledata/models/andy.sfa',
        'src/main/res/raw/Andy')

, in this case model is already available, so if I download the new model from server then how will I mention my newly downloaded file in gradle.

**Comment by ldima** [comment]
@dsternfeld7 I have got  

Unable to load Renderable Unable to load Renderable registryId='file:///storage/emulated/0/Download/lion3.sfb'
                                                                               java.util.concurrent.CompletionException: java.io.FileNotFoundException: /storage/emulated/0/Download/lion3.sfb

File is exist.
What does it mean?

**Comment by RavindraVirat** [comment]
If you pass Uri of the .sfb file to setSource() method , it is not working, giving 
IllegalArgumentException: Unable to parse url,
MalformedURLException: unknown protocol: content.

I tried like this and its able to render - 
setSource(this, new Callable<InputStream>() {
                    @Override
                    public InputStream call() throws Exception {
                        FileInputStream fileInputStream = null;
                        try {
                            fileInputStream = new FileInputStream(getFilePath());
                        } catch (FileNotFoundException e) {
                            e.printStackTrace();
                        }
                        return fileInputStream;
                    }
                })

getFilePath() method will return path of the .sfb file.

**Comment by ishaang10** [comment]
How to load a model from a file input stream ????

I downloaded the file from server using the download manager and its path is Content://downloads/all_download/190.   
so if i can somehow get it in a filestream . then how can i load that model.




its the .sfb file.

**Comment by artemtkachenko** [comment]
@ishaang10 
seems like this is what you are looking for

``` kotlin
ModelRenderable.builder()
            .setSource(context, Callable<InputStream> {
                return@Callable FileInputStream(%downloaded_file_absolute_path_string%)
            })
            .build()
```

Nevertheless I am not sure that a `content://` uri can be a source for `downloaded_file_absolute_path_string`. I suggest using a `file://` uri instead. It works for sure.
