### ISSUE TITLE
Reopen: How to remove the circle when the 3D object is selected?

### ISSUE THREAD

**Issue by CranberryYam** [google-ar/sceneform-android-sdk#352]
For some 3D models, when they're selected, There is a gray circle on the bottom. How to hide those circles for sure?

**Comment by gstanlo** [comment]
Then call [getSelectionVisualizer](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/ux/TransformationSystem#getSelectionVisualizer()), and then call

**Comment by gstanlo** [comment]
1. Call [getTransformationSystem](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/ux/BaseArFragment#getTransformationSystem()) on your ArFragment (or acquire it from somewhere)

1. Call [getSelectionVisualizer](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/ux/TransformationSystem#getSelectionVisualizer()) on the transformation system

1. Call [removeSelectionVisual](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/ux/SelectionVisualizer#removeSelectionVisual(com.google.ar.sceneform.ux.BaseTransformableNode)) on the selection visualizer, passing in the node you want. 

You can also modify the selection visualizer or write your own.

**Comment by CranberryYam** [comment]
> 1. Call [getTransformationSystem](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/ux/BaseArFragment#getTransformationSystem()) on your ArFragment (or acquire it from somewhere)
> 2. Call [getSelectionVisualizer](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/ux/TransformationSystem#getSelectionVisualizer()) on the transformation system
> 3. Call [removeSelectionVisual](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/ux/SelectionVisualizer#removeSelectionVisual(com.google.ar.sceneform.ux.BaseTransformableNode)) on the selection visualizer, passing in the node you want.
> 
> You can also modify the selection visualizer or write your own.

Thanks! Really Helpful. Consider to publish a more detailed documentation of Sceneform?

**Comment by CranberryYam** [comment]
After following your instructions, the circle did disappear. However, when I use the pinch gesture, the circle shows up again.

**Comment by dementia2029** [comment]
@CranberryYam Implement your custom SelectionVisualize, override applySelectionVisual and removeSelectionVisual and leave it blank.

**Comment by CranberryYam** [comment]
> @CranberryYam Implement your custom SelectionVisualize, override applySelectionVisual and removeSelectionVisual and leave it blank.

It works, Thanks!

**Comment by CranberryYam** [comment]
Everyone, this's the final answer:
```
class BlanckSelectionVisualizer: SelectionVisualizer {
    override fun applySelectionVisual(var1: BaseTransformableNode) { }
    override fun removeSelectionVisual(var1: BaseTransformableNode) { }
}
```
```
system.selectionVisualizer = BlanckSelectionVisualizer()
```
