### ISSUE TITLE
How to avoid app crash from session.createAnchor(pose)?

### ISSUE THREAD

**Issue by CranberryYam** [google-ar/sceneform-android-sdk#355]
It happens in the following situations:
ArFragment just starts to run
Place the phone on the table with camera covered and pick the phone up

I tried to use try catch, but it still doesn't work.

**Comment by claywilkinson** [comment]
Can you share a log of the crash?  This is not a lot to go on in terms of helping you.

**Comment by CranberryYam** [comment]
> Can you share a log of the crash? This is not a lot to go on in terms of helping you.

Thanks for replying. I already solved it by try catch. I'll close this issue.
