### ISSUE TITLE
Dynamic features support bug.

### ISSUE THREAD

**Issue by istima** [google-ar/sceneform-android-sdk#356]
Sceneform doesn't work in dynamic features due to its way of addressing resources. 
`Unable to load Texture registryId='android.resource://com.arfeature.arprofile/drawable/sceneform_plane'
    java.util.concurrent.CompletionException: java.lang.IllegalStateException: java.io.FileNotFoundException: No package found for authority: android.resource://com.arfeature.arprofile/drawable/sceneform_plane
    java.util.concurrent.CompletionException: java.io.FileNotFoundException: No package found for authority: android.resource://com.arfeature.arprofile/raw/sceneform_plane_shadow_material`

Demo project with proper resource addressing and demo of the issue: https://goo.gl/GmufL3

This is a follow-up to https://github.com/google-ar/sceneform-android-sdk/issues/33 that was closed claimed the issue was fixed while it wasn't.

**Comment by kunalmshah85** [comment]
I am running in to same issue. Were you able to find any solution/ work around for this ?

**Comment by istima** [comment]
@kunalmshah85 nope, not yet. Still waiting for @tpsiaki or @abramyan for comment :(

**Comment by rozag** [comment]
We have the same issue. Looks, like nobody is going to fix that :(

**Comment by abramyan** [comment]
Sorry about the late response. We're looking into it.

**Comment by istima** [comment]
Thanks, Lucy! @abramyan

**Comment by kunalmshah85** [comment]
Thanks Lucy @abramyan  for looking in to this. my scenario is little bit different than what @istima has. My "Dynamic feature" module is just a facade which is dependent on xyz.aar and xyz.aar is using scene form. ny base module downloads dynamic feature at run time which brings in aar with sceneform code along with it. This scenario also results in to same error.

**Comment by istima** [comment]
It's madness - the fix require only a couple lines of code and still, it isn't implemented...

**Comment by kunalmshah85** [comment]
@tpsiaki @abramyan. Thanks for looking in to this and identifying it as bug. Would you guys be able to share details around time line for this bug fix.  or do you guys have any suggestions or workarounds on how to use Sceneform sdk and ArFragment with dynamic feature. we are working on AR project where we would like to leverage power of Dynamic Feature to reduce app size. if you can share timeline for this for this bug fix it would help us to better plan our project.

**Comment by istima** [comment]
@tpsiaki @abramyan  I"m joining to the question @kunalmshah85  asked.

**Comment by malik-at-work** [comment]
Fixed in 1.6

**Comment by coolrukshan** [comment]
I receive an error 
"com.google.ar.core.exceptions.FatalException: Application manifest must contain meta-data com.google.ar.core" when using ARCore in my dynamic feature module.
