### ISSUE TITLE
How to place a Renderable to a HitTestResult getPoint() location

### ISSUE THREAD

**Issue by blitz2306** [google-ar/sceneform-android-sdk#359]
I want to place a small sphere renderable to the location where an already placed model was tapped and also anchor it to that location. Can that be achieved and if so, how?

`private void tryPlaceModel(MotionEvent motionEvent, Frame frame)
   {
      if (isModelPlaced)
      {
         return;
      }

      if (motionEvent != null && frame.getCamera().getTrackingState() == TrackingState.TRACKING)
      {
         for (HitResult hit : frame.hitTest(motionEvent))
         {
            Trackable trackable = hit.getTrackable();

            if (trackable instanceof Plane && ((Plane) trackable).isPoseInPolygon(hit.getHitPose()))
            {
               // Create the Anchor.
               Anchor anchor = hit.createAnchor();
               AnchorNode anchorNode = new AnchorNode(anchor);
               anchorNode.setParent(arSceneView.getScene());

               TransformableNode model = new TransformableNode(arFragment.getTransformationSystem());
               model.setParent(anchorNode);
               model.setRenderable(andyRenderable);
               model.select();

               isModelPlaced = true;

               model.setOnTapListener((hitTestResult, motionEvent1) ->
               {
                  Frame frame1 = arSceneView.getArFrame();

                  if (motionEvent1 != null && frame1.getCamera().getTrackingState() == TrackingState.TRACKING)
                  {
                     com.google.ar.sceneform.rendering.Color color = new com.google.ar.sceneform.rendering.Color();
                     color.set(Color.RED);

                     MaterialFactory.makeOpaqueWithColor(this, color)
                           .thenAccept(
                                 material ->
                                 {
                                    Pose pose = Pose.makeTranslation(hitTestResult.getPoint().x, hitTestResult.getPoint().y, hitTestResult.getPoint().z);

                                    Anchor anchor1 = session.createAnchor(pose);

                                    AnchorNode anchorNode1 = new AnchorNode(anchor1);
                                    anchorNode1.setParent(hitTestResult.getNode());

                                    Renderable sphere = ShapeFactory.makeSphere(0.05f,
                                          /* WRONG LOCATION */anchorNode1.getLocalPosition(), material);

                                    Node indicatorModel = new Node();
                                    indicatorModel.setParent(anchorNode1);
                                    indicatorModel.setRenderable(sphere);
                                 }
                           );
                  }
               });
            }
         }
      }`

Here's where I am now. The code entirely works, except the location where I want the spheres to appear. I also tried with AnchorNode.getWorldPosition, but it's wrong too. 

The spheres are appearing to the back of the model. Is this because the getPoint() method returns the point where the ray hit the **plane** (although it is literally written that it returns the point the ray hits the model/node), or I am just doing something wrong?

**Comment by claywilkinson** [comment]
Hi @blitz2306  - I answered this  on Stackoverflow: https://stackoverflow.com/questions/52704938/how-to-place-a-renderable-to-a-hittestresult-getpoint-location

So closing this issue.
