### ISSUE TITLE
Failed to create AR session

### ISSUE THREAD

**Issue by Zhuxf1111** [google-ar/sceneform-android-sdk#36]
When i first ran hellosceneform , it can normal use.Later i ran it , the "Failed to create AR session" appeared

**Comment by Zhuxf1111** [comment]
The device is Samsung Galaxy S7 edge

**Comment by KamikX** [comment]
Hi @Zhuxf1111 check if you have this in AndroidManifest.xml inside application tag
```
        <meta-data
            android:name="com.google.ar.core"
            android:value="required" />
```

**Comment by Zhuxf1111** [comment]
@KamikX  Hi , i checked my AndroidManifest.xml and it contain the codes. I used the demo hellosceneform  and it worked fine before.

**Comment by malik-at-work** [comment]
Hi  @Zhuxf1111 can you add anything in the log?
You can get the log from the log monitor window in android studio or via 'adb logcat'

The first things I would check in general if the app is not working include: the version I had installed for ArCore, and the permissions on the app just to make sure camera access is allowed.

**Comment by Zhuxf1111** [comment]
Hi @malik-at-work ,I have updated the ArCore version and add the permission on the app .The log is so    much and i dont know which of them is you needed.So i attach all of them below

**Comment by Zhuxf1111** [comment]
[log.txt](https://github.com/google-ar/sceneform-android-sdk/files/2024907/log.txt)

**Comment by Zhuxf1111** [comment]
@claywilkinson  I reset the mobile phone.Then it works fine.

**Comment by claywilkinson** [comment]
Glad it is working now!

**Comment by MuhammamdArslanKhan** [comment]
Same issue I am using an emulator.
emulator version
27.3.10-4969155

Android version
8.1 (Oreo) - API 27

OpenGL setting

Renderer maximum 
SwiftShader

**Comment by chnouman** [comment]
Same issue previously it was working and suddenly it stopped working. Tried uninstalling app and other stuff but no luck.

**Comment by beNitinhere** [comment]
Same issue here but with back camera.

**Comment by 3bdar7man** [comment]
> Do any other ArCore applications work or is only Sceneform having an issue? For example try HelloAr https://developers.google.com/ar/develop/unity/tutorials/hello-ar-sample

Hi @malik-at-work 
Is there any of this in the form of an application(apk)?
