### ISSUE TITLE
TextureRegistry remembering textures from previous session

### ISSUE THREAD

**Issue by kstpr** [google-ar/sceneform-android-sdk#361]
Hi, in our app we are building `Renderable`s from `RenderableDefinition`s with geometry and textures extracted from our custom format. Since we are spawning hundreds, even thousands of renderables I was trying to reuse the textures adding a `registryId`:
```
Texture.builder()
    .setSource { FileInputStream(uri.path) }
    .setUsage(Texture.Usage.DATA)
    .setSampler(samp)
    .setRegistryId(textureId)
    .build()
```
The texture id being a simple hash from the texture path and sampler options that we use for the texture:
```
private fun calculateTextureHash(path: String, wrapModeS: Boolean, wrapModeT: Boolean): Int {
    var result = 17
    result = 31 * result + path.hashCode()
    result = 31 * result + (if (wrapModeS) 0 else 1)
    result = 31 * result + (if (wrapModeT) 0 else 1)

    return result
}
```
Debugging the decompiled builder class I can see that the textures are indeed reused for different objects. And the textures are the right ones when the model opens. The problems come when I have opened a model, then closed the viewer in our app and then open a different model from the models list. Some of the textures in the new model are reused textures from the previous model. This comes from the fact that in our custom format the textures have template names like `T_12.png` so the hashes are sometimes the same for different textures but in different sessions too. I wasn't expecting that. 

To "fix" the problem I can add some dummy object id which is unique for the session into the hash. But for some models we are using hundreds of textures, some with very high quality. Also from the `ResourceRegistry<T>` class I see that the resources are retained into a simple HashMap:
```
    private final Map<Object, WeakReference<T>> registry = new HashMap();
```
Can this thing cause `OutOfMemoryError`s after several sessions putting all these textures inside? I think I've seen some unexplained ones.

**Comment by romainguy** [comment]
It's a `HashMap` but you can see that it holds weak references. This should allow the textures to be GC'd after they are not referenced by any other object anymore.

This looks WAI to me, purging textures between sessions might not be what the application expects either.

**Comment by kstpr** [comment]
OK, I guess it's safe to use it as is. If something crashes unexpectedly I will report back. Thanks!

**Comment by malik-at-work** [comment]
Adding to this.. As Romain said, ResourceRegistry is only holding a WeakReference to the texture.  If the texture is still around it likely means that something else may be holding a hard reference to it.

  I haven't seen any issues with RenderableDefinition or Texture although I have fixed issues elsewhere.  There are a lot of ways this could happen in your code as well and it may be a real issue.

Common causes for surprising hard references include: singletons, long lived inner classes, long lived anonymous classes, static members, etc.
