### ISSUE TITLE
Can't move a TransformableNode when plane undetected

### ISSUE THREAD

**Issue by CranberryYam** [google-ar/sceneform-android-sdk#363]
The transformableNode object only can be moved when the plane is detected.

**Comment by dsternfeld7** [comment]
TransformableNode is designed only to be translated along ArCore planes. If you want a TransformableNode for a different use case, you can extend BaseTransformableNode and add your own TransformationControllers while excluding the default TranslationController that is used for translating nodes on planes.

**Comment by CranberryYam** [comment]
> TransformableNode is designed only to be translated along ArCore planes. If you want a TransformableNode for a different use case, you can extend BaseTransformableNode and add your own TransformationControllers while excluding the default TranslationController that is used for translating nodes on planes.

Can I move the object in the infinite plane instead of moving only when trackbale.isPoseInPolygon()?

**Comment by dsternfeld7** [comment]
You can do that by modifying [this](https://github.com/google-ar/sceneform-android-sdk/blob/master/sceneformux/ux/src/main/java/com/google/ar/sceneform/ux/TranslationController.java#L140) line of the TranslationController to remove the isPoseInPolygon check.

**Comment by CranberryYam** [comment]
> You can do that by modifying [this](https://github.com/google-ar/sceneform-android-sdk/blob/master/sceneformux/ux/src/main/java/com/google/ar/sceneform/ux/TranslationController.java#L140) line of the TranslationController to remove the isPoseInPolygon check.

So I have to fork my own version of Sceneform-sdk?

**Comment by dsternfeld7** [comment]
Yes, though it doesn't fork the whole SDK, just the open source UX portion. You can also make your own copy of TranslationController without forking and then extend BaseTransformableNode to add your own instead of the default.

**Comment by meetvora-ecosmob** [comment]
@dsternfeld7 Your solution is working perfectly. I wonder if there is any way to drag the object in the air, I mean without on any plane same like AR Stickers in Pixel's stock camera app. In that application, we can drag the object on the screen and even without surface detection that object will hover on the screen.
