### ISSUE TITLE
Some questions about 3D models

### ISSUE THREAD

**Issue by siny-yao** [google-ar/sceneform-android-sdk#366]
I have encountered some problems when I use it. There are few related materials on the Internet. I am asking questions here and I hope I can get answers.
1. How to import 3D models without using Google Sceneform Tools
2. Using the plugin to import a 3D model of type .fbx, losing the model action
3. Can I use the exported SFB directly without configuring gradle?

**Comment by bobekos** [comment]
1. Since Sceneform 1.5 you can create 3D models at runtime. Check the official documentation for this topic https://developers.google.com/ar/develop/java/sceneform/create-renderables.
2. Yes Sceneform does not support model animation at this time. You can animate the models over ObjectAnimator. Check this out: https://developers.google.com/ar/develop/java/sceneform/build-scene#top_of_page
3. Yes

**Comment by siny-yao** [comment]
Thank you for your answer and look forward to the more complete Sceneform.

**Comment by siny-yao** [comment]
> 1. Since Sceneform 1.5 you can create 3D models at runtime. Check the official documentation for this topic https://developers.google.com/ar/develop/java/sceneform/create-renderables.
> 2. Yes Sceneform does not support model animation at this time. You can animate the models over ObjectAnimator. Check this out: https://developers.google.com/ar/develop/java/sceneform/build-scene#top_of_page
> 3. Yes

Thanks for the answer, I tried it, there are a few doubts
1. I did not find a way to create renderable objects from 3D files in the ShapeFactory class.
2. How to bind the camera to Arfragment or ArSceneView to take a photo or video recording of the current scene.
3. I just want to add a model. I can't continue adding when the model exists. What should I do?

**Comment by claywilkinson** [comment]
1. To create renderable objects from 3D files (only glTF2 files are supported this way) see [Load 3D models at runtime](https://developers.google.com/ar/develop/java/sceneform/create-renderables#load_3d_models_at_runtime).

2. It is currently not possible to capture a video of a SceneView.  You can capture a photo image by using the [PixelCopy API](https://developer.android.com/reference/android/view/PixelCopy).  The [Sceneform Codelab](https://codelabs.developers.google.com/codelabs/sceneform-intro/index.html) shows the steps in detail (see Step 15).
3. I am not sure what you mean here?

**Comment by siny-yao** [comment]
Thank you for your answer, it helped me.
I hope to capture a video of SceneView in the future.

**Comment by siny-yao** [comment]
Sorry, bother you, I have found a way.
