### ISSUE TITLE
PlaneRenderer example not working

### ISSUE THREAD

**Issue by thomasbn94** [google-ar/sceneform-android-sdk#368]
Here [https://developers.google.com/ar/develop/java/sceneform/build-scene](url), there is an example of how to customize the plane renderer. It looks like this: 

        Texture.Sampler sampler =
                Texture.Sampler.builder()
                        .setMinMagFilter(Texture.Sampler.MagFilter.LINEAR)
                        .setWrapMode(Texture.Sampler.WrapMode.REPEAT)
                        .build();

        Texture.builder()
                .setSource(this, R.drawable.custom_texture)
                .setSampler(sampler)
                .build()
                .thenAccept(texture -> {
                    arSceneView
                            .getPlanerRenderer()
                            .getMaterial()
                            .setTexture(PlaneRenderer.MATERIAL_TEXTURE, customTexture);
                });

Some issues I found:
1. `setMinMagFilter()` is not public in the package. Perhaps you meant `setMinFilter()` ?
2. The second method invocation should be

        Texture.builder()
                .setSource(this, R.drawable.custom_texture)
                .setSampler(sampler)
                .build()
                .thenAccept(texture -> {
                    arSceneView
                            .getPlaneRenderer()
                            .getMaterial() // Returns a CompletableFuture
                            .thenAccept(
                                    material -> {
                                        material.setExternalTexture(PlaneRenderer.MATERIAL_TEXTURE, customTexture);
                                    }
                            );
                });
i think. 

By the way, does anyone know how `R.drawable.custom_texture` and `customTexture` look like?

**Comment by claywilkinson** [comment]
Thanks for pointing this out.    The R.drawable.custom_texture is the .png you want to use as the texture on the plane.  For example to test the code I just copied ic_launcher.png to custom_texture.png.

The correct code should look like:
```
   Texture.Sampler sampler =
            Texture.Sampler.builder()
                    .setMinFilter(Texture.Sampler.MinFilter.LINEAR)
                    .setWrapMode(Texture.Sampler.WrapMode.REPEAT)
                    .build();

    // R.drawable.custom_texture is a .png file in src/main/res/drawable
    Texture.builder()
            .setSource(this, R.drawable.custom_texture)
            .setSampler(sampler)
            .build()
            .thenAccept(texture -> {
              arSceneView.getPlaneRenderer()
                      .getMaterial().thenAccept(material ->
                      material.setTexture(PlaneRenderer.MATERIAL_TEXTURE, texture));
            });
```

**Comment by claywilkinson** [comment]
The documentation has been updated as well.
