### ISSUE TITLE
Navigation Arrow Direction

### ISSUE THREAD

**Issue by qiqims** [google-ar/sceneform-android-sdk#370]
I am trying to place multiple 3d arrows based on GPS locations and I am trying to get them all to point in the same direction, for example north, regardless of current device rotation or anything else.  I can place the arrow in the correct spot, but I cannot figure out how to have them all pointing in the correct direction.  When I run the app with the phone facing a different direction at startup the arrows will point in a different direction.  I am not trying to make something like a compass where it constantly is turning on the screen, just a fixed node. Do you have any resources that might be useful or any ideas of what I can try? @inio @jwmcglynn @gordonbrander

**Comment by strider1981** [comment]
Hi @qiqims how are you able to place arrows at a specific latlng? I am still trying to figure that out. Can you share your code snippet?
Thanks
