### ISSUE TITLE
RenderableSource apply custom material

### ISSUE THREAD

**Issue by bobekos** [google-ar/sceneform-android-sdk#373]
Hi,

since SceneForm 1.5 we got the option to import gltf models at runtime.
Is there a possibility to apply custom material reference to the renderable source?
As i can see you can manipulate only the scale and the recenter mode attributes.

**Comment by c0deminded** [comment]
Maybe this [issue](https://github.com/google-ar/sceneform-android-sdk/issues/157) can help you.

**Comment by c0deminded** [comment]
Sounds like a feature that needs to be added.
However, you can work around this issue if you download gltf on your phone , convert it to sfb with a standard material definition , and then do as above. Assign a custom material definition and maps that are used. Not the best way, but it should work.

**Comment by bobekos** [comment]
Hallo @c0deminded 

thanks for the response. But as far as I know there is no option to add (not modify) a new custom material at runtime. Or am I blind?

**Comment by bobekos** [comment]
@c0deminded Forget everything I said. Are you f!%&"§& kidding me? I overlooked the setMaterial method.
