### ISSUE TITLE
Adding child node to TransformableNode?

### ISSUE THREAD

**Issue by sarahthe** [google-ar/sceneform-android-sdk#374]
Hi,

I'm having trouble adding a child node to a TransformableNode. I have a project containing Augmented Images and Sceneform to render a 3D model when an image is tracked.

My goal is to render the 3D model as TransformableNode and add child nodes at specific locations, so as to superimpose an additional 3D model that is clickable (see image below).

My code creating the 3D model is as follows:

```
renderObject(arFragment, augmentedImage.createAnchor(augmentedImage.getCenterPose()), R.raw.earth);

...

private void renderObject(ArFragment fragment, Anchor anchor, int model) {
        ModelRenderable.builder()
                .setSource(this, model)
                .build()
                .thenAccept(renderable -> addNodeToScene(fragment, anchor, renderable))
                .exceptionally((throwable -> {
                    AlertDialog.Builder builder = new AlertDialog.Builder(this);
                    builder.setMessage(throwable.getMessage()).setTitle("Error!");
                    AlertDialog dialog = builder.create();
                    dialog.show();
                    return null;
                }));
}

private void addNodeToScene(ArFragment fragment, Anchor anchor, Renderable renderable) {
        AnchorNode anchorNode = new AnchorNode(anchor);
        TransformableNode node = new TransformableNode(fragment.getTransformationSystem());
        node.setRenderable(renderable);
        node.getScaleController().setMinScale(0.1f);
        node.getScaleController().setMaxScale(1.0f);
        node.setLocalScale(new Vector3(0.0f, 0.0f, 0.0f));
        node.setWorldRotation(Quaternion.axisAngle(new Vector3(-1.0f, -1.0f, 0.5f), 90));
        node.setParent(anchorNode);
        fragment.getArSceneView().getScene().addChild(anchorNode);
        node.select();
}
```

What I get is the tracked image and my 3D model. What I want is to show the info-model over a part of the model (see screenshot with added info-model below) and click it to get to another view.

![screenshot](https://user-images.githubusercontent.com/27763767/46957798-9ba9c100-d098-11e8-9d73-c7d4df6bad34.jpg)

How can I accomplish this?

**Comment by sarahthe** [comment]
Anyone?

**Comment by malik-at-work** [comment]
I'm not sure I understand the question, but generally if you want to add a dialog like function it may be a lot easier to implement it as ViewRenderable.

**Comment by sarahthe** [comment]
Well, I already implemented this now with a Node as a child of a TransformableNode.
My problem now is to find the position at which to display the child that must be relative to the parent's position.

My current implementation is as follows:
`
Node node = new Node();
renderable.setRenderPriority(0);
node.setParent(parent);
node.setRenderable(renderable);
Vector3 pos = Vector3.add(Vector3.add(parent.getWorldPosition(), parent.localToWorldPoint(parent.getDown())), parent.localToWorldPoint(parent.getForward()));
node.setLocalPosition(pos);
`

However, I did not find any documentation on the local coordinate system and the vectors from TransformableNodes at all. Could you explain, what the `getDown()` function or similar exactly return? Now I experimented with scales but I'm not sure why it is needed. You can see my current visualization below. With these, I think, I can describe a position adjacent to the parent model (in my case, front bottom center).

![screenshot_20181119-140649_museum ar xperience](https://user-images.githubusercontent.com/27763767/48709449-cb9f3380-ec05-11e8-9195-4309fe3138e7.jpg)

**Comment by sarahthe** [comment]
No, I want to set a position relative to the parent, e.g. half its width in front of it. For this, I need to know the width of the parent. What exactly do the vectors like `getForward()` describe? Can I use them to determine the child's position?

**Comment by malik-at-work** [comment]
In a local space [forward](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/math/Vector3#forward()) is the vector (0, 0, -1).  [getForward](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/Node#getForward())  Returns the direction vector (0. 0, -1) converted from local space to world space.  This means the rotation the node and the node parents is applied.

Forward is not the same as "in front of" for multiple reasons.  Forward describes the direction a node is facing.  In front of describes a relationship between two points and the camera.  To calculate a point in front of or behind another object, you must calculate a line going from the object to the camera and then select a point along that line.

**Comment by sarahthe** [comment]
Solved: Got the information I needed about the parent's sizing from its collision shape. I can get the size (or radius) from the collision shape and position the child relative to these values.

In case anyone else has a similar problem: In my example of the earth, the child model is to be placed at front top of parent (sphere collision shape). The following code does this:

```
Node node = new Node();
renderable.setRenderPriority(0);
node.setParent(parent);
node.setRenderable(renderable);
Vector3 pos;

if (parent.getCollisionShape() instanceof Box) {
    Box box = (Box) (parent.getCollisionShape());
    Vector3 size = box.getSize();
    pos = new Vector3(size.x * 0.5f, size.y * 1f, size.z * 0f);
} else {
    Sphere sphere = (Sphere) (parent.getCollisionShape());
    float diameter = sphere.getRadius() * 2;
    pos = new Vector3(diameter * 0.5f, diameter * 1f, diameter * 0f);
}

node.setLocalPosition(pos);
```

**Comment by claywilkinson** [comment]
@sarahthe  Thanks for posting your solution!
