### ISSUE TITLE
Can't produce Shadow

### ISSUE THREAD

**Issue by CranberryYam** [google-ar/sceneform-android-sdk#384]
I tried to cast the shadow of my object on a cube, but it doesn't work.
```
MaterialFactory.makeOpaqueWithColor(context, Color(android.graphics.Color.WHITE))
                .thenAccept { material ->
                    val size = Vector3(3f, 0.1f, 3f)
                    val center = Vector3(0f,-0.1f, 0f)
                    planeRender = ShapeFactory.makeCube(size, center, material)
                }

sNode.renderable = planeRender
 sNode.localPosition = Vector3(0.0f, 0.0f, 0.0f)

fNode.addChild(node)
 fNode.addChild(sNode)
```

**Comment by CranberryYam** [comment]
> Have you tried calling the method [setShadowCaster](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/rendering/Renderable#setShadowCaster(boolean)) with `true` after the creation?

I did. What do u think is the best practice of making shadow, create a cube underneath? Cause these's no shadow if no planes detected.

**Comment by malik-at-work** [comment]
I would expect renderable.setShadowReciever(true)  to have an object that can catch shadows.
