### ISSUE TITLE
fade mode layering wrong

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/sceneform-android-sdk#390]
When using the blend mode fade in the custom material for the background object, the layering is wrong for my scene, even when setting the render priority. 

When blend mode is set to transparent, the scene looks as shown in the screen shot. Just by changing the blend mode to fade, the text is rendered behind the background. Render priority for the background object is set to 0, for the other objects the default 4.

The background and the image object are a ShapeFactory cube with a custom material, the text is a ViewRenderable with background set to transparent in the layout.

![screenshot_20181023-122931_2](https://user-images.githubusercontent.com/231274/47355335-6701bf00-d6c1-11e8-9a18-845c0ea5ec9d.png)

**Comment by romainguy** [comment]
Is your background opaque or transparent?

**Comment by michaelvogt** [comment]
Seems my explanation was not good enough. 

I set the blend mode of the background to transparent, or opaque if you like, and all is fine. I set it to fade, and the text vanishes (the object is still in the scene, but he background is covering it). Whatever the reason, I don't see that I'm doing something wrong here. Something is different between these two modes, and it would be kind if this could be fixed.

**Comment by romainguy** [comment]
Thanks for the info. Is your background material lit or unlit? Could you paste your custom material here so I can try to reproduce the issue?

**Comment by michaelvogt** [comment]
Sure, happy to provide any info you'd need to fix this.

The material for the background can be as simple as the one below. 

```
material {
    name: "Custom material",
    parameters: [
    ],
    requires: [
        "position",
        "uv0"
    ],
    blending : "transparent",
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);

      }
}
```

**Comment by michaelvogt** [comment]
Just tried if the effect is the same when the background is unlit and blend is set to fade. And yes, the text is also covered by the background.

A workaround might be acceptable for a while, but I clearly want to have a problem fixed, and not going from workaround to workaround because of SceneForm.

The problem exists also with this empty material function. So it doesn't have any influence. 

As I said, I just change the blend mode of the custom material. One time the render is as expected, the other time it isn't. The only thing that changes is the value of the blend mode. When there is anything the application can do wrong that this problem arises, please let me know. 

Important might be, as I wrote above, the custom material is added to a ShapeRenderable Cube, and the text is a ViewRenderable.

Just for completeness, here is how it looks like when I display the background with half the size and the material as provided above, blend mode set to fade and unlit. The text should be at least in front of the background. Yes, as before the renderpriority was set for the background, how far the text is positioned in front of the background doesn't matter
![screenshot_20181023-175655_2](https://user-images.githubusercontent.com/231274/47374125-7ac31a80-d6ed-11e8-9b23-f72360cd0576.png)

**Comment by romainguy** [comment]
I definitely want to fix this issue for you, I'm trying to understand what's happening. Note that priority 0 is the highest priority, priority 4 is lower (it's also the default priority).

**Comment by michaelvogt** [comment]
I will setup a Hello Sceneform for you tomorrow that shows the problem. Hope this helps to find the problem.

**Comment by michaelvogt** [comment]
Here you are. Copying the source below into the HelloSceneformActivity, should show the background and the text floating on top of it - which it doesn't right now. The 3D model used is in the zip.

Do you see how there are already 3 workarounds for Sceneform / ARCore behaviours?

```
          // background
          ModelRenderable.builder()
              .setSource(getApplicationContext(), R.raw.default_model)
              .build()
              .thenAccept(temp -> {
                // TODO: Hack - fix when custom material can be created #196
                Material material = temp.getMaterial();

                Renderable backgroundRenderable = ShapeFactory.makeCube(
                    new Vector3(0.645f, 0.005f, 0.432f),
                    Vector3.zero(), material);

                // Needs to be set to help SceneForm get the layering right
                // https://github.com/google-ar/sceneform-android-sdk/issues/285#issuecomment-420730274
                backgroundRenderable.setRenderPriority(0);

                Node backgroundNode = new Node();
                backgroundNode.setParent(anchorNode);

                // Needs to be set to help SceneForm / ARCore get the orientation right
                // https://github.com/google-ar/sceneform-android-sdk/issues/286
                backgroundNode.setLookDirection(Vector3.up(), anchorNode.getUp());
                backgroundNode.setRenderable(backgroundRenderable);

                // text
                ViewRenderable.builder()
                    .setView(getApplicationContext(), R.layout.view_text)
                    .build()
                    .thenAccept(textRenderable -> {
                      textRenderable.setSizer(view -> new Vector3(0.445f, 0.572f, 0.2f));
                      textRenderable.setShadowCaster(false);

                      Node textNode = new Node();
                      textNode.setParent(backgroundNode);
                      textNode.setLocalPosition(new Vector3(0.106f, 0.1f, 0.32f));
                      textNode.setLocalRotation(new Quaternion(new Vector3(-1.0f, 0.0f, 0.0f), 90.0f));
                      textNode.setRenderable(textRenderable);

                      TextView textView = textRenderable.getView().findViewById(R.id.view_text);
                      textView.setText("<h1>宗岡家</h1>\n" +
                          "      <h2>大田市指定史跡、大森代官所役人遺宅</h2>\n" +
                          "      <p>宗岡は、戦国時代毛利輝元の「銀山六人衆」として知られ、諸役の徴収方を担いました。江戸時代に入ると、奉行大久保長安に召し抱えられ、以後銀山附役人として銀山支配を支えていくことになります。\n" +
                          "寛政二年（一七九〇）に、六代目喜三兵衛は、銀山附役人の職を離れ、川本村（現在の邑智郡川本町）に移りますが、文政六年（一八二三）に八代目長藏が銀山附同心として復帰し遠縁であった地役人頭の阿部家（阿部半蔵光格）から隣地にあたる現在の屋敷を譲り受けました。\n" +
                          "現存する主屋・離れ・土蔵は、江戸時代末期の家相図に描かれた間取りと一致し、銀山附同心の屋敷構えを残す住居として貴重で、平成五年に大田市指定史跡となりました。現在の屋敷は平成二五年度から二九年度の修理工事時の調査と家相図をもとに整備されたものです。\n" +
                          "    </p>");

                      Log.i(TAG, "TextNode successfully created");
                    })
                    .exceptionally(throwable -> {
                      Log.e(TAG, "Could not create TextRenderable", throwable);
                      return null;
                    });
              })
              .exceptionally(throwable -> {
                Log.d(TAG, "Could not create model: ", throwable);
                return null;
              });
```

[default_model.zip](https://github.com/google-ar/sceneform-android-sdk/files/2509734/default_model.zip)

**Comment by romainguy** [comment]
Thanks!

**Comment by michaelvogt** [comment]
Glad to hear that it wasn't me doing something wrong. Looking forward to the fix.

**Comment by romainguy** [comment]
The bug has been fixed on the Filament side.

**Comment by michaelvogt** [comment]
@abramyan Just closing without a comment, and without a chance to check if the problem is actually fixed feels - lets say - strange.

**Comment by romainguy** [comment]
The fix is coming to Sceneform 1.7.

**Comment by abramyan** [comment]
@michaelvogt sorry about that. Can you please verify with 1.7?

**Comment by michaelvogt** [comment]
Well, yes, the layering of the models worked with a simple sample. Can't test right now with the complete app.

But, please have a look at #535
