### ISSUE TITLE
Blue lines drawn at the top and right borders of SceneView

### ISSUE THREAD

**Issue by ClementTroesch** [google-ar/sceneform-android-sdk#394]
Hi,

I'm working on an app that uses sceneform to display a simple 3D model (no AR involved). 

I've got two `SceneView` instances on top of each other: one for the model and one to display an orientation marker at the bottom right corner of the main view.

<img src="https://user-images.githubusercontent.com/2217369/47440757-1c5e7080-d7af-11e8-9907-eaa7b77cb709.png" width="200">

My problem is that blue lines are drawn at the top and right borders of each view:

<img src="https://user-images.githubusercontent.com/2217369/47441419-64ca5e00-d7b0-11e8-8921-6dd4b9edea62.png" width="300">

Am I doing anything wrong and is there a way to get rid of these blue lines ?

Thanks,
Clément

**Comment by romainguy** [comment]
Thank you for the report. We recently fixed this issue in the renderer, it will be part of a future update of Sceneform. More details about the bug and fix here: https://github.com/google/filament/pull/414

You can work around this problem temporarily by changing the size of the scene view.
