### ISSUE TITLE
sfb file is too big for our models, around 10MB

### ISSUE THREAD

**Issue by CranberryYam** [google-ar/sceneform-android-sdk#395]
For other files of one model, the total size is 4 MB. However, the sfb file of this model is around 10MB. Do we really need sfb file? Our app downloads the model in realtime, so we really concern about the size of models.

**Comment by stanlo** [comment]
Which other formats are you comparing to? The SFB is not file compressed, so if you'd like, you can try zipping it. Otherwise it has the necessary geometry and images for the model all in one file, so you might be able to try reducing the image or geometry resolution?
