### ISSUE TITLE
chroma_key_material without color filter

### ISSUE THREAD

**Issue by bobekos** [google-ar/sceneform-android-sdk#400]
Hi,

i try to create a material like the chroma_key_material from the video sample but without the color filter functionality. I want to stream only a video on a plane.  I have tried the following but without success. The video casts shadows on itself from one side and is too bright. Any ideas?

```
material {
    name : "video material",
    parameters : [
        {
           type : samplerExternal,
           name : texture
        }
    ],
    requires : [
        uv0
    ],
    shadingModel : lit,
    blending : opaque,
    doubleSided : true
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor = texture(materialParams_texture, getUV0());
    }
}
```

**Comment by romainguy** [comment]
You should make the material unlit if you don't want shadows/lighting. For the brightness problem it's because you need to convert from srgb to linear space. Simply square baseColor.rgb to achieve this easily: `material.baseColor.rgb *= material.baseColor.rgb`

**Comment by bobekos** [comment]
@romainguy 
Perfect! Works like a charm. Thank you very much.
