### ISSUE TITLE
How to set visibility plane detection ?

### ISSUE THREAD

**Issue by nagesh1044** [google-ar/sceneform-android-sdk#403]
Hi,

I want to hide the visibility of plane detection like white dots?

Please let us know how to do this?

**Comment by bobekos** [comment]
Just set:
`arSceneView.getPlaneRenderer().setVisible(false)`

**Comment by nagesh1044** [comment]
> Just call:
> `arSceneView.getPlaneRenderer().setVisible(false)`

Thanks . It is working.

**Comment by nagesh1044** [comment]
How to add numbers on top of Anchor node . 


![screen_shot](https://user-images.githubusercontent.com/3814766/48179936-7c285000-e347-11e8-9fcc-d506561291ce.png)

**Comment by nagesh1044** [comment]
In Android Ar Core how to restrict dragging of objects(Anchor nodes) from one location to another location?

**Comment by nagesh1044** [comment]
In Android Ar Core how to restrict dragging of objects(Anchor nodes) from one location to another location?
