### ISSUE TITLE
Replace node renderable ( same rotation, position and scale ) with another node renderable

### ISSUE THREAD

**Issue by AndroidRocket** [google-ar/sceneform-android-sdk#405]
Hello,
I am new to sceneform sdk . I have added one Transformable Node , then i applied some rotation , scalling and changed its position also. Now on click of button i need to place second node with same rotation , scalling and position. For that what  i did is: 

Node nodeTwo = new Node();
nodeTwo.setLocalPosition(nodeOne);
nodeTwo.setLocalRotation(nodeOne);
nodeTwo.setLocalScale(nodeOne);
nodeTwo.setRenderable(renderable);

I have also tried with setWorldPosition() , setWorldRotation(). But nothing works , second node got placed on fix position and rotation.Can I do something to 'fix' this?

**Comment by AndroidRocket** [comment]
@malik-at-work 

Please help me find any solution on this.

**Comment by AndroidRocket** [comment]
it was just a silly mistake. I was adding one Base below Anchor node as parent which is the cause of problem.Resolved at below link: 

[see here](https://stackoverflow.com/questions/53058940/replace-node-renderable-same-rotation-position-and-scale-with-another-node)

**Comment by malik-at-work** [comment]
Great that you were able to solve it!
