### ISSUE TITLE
arFragment.planeDiscoveryController.hide() not working

### ISSUE THREAD

**Issue by vntodorova** [google-ar/sceneform-android-sdk#414]
What I'm trying to do is hide the hand motion view from the screen while my AR model is loading (because it's pretty huge), and to display it back again, after the model is loaded. 

What I'm currently doing is call  `arFragment.planeDiscoveryController.hide()` , but after that the animation is still there. 
When I call  `arFragment.planeDiscoveryController.setInstructionView(null)`  the hand disappears, but when I try to show it again, using 
```
val handMotionView = HandMotionView(context)
arFragment.planeDiscoveryController.setInstructionView(handMotionView) 
arFragment.planeDiscoveryController.show() 
```
it's not appearing again. I would expect it to work with just hide() and show(). Am I doing something wrong or I just completely don't understand what's going on?

**Comment by bobekos** [comment]
Where did you try to hide the controller? When you look in the ArBaseFragment onResume method you will see that the controller is calling his show() function. So to hide the view you must call hide after onResume.

**Comment by malik-at-work** [comment]
planeDiscoveryController.show()  only does a call to setVisibility(View.VISIBLE) on the view,
Similarly hide is just a call to setVisibility(View.GONE) as mentioned above ArFragmentBase makes calls to show and hide.

**Comment by vntodorova** [comment]
@bobekos Calling it in onResume worked! I was calling it before that. Thanks 👍
