### ISSUE TITLE
Android Studio 3.1 Support

### ISSUE THREAD

**Issue by azamsharp** [google-ar/sceneform-android-sdk#42]
I downloaded Android Studio 3.1 but I still cannot find any libraries related to SceneForm. Am I missing something?

**Comment by jagsrajput21** [comment]
@azamsharp You have to install SceneForm plugin in Android Studio. 

Go to Preferences-> Plugins -> Browse Repositiories -> Google Sceneform Tools.

**Comment by claywilkinson** [comment]
Android Studio projects use Gradle to resolve the library dependencies for a project.  If you open one of the sample projects in Android Studio when it builds the project, it will download the client libraries needed.


A quick start guide for Sceneform is at: https://developers.google.com/ar/develop/java/sceneform/

If you are new to developing for Android or using Android Studio, you might want to check out getting started resources for Android Studio such as:
* https://developer.android.com/guide/
*  [YouTube video](https://youtu.be/Z98hXV9GmzY)
*  [Udacity's Android Basics] (https://www.udacity.com/course/android-basics-user-interface--ud834)
