### ISSUE TITLE
Rotate around model center

### ISSUE THREAD

**Issue by bobekos** [google-ar/sceneform-android-sdk#422]
Hi,

how can i rotate a model around it's center when the recenter:attribute is set to false?

Any help would be appreciated.

**Comment by bobekos** [comment]
Any suggestions? I have following scenario:

1. AugmentedImage Detection
2. This Model ([link](https://we.tl/t-DRgO6Wchd8)) ist just a simple plane where i add some textures later
3. The SFA recenter:attribute is set to false because i want to placed the model at its origin position
4. Now i want to rotate the plane to the camera on each frame update. The example from the docs (see below) is not working because it's rotate the model not around the center of the "plane" .

```
@Override
public void onUpdate(FrameTime frameTime) {
  Vector3 cameraPosition = getScene().getCamera().getWorldPosition();
  Vector3 cardPosition = infoCard.getWorldPosition();
  Vector3 direction = Vector3.subtract(cameraPosition, cardPosition);
  Quaternion lookRotation = Quaternion.lookRotation(direction, Vector3.up());
  infoCard.setWorldRotation(lookRotation);
}
```

**Comment by ivstka95** [comment]
@bobekos hi, have you resolved this? i need help too, will appreciate if you share any progress

**Comment by bobekos** [comment]
Yes, I was able to solve it. Example below:
```
val renderable = ... //your renderable

val originCenter = (renderable.collisionShape as Box).center //get the origin center of the object

val parentNode = Node() //wrapper node
parentNode.localPosition = originCenter

val renderableNode = Node()
renderableNode.setParent(parentNode)
renderableNode.localPosition = originCenter.negated()
```
Now you can rotate the parentNode and the model rotate around ts center

**Comment by ivstka95** [comment]
@bobekos already solved it the same way by myself. thank you for reply, appreciate it!
