### ISSUE TITLE
[ help!!! ]Can I remove the white circle at the model bottom?

### ISSUE THREAD

**Issue by HoneyHanNing** [google-ar/sceneform-android-sdk#423]
As for the title, I am a beginner of Android. When running github's sceneform-sample, I found that when the model appeared on the screen, a white circle would be followed under the model. What method can I use to remove the white circle at the bottom?

Thank you very much for your help！~
![_20181109103819](https://user-images.githubusercontent.com/35944776/48239893-9c214780-e40b-11e8-83ba-535c2730154b.png)

**Comment by siny-yao** [comment]
This is part of the andy model, if it is your own model will not appear

**Comment by dementia2029** [comment]
```
public class MainActivity extends AppCompatActivity{
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        buttonRemove = findViewById(R.id.remove);
        ApiUtils.updateSOService(this);

        fragment = (ArFragment) getSupportFragmentManager().findFragmentById(R.id.sceneform_fragment);
        if (fragment != null) {
            fragment.getTransformationSystem().setSelectionVisualizer(new CustomVisualizer());
        }
    }

public class CustomVisualizer implements SelectionVisualizer {
    @Override
    public void applySelectionVisual(BaseTransformableNode node) {}
     @Override
    public void removeSelectionVisual(BaseTransformableNode node) {}
}
```

**Comment by HoneyHanNing** [comment]
> @HoneyHanNing
> 
> ```
> public class MainActivity extends AppCompatActivity{
>     @Override
>     protected void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
>         setContentView(R.layout.activity_main);
>         fragment = (ArFragment) getSupportFragmentManager().findFragmentById(R.id.sceneform_fragment);
>         if (fragment != null) {
>             fragment.getTransformationSystem().setSelectionVisualizer(new CustomVisualizer());
>         }
>     }
> 
> public class CustomVisualizer implements SelectionVisualizer {
>     @Override
>     public void applySelectionVisual(BaseTransformableNode node) {}
>     @Override
>     public void removeSelectionVisual(BaseTransformableNode node) {}
> }
> ```

Thank you for your help, I will try！~

**Comment by HoneyHanNing** [comment]
@dementia2029 Thank you for your help, I will try！~
