### ISSUE TITLE
How I can set repeated texture on an object in Android ArCore Sceneform API?

### ISSUE THREAD

**Issue by andrewgrow** [google-ar/sceneform-android-sdk#437]
I have successfully made a line between two vectors in the AR Scene.

My code:

```
private void addLineBetweenPoints(Scene scene, Vector3 from, Vector3 to) {
        // prepare an anchor position
        Quaternion camQ = scene.getCamera().getWorldRotation();
        float[] f1 = new float[]{to.x, to.y, to.z};
        float[] f2 = new float[]{camQ.x, camQ.y, camQ.z, camQ.w};
        Pose anchorPose = new Pose(f1, f2);

        // make an ARCore Anchor
        Anchor anchor = mCallback.getSession().createAnchor(anchorPose);
        // Node that is automatically positioned in world space based on the ARCore Anchor.
        AnchorNode anchorNode = new AnchorNode(anchor);
        anchorNode.setParent(scene);

        // Compute a line's length
        float lineLength = Vector3.subtract(from, to).length();

        // Prepare a sampler
        Texture.Sampler sampler = Texture.Sampler.builder()
                .setMinFilter(Texture.Sampler.MinFilter.LINEAR_MIPMAP_LINEAR)
                .setMagFilter(Texture.Sampler.MagFilter.LINEAR)
                .setWrapModeR(Texture.Sampler.WrapMode.REPEAT)
                .setWrapModeS(Texture.Sampler.WrapMode.REPEAT)
                .setWrapModeT(Texture.Sampler.WrapMode.REPEAT)
                .build();

        // 1. Make a texture
        Texture.builder()
                .setSource(() -> getContext().getAssets().open("textures/aim_line.png"))
                .setSampler(sampler)
                .build().thenAccept(texture -> {
                    // 2. make a material by the texture
                    MaterialFactory.makeTransparentWithTexture(getContext(), texture)
                        .thenAccept(material -> {
                            // 3. make a model by the material
                            ModelRenderable model = ShapeFactory.makeCylinder(0.0025f, lineLength,
                                    new Vector3(0f, lineLength / 2, 0f), material);
                            model.setShadowReceiver(false);
                            model.setShadowCaster(false);

                            // make node
                            Node node = new Node();
                            node.setRenderable(model);
                            node.setParent(anchorNode);

                            // set rotation
                            final Vector3 difference = Vector3.subtract(to, from);
                            final Vector3 directionFromTopToBottom = difference.normalized();
                            final Quaternion rotationFromAToB =
                                    Quaternion.lookRotation(directionFromTopToBottom, Vector3.up());
                            node.setWorldRotation(Quaternion.multiply(rotationFromAToB,
                                    Quaternion.axisAngle(new Vector3(1.0f, 0.0f, 0.0f), 90)));
                    });
        });
    }
```

It works perfectly, but I have a mistake texture. In the file "textures/aim_line.png" contains PNG: (the line's half is transparent the other half is orange.)

![aim_line](https://user-images.githubusercontent.com/8538536/48919923-674ad100-ee9e-11e8-93e5-44d0156a9bf3.png)

My current result:

![current_result](https://user-images.githubusercontent.com/8538536/48919929-703ba280-ee9e-11e8-8234-3161ec8cdbd2.png)

But I expected next result:

expected result
![expected_result](https://user-images.githubusercontent.com/8538536/48919935-76318380-ee9e-11e8-8244-4d1a6e6884b9.png)

So, I have use the Sampler where was wrote "WrapMode.REPEAT" but the texture does not repeat, only stretched.

How I can set repeated texture on an object in Android ArCore Sceneform API?

**Comment by claywilkinson** [comment]
I asked around and the cylinder is working as designed.  To repeat the texture you need to either model your own cylinder, including the repeating pattern, or use a custom material.  I posted how to use the custom material on your [Stackoverflow question](https://stackoverflow.com/questions/53437128/how-i-can-set-repeated-texture-on-an-object-in-android-arcore-sceneform-api)

**Comment by andrewgrow** [comment]
> I asked around and the cylinder is working as designed. To repeat the texture you need to either model your own cylinder, including the repeating pattern, or use a custom material. I posted how to use the custom material on your [Stackoverflow question](https://stackoverflow.com/questions/53437128/how-i-can-set-repeated-texture-on-an-object-in-android-arcore-sceneform-api).

Thanks a lot for your help, sir!

**Comment by mpetlyuk** [comment]
How can I add animation for the texture to simulate endless moving animation?

**Comment by apetoman** [comment]
> 我四处询问，气缸按设计工作。要重复纹理，您需要为自己的圆柱体建模，包括重复模式，或使用自定义材质。我发布了如何在[Stackoverflow问题](https://stackoverflow.com/questions/53437128/how-i-can-
--------------------------------------------------
set-repeated-texture-on-an-object-in-android-arcore-sceneform-api)上使用自定义材料。
I'm so sorry. The material I got according to your method is black. There is no duplicate texture

**Comment by apetoman** [comment]
@claywilkinson 
Excuse me, I can draw the line segment according to your method, but it's all black. Can you help me?
------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/34733391/54262755-014b9c00-45aa-11e9- 




------------------------------------------------------------------------
        ModelRenderable.builder().setSource(this@ArDrawActivity, R.raw.yuanquan).build().thenAccept {

            repeatingMaterial = it.material
        }
------------------------------------------------------------------------
     fun drawLinTest(sta: Node, stop: Node) {



        val firstWorldPosition = sta.worldPosition
        val secondWorldPosition = stop.worldPosition


        val lineLength = Vector3.subtract(firstWorldPosition, secondWorldPosition).length()
        var lengthCM = lineLength * 100



        repeatingMaterial.setFloat("repeat_x", lengthCM/10)
        repeatingMaterial.setFloat("repeat_y", lengthCM/10)
        // val lineMode = ShapeFactory.makeCylinder(0.0025f, difference.length(), Vector3(0f, 0f, 0f), material)

        var model = ShapeFactory.makeCylinder(0.0025f, lineLength, Vector3(0f, 0f, 0f), repeatingMaterial)

        model.isShadowReceiver = false
        model.isShadowCaster = false


        val difference = Vector3.subtract(firstWorldPosition, secondWorldPosition)
       
        val directionFromTopToBottom = difference.normalized()
        val rotationFromAToB = Quaternion.lookRotation(directionFromTopToBottom, Vector3.up())

        val lineNode = Node()

        lineNode.renderable = model

        lineNode.setParent(arSceneView.scene)

        lineNode.worldPosition = Vector3.add(firstWorldPosition, secondWorldPosition).scaled(0.5f)

        lineNode.worldRotation = Quaternion.multiply(rotationFromAToB, Quaternion.axisAngle(Vector3(1.0f, 0.0f, 0.0f), 90f))
    }
