### ISSUE TITLE
Relative Pivot position support for GLTF

### ISSUE THREAD

**Issue by khonakr** [google-ar/sceneform-android-sdk#44]
We have to manually set the pivot location for all meshes in GLTFs, to be the origin because their relative transforms are not being respected by Sceneform.
As seen below, everything that was displaced relative to each other is just put either at their "zero" positions or somewhere wrong.

Incorrect:
![screen shot 2018-05-25 at 2 11 25 pm](https://user-images.githubusercontent.com/3877104/40559814-fc5fed32-6025-11e8-945a-9e24bf4bd156.png)

Correct: (After manual change in 3DS Max)
![screen shot 2018-05-25 at 2 15 35 pm](https://user-images.githubusercontent.com/3877104/40559977-91a835ac-6026-11e8-8da1-fac1350484c4.png)

**Comment by tpsiaki** [comment]
@khonakr - Thanks for the report and the workaround.  This will be fixed in our next release.

**Comment by tpsiaki** [comment]
This is fixed in versions 1.3+ of Sceneform.
