### ISSUE TITLE
Download .sfb and .obj files from cloud and load the model runtime?

### ISSUE THREAD

**Issue by yjoo9317** [google-ar/sceneform-android-sdk#441]
The requirement that I have is 
- need to download all 3d model assets from the cloud (Not bundled with APK.)

If I am using obj file (not glTF or glb), then I need to convert to sfb and load the model.
Seems like sfb holds the reference to the obj file in order to render the model and
that reference probably would be generated when we convert the obj file via the plugin tool.

What we want to do is that convert several obj files to sfb files and zip them up and put it into cloud.
Then later the app at its first run  will try to download the zip file and unzip into local directory.

Then can we load the model?

**Comment by bobekos** [comment]
Sure you need only the sfb file. The sfb has no reference to the original model. The sfb contains all needed data to render the object like (meshes, textures etc.).

**Comment by yjoo9317** [comment]
Thanks. Bobek..
Ok then, somehow it didn't work for me when I just tried to use .sfb file
only.
I will try again later.

**Comment by ishaang10** [comment]
is your issue fixed??
