### ISSUE TITLE
Sceneform, Apply custom Material to a RenderableDefinition.

### ISSUE THREAD

**Issue by RGregat** [google-ar/sceneform-android-sdk#445]
I found several sites how to set up a custom material definition to a sfa-file, but i have not found a way to apply it to a RenderableDefinition. So in general to use the custom material to a geometry that is created just programmatically. The reason behind is, to have some more control about the shaders. Actually I want to add a outline to my programmatically created models.

**Comment by RGregat** [comment]
Maybe the only way is to create a fake model, attach the custom material, load it and than use this material for my programmatically created mesh. Does this approach sounds reasonable?

**Comment by romainguy** [comment]
This is the way it's currently done yes. Just use a single triangle as the fake model for instance.

**Comment by RGregat** [comment]
Ok cool, I guess in that case my question is answered!
