### ISSUE TITLE
Issue with lighting in object created with RenderableDefinition

### ISSUE THREAD

**Issue by EdwinMurari** [google-ar/sceneform-android-sdk#446]
There is a weird effect with the illumination of an object created using RenderableDefinition. I created a plane using the RenderableDefinition and added a point light (andyrenderable) in front of it.
![screenshot_20181204-141156](https://user-images.githubusercontent.com/8147010/49417453-e5c63d80-f7d1-11e8-8031-4bc78134da30.png)

**Comment by romainguy** [comment]
Could you please share your original model as well as the .sfa please?

**Comment by EdwinMurari** [comment]
> Could you please share your original model as well as the .sfa please?

Hey,
Thank you for your response. I don't have any original model or .sfa, I built it using the vertex builder.
Here is the code for the plane generated.
`		Vector3 extents = this.size.scaled(0.5f);

        Vertex.UvCoordinate uv01 = new Vertex.UvCoordinate(-extents.x + 0.5f, extents.y + 0.5f);
        Vertex.UvCoordinate uv11 = new Vertex.UvCoordinate(extents.x + 0.5f, extents.y + 0.5f);
        Vertex.UvCoordinate uv10 = new Vertex.UvCoordinate(extents.x + 0.5f, -extents.y + 0.5f);
        Vertex.UvCoordinate uv00 = new Vertex.UvCoordinate(-extents.x + 0.5f, -extents.y + 0.5f);

        ArrayList<Vector3> positions = new ArrayList<>();

        // Positions
        positions.add(Vector3.add(center, new Vector3(0, extents.y, -extents.x)));
        positions.add(Vector3.add(center, new Vector3(0, extents.y, extents.x)));
        positions.add(Vector3.add(center, new Vector3(0, -extents.y, extents.x)));
        positions.add(Vector3.add(center, new Vector3(0, -extents.y, -extents.x)));

        // Vertices
        vertices.add(Vertex.builder().setPosition(positions.get(0)).setNormal(back).setUvCoordinate(uv01).build());
        vertices.add(Vertex.builder().setPosition(positions.get(1)).setNormal(back).setUvCoordinate(uv11).build());
        vertices.add(Vertex.builder().setPosition(positions.get(2)).setNormal(back).setUvCoordinate(uv10).build());
        vertices.add(Vertex.builder().setPosition(positions.get(3)).setNormal(back).setUvCoordinate(uv00).build());

        ArrayList<Integer> triangleIndices = new ArrayList<>(Arrays.asList(
                3, 1, 0, 3, 2, 1,
                3, 0, 1, 3, 1, 2

        ));

        submeshes.add(RenderableDefinition.Submesh.builder().setTriangleIndices(triangleIndices).setMaterial(material).build());
			
        RenderableDefinition renderableDefinition =
                RenderableDefinition.builder()
                        .setVertices(vertices)
                        .setSubmeshes(submeshes)
                        .build();

        ModelRenderable.builder().setSource(renderableDefinition)
                .build()
                .thenAccept(
                        modelRenderable -> {
							return modelRenderable;
                        }
                );`

**Comment by romainguy** [comment]
Looks like you are trying to create a double-sided plane? It's a little weird: you are creating front and back faces with the same normals. What are you trying to achieve here?

**Comment by EdwinMurari** [comment]
> Looks like you are trying to create a double-sided plane? It's a little weird: you are creating front and back faces with the same normals. What are you trying to achieve here?

I am trying to create a plane which is visible from both the sides.
I found that the issue was with the normal map, it was set as back, I changed it to Vector3.left() and now it works fine.
Thank you

**Comment by romainguy** [comment]
To create a double sided plane just create one quad and use a double-sided material. That's what it's for :)

**Comment by EdwinMurari** [comment]
> o create a double sided plane just create one quad and use a double-sided

Thank you for the info, I will look into it. Thanks a lot for your help.
