### ISSUE TITLE
What is optimal icon polygon count for ARCore 3D objects

### ISSUE THREAD

**Issue by rramprasad** [google-ar/sceneform-android-sdk#45]
As a Android developer, what are the specifications/requirements I need to provide for my 3D designer. I got following queries from 3D designer to fix issue #37. 

1) What is optimal icon polygon count for ARCore 3D objects? 
2) Is it best to use texture based ‘Normal Map’ system to create the embossed look?

What are best practices for 3D assets? Is it any specifications available for ARCore?

**Comment by malik-at-work** [comment]
This question can't be answered simply. It depends a lot on what phone you are on, how many objects you are showing as well as the nature and purpose of object as well.

General guidance we can give includes:
* Use as few polys as possible while your assets still look good.
* Small triangles are relatively expensive
* Some apps use budgets like 5K per object and <100K per scene...but a simple budget probably isn't enough guidance.
* Consider if the object is intended to be used in the foreground or the background.
* Consider if the object has features that a user is likely to really care about that you can't skimp on.
* Is the object the main thing the user sees/interacts with?
* Is decoration on some other object?
* All of these factors may impact any budget you create.

Normal Mapping: We have a lighting and shading system in Sceneform and many more features related to to lighting are under consideration.  Normal mapping is critical to any advanced lighting features.
