### ISSUE TITLE
Is there a way to know when plane is detected?

### ISSUE THREAD

**Issue by EdwinMurari** [google-ar/sceneform-android-sdk#457]
Is there some method called onPlaneDetected or something similar?
I would like to do something as soon as a plane is detected.

**Comment by ilamaheshwari** [comment]
make a PointDrawable class here - 

public class PointerDrawable extends Drawable {
    private final Paint paint = new Paint();
    private boolean enabled;
    @Override
    public void draw(@NonNull Canvas canvas) {
        float cx = canvas.getWidth()/2;
        float cy = canvas.getHeight()/2;
        if (enabled) {
            paint.setColor(Color.GREEN);
            canvas.drawCircle(cx, cy, 10, paint);
        } else {
            paint.setColor(Color.GRAY);
            canvas.drawText("X", cx, cy, paint);
        }
    }
    public boolean isEnabled() {
        return enabled;
    }
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    @Override
    public void setAlpha(int alpha) {
    }
    @Override
    public void setColorFilter(@Nullable ColorFilter colorFilter) {
    }
    @SuppressLint("WrongConstant")
    @Override
    public int getOpacity() {
        return 0;
    }
}

and in MainActivity Add this code - 
in onCreate -  fragment.getArSceneView().getScene().addOnUpdateListener(frameTime -> {
    fragment.onUpdate(frameTime);
    onUpdate();
    });

now in rest Mainactivity add these methods - 
private void onUpdate() {
 boolean trackingChanged = updateTracking();
 View contentView = findViewById(android.R.id.content);
 if (trackingChanged) {
   if (isTracking) {
     contentView.getOverlay().add(pointer);
   } else {
     contentView.getOverlay().remove(pointer);
   }
   contentView.invalidate();
 }

 if (isTracking) {
   boolean hitTestChanged = updateHitTest();
   if (hitTestChanged) {
     pointer.setEnabled(isHitting);
     contentView.invalidate();
   }
 }
}
      
private boolean updateTracking() {
 Frame frame = fragment.getArSceneView().getArFrame();
 boolean wasTracking = isTracking;
 isTracking = frame != null &&
              frame.getCamera().getTrackingState() == TrackingState.TRACKING;
 return isTracking != wasTracking;
}

private boolean updateHitTest() {
 Frame frame = fragment.getArSceneView().getArFrame();
 android.graphics.Point pt = getScreenCenter();
 List<HitResult> hits;
 boolean wasHitting = isHitting;
 isHitting = false;
 if (frame != null) {
   hits = frame.hitTest(pt.x, pt.y);
   for (HitResult hit : hits) {
     Trackable trackable = hit.getTrackable();
     if (trackable instanceof Plane &&
             ((Plane) trackable).isPoseInPolygon(hit.getHitPose())) {
       isHitting = true;
       break;
     }
   }
 }
 return wasHitting != isHitting;
}

**Comment by EdwinMurari** [comment]
> etTrackingState() == TrackingState.TRACKING;
> return isTracking != wasTracking;

I am looking to run a method as soon as a plane is detected, for example, enable a button to place a node as soon as it finds a plane.
But this kinda help, thank you for your effort.
