### ISSUE TITLE
How to get hitNode from screen point?

### ISSUE THREAD

**Issue by EdwinMurari** [google-ar/sceneform-android-sdk#458]
How can I get the node hit  from a screen point like what onPeekTouch does?

**Comment by claywilkinson** [comment]
You can use [Scene.hitTest(motionEvent)](https://developers.google.com/ar/reference/java/sceneform/reference/com/google/ar/sceneform/Scene#hitTest(android.view.MotionEvent)) to perform a hittest based on screen coordinates.
