### ISSUE TITLE
ARCore Drawing a Line with Color Switcher

### ISSUE THREAD

**Issue by shak98** [google-ar/sceneform-android-sdk#459]
Dear experts,

We’re trying to add a color switcher to this project: https://experiments.withgoogle.com/arcore-drawing

How is this possible? Can you guide us, please? 

Thank you,
Shak

**Comment by claywilkinson** [comment]
There is a similar project that uses Sceneform to draw (but does not use Cloud Anchors) which has a color picker.  You might want to check that one out: 
https://github.com/googlesamples/sceneform-samples/tree/master/drawing
