### ISSUE TITLE
Is there a way to get world position or proximity in a scene?

### ISSUE THREAD

**Issue by yashvv** [google-ar/sceneform-android-sdk#460]
For example if there are multiple objects(A, B, C) in a scene I am trying to change the color or material of object A when I am close to it or looking at it. If I can get the world position then I will be able to calculate the proximity to the object.

**Comment by claywilkinson** [comment]
Yes you can use the world position of the camera and the world position of each object to get the distance to the object.

```
 Vector3 distance = Vector3.subtract(modelNode.getWorldPosition(), camera.getWorldPosition());
 Log.d(TAG, String.format(Locale.getDefault(), "Model is approx. %.2f m away.",
              distance.length()));
```

One thing to note is that this is to the root of the model, not the edge.

You can also use [Scene.hitTest()](https://developers.google.com/ar/reference/java/sceneform/reference/com/google/ar/sceneform/Scene#hitTest(com.google.ar.sceneform.collision.Ray)) to find the object you are looking at.
```
scene.hitTest(new Ray(camera.getWorldPosition(),camera.getForward()));
```

**Comment by yashvv** [comment]
Thank You Clay. There is no camera.getWorldPosition() even in 1.6.0.
This is the way I got it working for the position tracking.

`float[] position = new float[3];
  frame.getCamera().getPose().getTranslation(position, 0);
            
 Vector3 distance = Vector3.subtract(node.getWorldPosition(), new Vector3(position[0], position[1], position[2]));`

**Comment by claywilkinson** [comment]
Sorry - I should have been more specific (there are so many cameras :/) . SceneView.getCamera().getWorldPosition().  But you can use the the ARCore camera too.
