### ISSUE TITLE
SFB Viewer shows nothing (MacBook Pro / macOS Sierra)

### ISSUE THREAD

**Issue by ddurand-dotscreen** [google-ar/sceneform-android-sdk#47]
![capture d ecran 2018-05-28 a 12 09 37](https://user-images.githubusercontent.com/4602107/40609825-302dd3a8-6270-11e8-9600-a490af82bd04.png)

On a MacBook Pro 13" 2001 / macOS Sierra 10.12.6
System details (in French, sorry...):
  Nom du modèle :	MacBook Pro
  Identifiant du modèle :	MacBookPro8,1
  Nom du processeur :	Intel Core i7
  Vitesse du processeur :	2,8 GHz
  Nombre de processeurs :	1
  Nombre total de cœurs :	2
  Cache de niveau 2 (par cœur) :	256 Ko
  Cache de niveau 3 :	4 Mo
  Mémoire :	8 Go

Graphics card: Intel HD Graphics 3000 :
  Jeu de composants :	Intel HD Graphics 3000
  Type :	Processeur graphique (GPU)
  Bus :	Intégré
  VRAM (dynamique, max.) :	512 Mo
  Fournisseur :	Intel (0x8086)
  Identifiant du périphérique :	0x0126
  Identifiant de révision :	0x0009

**Comment by tpsiaki** [comment]
@ddurand-dotscreen - when you open an SFB, is there any error message pop-up in the bottom right of Android Studio?  You can see more information by clicking on it, or after this occurs, by clicking on the icon in the bottom right of the window showing an exclamation-point inside a circle (either gray or red).

**Comment by AKKamath** [comment]
I'm getting a similar issue. Nothing shows up in the viewer. Clicking on the gray error circle gave the following message:

> null
java.lang.NullPointerException
	at com.google.ar.sceneform.plugin.viewer.FilamentViewer.initialize(FilamentViewer.java:179)
	at com.google.ar.sceneform.plugin.viewer.Filament$1.run(Filament.java:79)
	at com.google.ar.sceneform.plugin.viewer.Filament$4.run(Filament.java:252)

**Comment by tpsiaki** [comment]
@AKKamath - It looks like you're hitting a bug with initialization that is fixed internally - fix will be available in an upcoming release.

**Comment by CloseFile** [comment]
I have the same problem on a Windows 10 computer without a video card.(intel hd 4000)

**Comment by tpsiaki** [comment]
The MacOS initialization error is fixed in the 1.4 version of the Sceneform Android Studio plugin.

**Comment by jmlp1327** [comment]
Hi All. I'm using the 1.6.0 version of SceneForm and I have the same issue.

**Comment by MubashirMurtaza** [comment]
having the same issue on windows 10.
