### ISSUE TITLE
ViewRenderable is broken in Sceneform 1.6.0

### ISSUE THREAD

**Issue by andrewgrow** [google-ar/sceneform-android-sdk#478]
Hello.

I have the simple view (an orange circle) that has been created by next code:
```
ViewRenderable.builder()
                .setView(MyActivity.this, R.layout.view_ar_point)
                .build()
```

the Layout looks like :
```
<?xml version="1.0" encoding="utf-8"?>
<TextView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="100dp"
    android:layout_height="100dp"
    android:background="@drawable/shape_circle_orange"
    />
```

the Drawable looks like : 
```
<shape
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">
    <solid
        android:color="#ffa71c"/>
    <size
        android:width="100dp"
        android:height="100dp"/>
</shape>
```

So, I have the next view:
![normal](https://user-images.githubusercontent.com/8538536/50362802-cff69d80-0571-11e9-9535-b74a72aeb212.png)

**It works perfectly when I have** 
```
implementation "com.google.ar.sceneform:core:1.5.1"
implementation "com.google.ar.sceneform.ux:sceneform-ux:1.5.1"
implementation 'com.google.ar.sceneform:assets:1.5.1'
```

===========
When I try update my dependencies to
```
implementation "com.google.ar.sceneform:core:1.6.0"
implementation "com.google.ar.sceneform.ux:sceneform-ux:1.6.0"
implementation 'com.google.ar.sceneform:assets:1.6.0'

```
I will get the broken image:
![broken](https://user-images.githubusercontent.com/8538536/50362916-501d0300-0572-11e9-91c5-db5607edccce.png)

It will be looks like a square mirror. The view is broken now =(

**Comment by claywilkinson** [comment]
Hi @andrewgrow  - I tried to reproduce this problem, but it worked the same in 1.5.1 and 1.6.

Here is my [sample project](https://github.com/claywilkinson/sceneform-android-sdk/tree/viewrenderable-demo) - Did I do something different from you?

**Comment by andrewgrow** [comment]
@claywilkinson Good afternoon to you, sir. Thank you for your response. I am going to analyzes the sample project and will write an answer here later.

**Comment by andrewgrow** [comment]
@claywilkinson Sir, I have the same error in your project also. 

But you are right - I have an important different thing - in each frame I remove anchor and make new. It will be use the Renderable as an aim (target). I have clone the project and add the differents here: https://github.com/andrewgrow/sceneform-android-sdk/tree/error-478

Please, look at it. Thank you!

**Comment by claywilkinson** [comment]
A workaround, and a more memory efficient approach is to keep the same AnchorNode and just update the anchor from the hittest.  This seems to avoid the problem, and also avoids all the memory allocations of creating a new instance of the renderable internally and allocating a new node on every frame.

I'll pass along your code - it seems like there is still a bug somewhere, but hopefully you're unblocked now.

**Comment by andrewgrow** [comment]
@claywilkinson Thank you so much!
