### ISSUE TITLE
Uranus on solarsystem sample is oriented horizontally instead of vertically

### ISSUE THREAD

**Issue by kenkawakenkenke** [google-ar/sceneform-android-sdk#479]
Expected: The axis of rotation of Uranus should be tilted 97.7° against the orbital axis (i.e the ring should look vertical) https://en.wikipedia.org/wiki/Uranus#Axial_tilt

Actual behaviour: Uranus is rendered with its rotational axis parallel to its orbital axis.
See screenshot: https://photos.app.goo.gl/HzeEs11KAqyrDoiQA

I realize this is just a sample app, but this really stands out in an otherwise beautiful app + feels like an easy enough fix.

**Comment by claywilkinson** [comment]
Thanks @kenkawakenkenke for the pull request.  Because of the way the SDK is published, it cannot be merged, but I've added it to the list of changes for the next release.
