### ISSUE TITLE
How to change plane detection colour?

### ISSUE THREAD

**Issue by mistrydarshan99** [google-ar/sceneform-android-sdk#48]
Hello,

When I scan surface using this SDK I have found white dot plane. Now instead of white dot plane, I have to change it to blue dot plane so how to do this.
![screenshot_20180528-184755_augment 3d](https://user-images.githubusercontent.com/5453894/40616406-8bf07b2c-62a8-11e8-8afc-ca36a3e4239a.jpg)

**Comment by dsternfeld7** [comment]
You can change the color of the plane by setting the color parameter of the plane's material like this:

`arSceneView.getPlaneRenderer().getMaterial().thenAccept(material ->
        material.setFloat3(PlaneRenderer.MATERIAL_COLOR, new Color(0.0f, 0.0f, 1.0f, 1.0f))
    );`

For information about all of the material parameters available for the plane, see the PlaneRenderer documentation [here](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/rendering/PlaneRenderer).

**Comment by mistrydarshan99** [comment]
@dsternfeld7 plane color changes successfully. But now I have to try to render texture image instead of color while plane detected but it will not work as expected. Here is my texture image.
![images](https://user-images.githubusercontent.com/5453894/40784590-b188dd9a-6503-11e8-8a43-03e4b016074d.png)
 Output:
![screenshot_20180531-185240_augment 3d](https://user-images.githubusercontent.com/5453894/40784822-594e9eca-6504-11e8-8aae-a8be13b22875.jpg)

Another issue is that horizontal and vertical surface detected successfully when I detect a ceiling plane is not visible on ceiling detection, but I put android anchor on it see screenshot:
![screenshot_20180531-185936_augment 3d](https://user-images.githubusercontent.com/5453894/40785056-15e0c1c6-6505-11e8-8e29-eea519096195.jpg)

**Comment by dsternfeld7** [comment]
I believe you can get the behavior you expect by changing the [MATERIAL_UV_SCALE](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/rendering/PlaneRenderer.html#MATERIAL_UV_SCALE) parameter. This parameter is used to control the size at which the texture is tiled in world-space, the default values are setup for the default texture. Try this and see what happens:

```
CompletableFuture<Texture> build = Texture.builder().setSource(this, R.drawable.images).build();
arFragment.getArSceneView()
        .getPlaneRenderer()
        .getMaterial()
        .thenAcceptBoth(build, (material, texture) -> {
          material.setTexture(PlaneRenderer.MATERIAL_TEXTURE, texture);
          material.setFloat2(PlaneRenderer.MATERIAL_UV_SCALE, 50.0f, 50.0f);
        });
```

The plane not rendering on ceiling planes sounds like a bug. Can you open a new issue specifically to track that bug?

**Comment by mistrydarshan99** [comment]
Hi,

I have used your code still issue is not fixed. Below is a screenshot. 
![screenshot_20180601-112457_augment 3d](https://user-images.githubusercontent.com/5453894/40973545-40b068b2-68e2-11e8-92af-318b1b4d5e14.jpg)

**Comment by KamikX** [comment]
@mistrydarshan99  Hi, try this code:
```
         // Build texture sampler
        Texture.Sampler sampler = Texture.Sampler.builder()
                .setMinFilter(Texture.Sampler.MinFilter.LINEAR)
                .setMagFilter(Texture.Sampler.MagFilter.LINEAR)
                .setWrapMode(Texture.Sampler.WrapMode.REPEAT).build();

        // Build texture with sampler
        CompletableFuture<Texture> trigrid = Texture.builder()
                .setSource(this, R.drawable.trigrid_0)
                .setSampler(sampler).build();

        // Set plane texture
        this.sceneformFragment.getArSceneView()
                .getPlaneRenderer()
                .getMaterial()
                .thenAcceptBoth(trigrid, (material, texture) -> {
                    material.setTexture(PlaneRenderer.MATERIAL_TEXTURE, texture);
                });
```

Result :
![screenshot_20180605-144612](https://user-images.githubusercontent.com/2276560/40976926-d210848a-68cf-11e8-830f-18bdff6dc641.png)

**Comment by mistrydarshan99** [comment]
@KamikX Thanks, bro. it works very well.

**Comment by dementia2029** [comment]
Hi. I think that this issue is not fixed properly. Custom texture have wrong proportions.

**Comment by dementia2029** [comment]
We also need to set uvScale for Image like this:
`material.setFloat2("uvScale", 1f, 1.19245f);`

**Comment by narendra02031997** [comment]
How can i apply texture to an object

**Comment by ChanduMnS** [comment]
> @mistrydarshan99 Hi, try this code:
> 
> ```
>          // Build texture sampler
>         Texture.Sampler sampler = Texture.Sampler.builder()
>                 .setMinFilter(Texture.Sampler.MinFilter.LINEAR)
>                 .setMagFilter(Texture.Sampler.MagFilter.LINEAR)
>                 .setWrapMode(Texture.Sampler.WrapMode.REPEAT).build();
> 
>         // Build texture with sampler
>         CompletableFuture<Texture> trigrid = Texture.builder()
>                 .setSource(this, R.drawable.trigrid_0)
>                 .setSampler(sampler).build();
> 
>         // Set plane texture
>         this.sceneformFragment.getArSceneView()
>                 .getPlaneRenderer()
>                 .getMaterial()
>                 .thenAcceptBoth(trigrid, (material, texture) -> {
>                     material.setTexture(PlaneRenderer.MATERIAL_TEXTURE, texture);
>                 });
> ```
> 
> Result :
> ![screenshot_20180605-144612](https://user-images.githubusercontent.com/2276560/40976926-d210848a-68cf-11e8-830f-18bdff6dc641.png)

Hey @mistrydarshan99. Thanks for the code. I want to replicate the same for the model. I'm trying to apply a picture to the model. I tried the above code for the plane and it worked. I was applying the texture using modelrenderable.setMaterial(), but I didn't find success the texture is extended. Kindly help me with this. 
Thanks in Advance 
Chandu.
