### ISSUE TITLE
Can ModelRenderable.Builder cache fetched models?

### ISSUE THREAD

**Issue by codeniko** [google-ar/sceneform-android-sdk#482]
This is probably a feature request. I fetch and load my models through URLs. Can Sceneform cache the fetched models so that next time the same url is set to be fetched, it loads from cache instead?

**Comment by claywilkinson** [comment]
Caching quickly turns into a very complex system within itself.  I'd recommend implementing your own caching external of Sceneform and then using the [ModelRenderable.Builder.setSource(Context, Callable&lt;InputStream&gt;)] (https://developers.google.com/ar/reference/java/sceneform/reference/com/google/ar/sceneform/rendering/ModelRenderable.Builder#setSource(android.content.Context,%20java.util.concurrent.Callable%3Cjava.io.InputStream%3E)) to provide the model data.
