### ISSUE TITLE
OBJ can't correctly render vertex colors

### ISSUE THREAD

**Issue by panyingyun** [google-ar/sceneform-android-sdk#485]
OBJ can't correctly render vertex colors
Platform:
Android 9.0 OnePlus 6  
ARCore 1.6

1、OBJ file 
g cube

v  0.0  0.0  0.0  124  110  120
v  0.0  0.0  1.0  24  0  121
v  0.0  1.0  0.0  4  0  44
v  0.0  1.0  1.0  224  0  10
v  1.0  0.0  0.0  24  200  25
v  1.0  0.0  1.0  124  10  56
v  1.0  1.0  0.0  78  10  50
v  1.0  1.0  1.0  23  0  200

vn 0.0 0.0 1.0
vn 0.0 0.0 -1.0
vn 0.0 1.0 0.0
vn 0.0 -1.0 0.0
vn 1.0 0.0 0.0
vn -1.0 0.0 0.0

f 1//2 7//2 5//2
f 1//2 3//2 7//2
f 1//6 4//6 3//6
f 1//6 2//6 4//6
f 3//3 8//3 7//3
f 3//3 4//3 8//3
f 5//5 7//5 8//5
f 5//5 8//5 6//5
f 1//4 5//4 6//4
f 1//4 6//4 2//4
f 2//1 6//1 8//1
f 2//1 8//1 4//1

sceneform Render like this,
![_20190103151637](https://user-images.githubusercontent.com/5029318/50626686-a1fa5b80-0f6a-11e9-8739-0d07cd6403a7.jpg)

but Actually should show up like this：

![snapshot00](https://user-images.githubusercontent.com/5029318/50626627-492ac300-0f6a-11e9-8c35-89df3f70e883.png)

**Comment by panyingyun** [comment]
test obj is here
[cube1.obj.txt](https://github.com/google-ar/sceneform-android-sdk/files/2722938/cube1.obj.txt)
[cube2.obj.txt](https://github.com/google-ar/sceneform-android-sdk/files/2722940/cube2.obj.txt)

**Comment by claywilkinson** [comment]
I am seeing a different result.

I used 1.6 of Sceneform and here is Cube1 and Cube2
![screenshot_cube2](https://user-images.githubusercontent.com/8752378/50655554-6a2ced00-0f45-11e9-8ac4-f44c5fe08fb6.png)

![screenshot_cube1](https://user-images.githubusercontent.com/8752378/50655432-0276a200-0f45-11e9-895d-2117ffb3be88.png)

**Comment by panyingyun** [comment]
@claywilkinson  Thank you very much.
I made a low-level error, sfa was not automatically generated by the system.
   Model: {
     Attributes: [
       'Position',
       'Color',                // do not  missing this line,
       'Orientation',
     ],
I am applying AR technology to the CAE industry. The following illustration shows an engine post-processing demonstration in AR. This is a very interesting job, and I am very grateful for the tools provided by Google.
![engine](https://user-images.githubusercontent.com/5029318/50721437-9fc70700-10fa-11e9-94bf-e867d9dacb46.jpg)
If someone  encounter the same problem, please refer to my github demo
https://github.com/panyingyun/videorecording
