### ISSUE TITLE
How do you place objects on top of one another?

### ISSUE THREAD

**Issue by RealRohan** [google-ar/sceneform-android-sdk#486]
Hello. I am trying to build an application using Android Studio and Sceneform that will allow users to place 3D models of cubes on top of one another (like building blocks). Usually, when you place an object in the same position as another, it just appears inside the first object. I want the object to appear on top of the first object (or under, depending on where the user taps). I also want to add gravity/physics to the blocks so that they can fall.

Is there any way to do this?
Thanks!

**Comment by claywilkinson** [comment]
Sceneform does not have a physics engine integrated, so you need to handle that yourself.

For positioning, you can use the [Renderer.getColliderShape()](https://developers.google.com/ar/reference/java/sceneform/reference/com/google/ar/sceneform/rendering/Renderable#getCollisionShape()) to get the box enclosing the renderable and perform intersection testing or positioning based on the size.

From your general description, you might be better off investigating using a game engine such as Unity (C#), Unreal Engine (C++) or libGDX (Java).
