### ISSUE TITLE
How i can create an object on top of the object in arcore

### ISSUE THREAD

**Issue by beancurd1996** [google-ar/sceneform-android-sdk#487]
I am a student, I am sorry that my English is bad.
I am using android studio to develop an arcore project
I want to create an object on top of the object.
look like 1:20 https://www.youtube.com/watch?v=_WRul7mvnqY
I have never experienced using unity or unreal

**Comment by claywilkinson** [comment]
I'd suggest starting with the [Sceneform codelab](https://codelabs.developers.google.com/codelabs/sceneform-intro/index.html) and after that ask specific questions about the problems.

**Comment by beancurd1996** [comment]
I did try it,but the virtual objects will only overlap.

**Comment by beancurd1996** [comment]
I want to create an virtual object on top of another virtual object

**Comment by claywilkinson** [comment]
I am not sure what you mean by "on top of"?  Can you share a image showing what you are getting and what you are trying to get?

**Comment by beancurd1996** [comment]
sorry for my bad English.
It mean create a virtual object in the plane and create another virtual object in the virtual object plane.
[img]https://upload.cc/i1/2019/01/12/UnEIq5.png[/img]

**Comment by beancurd1996** [comment]
I followed the Sceneform codelab
https://upload.cc/i1/2019/01/12/zsiD5J.png
How can I prevent multiple virtual objects from overlapping

**Comment by ishaang10** [comment]
did you fix your problem?? @beancurd1996  . if yes then please share how
