### ISSUE TITLE
Reset session

### ISSUE THREAD

**Issue by EdwinMurari** [google-ar/sceneform-android-sdk#492]
How do I reset the AR session? I found a solution to this in one of the issues, where the solution was to restart the activity, but that will not work for me because I am using the arfragment in one of the fragments in navigation view, so I tried resetting the fragment but the variables don't reset, which I can take care of by resetting them manually(a solution I found on stackoverflow). I was wondering if there was a better solution to this where I can just reset the session, without restarting the activity or the fragment the ARFragment is in. By "resetting session" I mean, return the ArFragment to the way it was when the app starts, no planes, no anchors, no node, where it shows the handmotion.

**Comment by claywilkinson** [comment]
The easiest way to do this is to replace the ArFragment with a new instance.  To do this, you'll need to add the initial ArFragment manually, not in the layout xml file.  There is a good stackoverflow thread on replacing fragments: https://stackoverflow.com/questions/5658675/replacing-a-fragment-with-another-fragment-inside-activity-group

**Comment by EdwinMurari** [comment]
Thanks a lot for the help, I will try this.
