### ISSUE TITLE
Is there any way to find angle between anchor and the current view of the camera?

### ISSUE THREAD

**Issue by TahirAliKhan** [google-ar/sceneform-android-sdk#497]

**Comment by JohnGilbertson** [comment]
You can use some vector maths to find this out. The following code is Kotlin, but Java version is simple to work out from this

Step 1: Vector from camera to node (the 2 arguments might be the wrong way around I can't remember the correct order off the top of my head)

`val nodeRelativePosition=Vector3.subtract(node.worldPosition, sceneView.scene.camera.worldPosition)`

Step 2: Find the angle between that and the camera forwards view

`val angle=Vector3.angleBetweenVectors(sceneView.scene.camera.forward,nodeRelativePosition)`
