### ISSUE TITLE
Render distance limit

### ISSUE THREAD

**Issue by ArtsemKurantsou** [google-ar/sceneform-android-sdk#498]
Is there any way to increase render distance? I've noticed that when object is far then 30 meters it disappears. Can it be configured some how?

**Comment by claywilkinson** [comment]
At this time there is no way to set the far clip plane.  Setting this would also impact how ARCore works which makes it much more difficult to change.

One option would be for you to scale down nodes beyond 30m and draw them accordingly.

**Comment by valnenov** [comment]
I am facing the same problem. Can you please advise if there is a workaround solution to this issue besides scaling down the nodes, which is not acceptable in my case?

**Comment by ArtsemKurantsou** [comment]
Hi @valnenov . Unfortunately I wasn't able to find workaround. I tried to scale and rotate nodes manually but it worked woeful.

**Comment by valnenov** [comment]
Thanks for you prompt feedback Artem. I guess we have to wait for Google and hope for this to be addressed in the next release of ARcore:-) Please let me know if you come up with some solution before that and I will do the same.

**Comment by guerwan** [comment]
We have the same issue, @claywilkinson any plans to add control over the far clip plane in a future release?

**Comment by guerwan** [comment]
After investigation, you can use : arFragment.getArSceneView().getScene().getCamera().setFarClipPlane(…);

**Comment by vortice3D** [comment]
Hi there:

- ARCore/Sceneform 1.9 keeps on this same frustum fixed setting, with a near plane of 1cm  and a far one of 30m;
- calls to API arFragment.getArSceneView().getScene().getCamera().**setFarClipPlane**(…) seems not to have any effect (maybe is only a placeholder intended for a future real implementation).

Any tips on this issue or must I change to ARKit in order to implement architectural-type AR experiences? I've read that iOS let you a far clipping plane of 1Km.

Best regards.

**Comment by vortice3D** [comment]
Hi there again:

After tweaking a bit the code with the setFarClipPlane call, I've finally managed to have it working.

My fault was to call that API after the Renderable had been already attached to node.

Best regards.

**Comment by aj019** [comment]
@vortice3D Can you show a code snippet to make it clear what you actually did and in which file ?

**Comment by olancedev** [comment]
Hello @aj019  
`        sceneView.scene.camera.farClipPlane = 100.0f
`
You can add this line befor create any renderable. i think best place is in onCreate() method of activity.

**Comment by chnouman** [comment]
@olancedev what it is doing can you explain little?

**Comment by vortice3D** [comment]
Hi there:

First of all, please excuse me for the xtra-delay:

The needed code is fairly straightforward. In the onCreate method of your AR activity you only need to write something:

`...
_arFragment =(CustomARFragment)getSupportFragmentManager().findFragmentById(R.id.ux_fragment);
...
_arFragment.getArSceneView().getScene().getCamera().setNearClipPlane(0.5f);
_arFragment.getArSceneView().getScene().getCamera().setFarClipPlane(750f);
...`

Best regards.
