### ISSUE TITLE
sceneform parsing issue

### ISSUE THREAD

**Issue by kunalmshah85** [google-ar/sceneform-android-sdk#501]
we are using our artifactory as pass through for google() repository. we are not able to resolve sceneform sdk dependency through gradle as its resulting in following Error.

{
  "errors" : [ {
    "status" : 404,
    "message" : "Failed to transform pom file: Failed to read POM for 'com/google/ar/sceneform/core/1.6.0/core-1.6.0.pom': Unrecognised tag: 'packaging' (position: START_TAG seen ...</version>\\n    <packaging>... @23:16) ."
  } ]
}

we reached out to our artifactory vendor to mitigate the issue. The vendor is saying that pom doesn’t meet the Maven standard due to the <packaging> tags existing within dependencies and will have to be fixed by the publisher to be resolved correctly. 

https://maven.apache.org/ref/3.6.0/maven-model/maven.html#class_dependency 

can you guys please look in to this.

**Comment by tpsiaki** [comment]
Thanks for the report.  We have a fix for this internally which will go out in a future release.

**Comment by kunalmshah85** [comment]
Thanks for fixing the issue. Just wanted to mention  following transitive
dependencies  has same issue.

Filament-android
Sceneform-base
Rendering

**Comment by tpsiaki** [comment]
Yes, there was an issue with our pom-generation that affected all of the sceneform-related libraries.  They will all be resolved with the fix.  Thanks!

**Comment by fredsa** [comment]
Fixed in 1.9.0.
https://github.com/google-ar/sceneform-android-sdk/releases
