### ISSUE TITLE
i need to disable vertical plane . this is my code . need help asap

### ISSUE THREAD

**Issue by ishaang10** [google-ar/sceneform-android-sdk#503]
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        arFragment=(ArFragment) getSupportFragmentManager().findFragmentById(R.id.ux_fragment);

        assert arFragment != null;
        ArSceneView arView= arFragment.getArSceneView();
        Scene scene=arView.getScene();

        ModelRenderable.builder().setSource(this,Uri.parse("armchair.sfb")).build()
                .thenAccept(modelRenderable -> chickenren=modelRenderable).exceptionally(throwable -> {
            Toast.makeText(this,"unable",Toast.LENGTH_LONG).show();
            return null;
        });

        arFragment.setOnTapArPlaneListener(
                (HitResult hitResult, Plane plane, MotionEvent motionEvent)->{

                    if(plane.getType() != Plane.Type.HORIZONTAL_UPWARD_FACING)
                        return;

                    Anchor anchor = hitResult.createAnchor();
                    AnchorNode anchorNode = new AnchorNode(anchor);
                    anchorNode.setParent(scene);

                    TransformableNode chicken = new TransformableNode(arFragment.getTransformationSystem());
                    chicken.setParent(anchorNode);
                    chicken.setRenderable(chickenren);
                    chicken.select();

                });

**Comment by ishaang10** [comment]
where should be this class implemented?? separately or in the Main activity itself?
(sorry im totally new to android dev so noob doubts)

**Comment by keval02** [comment]
You can create it separately.

**Comment by ishaang10** [comment]
is this java or kotlin? can you please simplify the code so i can copy. 
thanks

**Comment by ishaang10** [comment]
fragment
       android:id="@+id/ux_fragment"
       android:name="com.google.ar.sceneform.ux.ArFragment"
       android:layout_width="match_parent"
       android:layout_height="match_parent" />

getting error if i change ArFragment to CustomARFragment(ive made a class already and changed the calling of it )

**Comment by ishaang10** [comment]
thank you keval
