### ISSUE TITLE
SceneForm should use <uses-permission23> for EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by kenyee** [google-ar/sceneform-android-sdk#504]
I noticed this in my manifest merge report:
```
uses-permission#android.permission.WRITE_EXTERNAL_STORAGE
IMPLIED from /Users/kyee/..../AndroidManifest.xml:2:1-1709:12 reason: com.google.ar.sceneform has a targetSdkVersion < 4
```

Seems like the library should set a minSdkVersion in its manifest or preferably use the <uses-permission23> tag and ask for it dynamically at runtime.
It appears that it's not currently set so it ends up being required for all API versions.
FWIW, I use the permissions23 tag for camera permissions for this module in our app.

If apps using the libraries want to override the minSDK (if you choose not to use permissions23), they can use this tag in their manifest to override it:

```
<uses-sdk tools:override="com.google.ar.sceneform" /
````

**Comment by claywilkinson** [comment]
Hmm. Which version of sceneform are you using?  I just downloaded and unzipped sceneform 1.6 and the AndroidManifest.xml has 
`  <uses-sdk android:minSdkVersion="14" />`

Please note that Sceneform will not work with API < 24 since Java 8 classes are used (notably CompletableFuture).  The intent of setting the  min version = 14 is to make it easier to include Sceneform in an "AR Optional" application that has a non-AR mode.

**Comment by kenyee** [comment]
Hmm...that is puzzling.  I pulled the artifact from Maven for 1.6 for sceneform as well as com.google.ar:core and both specify a minSDK of 14.
Is the merge manifest report broken?  Looking at it again, it says targetSdk is not set, so I think it's assuming that EXTERNAL_STORAGE permission is enabled by default.
Looks like com.google.ar:core does specify a targetSdkVersion of 24.  However, the sceneform AAR's manifest is missing the targetSdkVersion specifier.  I think that's the real issue.
1.6 added screen capture and video capture support which probably require EXTERNAL_STORAGE permissions and this missing tag gave it to the SDK implicitly.  It should be changed to add the use-permission23 tag so and do a runtime permission dialog instead I think...

**Comment by claywilkinson** [comment]
OK - It looks like sceneform-base, which is a dependency of sceneform core does not have a minSDK
It should have min of 14.

I'll try to get it fixed in the next release

**Comment by kenyee** [comment]
FYI, this also implicitly grabs READ_EXTERNAL_STORAGE and READ_PHONE_STATE permissions as well in case anyone else is uploading a new app w/ an AR feature and wondering why all these new permissions showed up :-(

**Comment by kenyee** [comment]
And for a workaround, add this to your manifest if you don't need these permissions in your app:

```
    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        tools:node="remove" />
    <uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE"
        tools:node="remove" />
    <uses-permission
        android:name="android.permission.READ_PHONE_STATE"
        tools:node="remove" />
```
