### ISSUE TITLE
error in uploading object file from a source

### ISSUE THREAD

**Issue by ishaang10** [google-ar/sceneform-android-sdk#506]
This is a piece of code provided by google to load .gltf file at runtime

 private static final String GLTF_ASSET =
   "https://github.com/KhronosGroup/glTF-Sample-Models/raw/master/2.0/Duck/glTF/Duck.gltf";

 
 ModelRenderable.builder()
    .setSource(this, RenderableSource.builder().setSource(
            this,
            Uri.parse(GLTF_ASSET),
            RenderableSource.SourceType.GLTF2)
            .setScale(0.5f)  
            .setRecenterMode(RenderableSource.RecenterMode.ROOT)
            .build())
    .setRegistryId(GLTF_ASSET)
    .build()
    .thenAccept(renderable -> duckRenderable = renderable)
    .exceptionally(
        throwable -> {
          Toast toast =
              Toast.makeText(this, "Unable to load renderable " +
              GLTF_ASSET, Toast.LENGTH_LONG);
          toast.setGravity(Gravity.CENTER, 0, 0);
          toast.show();
          return null;
        });

but if i load my personal file and add the location to gltf_asset it gives me n error... please help me fix this

**Comment by ishaang10** [comment]
find my model here
https://github.com/ishaang10/models/blob/master/Chair2.gltf

(it also has the.bin file in ghe same folder)

**Comment by claywilkinson** [comment]
Can you share the errors you're getting in the log?

Can you load it using the Sceneform plugin locally just to test that the file is OK?

**Comment by ishaang10** [comment]
yes the file is ok. its running fine if i store locally. here is one error

android.util.malformedjsonexception: use jsonreader.setlenient(true) to accept malformed json

**Comment by ishaang10** [comment]
yeah that worked... thanx so much man.
also can you tell me the difference between blob and raw?

**Comment by ishaang10** [comment]
also do you have idea how can i import model directly from S3 storage on AWS?

**Comment by claywilkinson** [comment]
blob has the html for human viewing - raw is just the file contents.

Sorry, I don't know much about S3 storage on AWS, but it should be pretty easy, you just need to serve the file...

Good luck on your project!
