### ISSUE TITLE
Sceneform and play.core

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/sceneform-android-sdk#507]
When I add `com.google.android.play:core:1.3.4` to my project, I get the error message during build 
```
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
AGPBI: {"kind":"error","text":"Program type already present: com.google.a.a.a.a.a.d","sources":[{}],"tool":"D8"}
```

Any idea what's the class of this shortened classpath points to?

**Comment by claywilkinson** [comment]
This looks like a proguarding issue.  Which version of sceneform are you using?  If not 1.6.0, can you try with that?

**Comment by michaelvogt** [comment]
Thanks for your answer. I'm completely stomped with this problem.

I tried with Sceneform 1.5 and 1.6, with identical result.

Regarding proguard, I have this in the build file of the base module:

```
    buildTypes {
        debug {
            minifyEnabled false
            useProguard false
        }
        release {
            minifyEnabled false
            useProguard false
        }
    }
```

**Comment by claywilkinson** [comment]
Thanks for the additional info.  Let me look into it.

**Comment by michaelvogt** [comment]
@claywilkinson 
Any news? Can you reproduce the problem on your side?

**Comment by abramyan** [comment]
We reproed and have a fix in an upcoming release.

**Comment by michaelvogt** [comment]
@abramyan 
Thanks for your answer.

Any chance this makes it into 1.7?
Otherwise, any workaround possible until the release?

**Comment by abramyan** [comment]
There's a good chance it will be released in 1.7.

**Comment by BharathBunty** [comment]
@abramyan 
my android studio is crashing while installing sceneform plugin 1.3 , 1.4, 1.5 , 1.6  i have tried all..  can you please help me out . how to solve this

**Comment by abramyan** [comment]
@BharathBunty please file a separate issue with repro steps and logs.

**Comment by michaelvogt** [comment]
Compiles fine now with Sceneform 1.7.
