### ISSUE TITLE
Sceneform Android Studio plugin adds Gradle plugin to wrong module

### ISSUE THREAD

**Issue by StevenOttoG** [google-ar/sceneform-android-sdk#51]
I have a project with two modules:
app (An Android app module)
ar (An Android lib module)

Current behavior:
On every asset import the asset definition is added to the build.gradle of the lib project. The following gradle sync fails with the error that the Sceneform gradle plugin only supports app modules. I have to manually move the definition to the build.gradle of the app module.

Expected behavior:
The plugin adds asset definitions to the app module's build.gradle as it's the only one that supports the Sceneform gradle plugin.

**Comment by stevesamknows** [comment]
Related problem: if multiple "application" modules are in a project, the one named "app"
will always get the gradle modifications even if the intention is to add it to a different
application module; would be great if the plugin checked where the user has right-clicked in
the project hierarchy to figure out which build.gradle needs modifying

**Comment by tpsiaki** [comment]
@stevesamknows - Thanks!  We have an internal fix to add the plugin and asset rule to the module associated with the model selected in the importer (i.e. the one you right-click on by default).  This should take care of the problem you're seeing as well.

**Comment by tpsiaki** [comment]
This is fixed in the 1.4.0 version of the Sceneform Android Studio plugin.  Asset rules are now added to the project in which the asset files are located when they are imported.
