### ISSUE TITLE
Alpha Video (Chroma Key Filtering) 

### ISSUE THREAD

**Issue by mistrydarshan99** [google-ar/sceneform-android-sdk#53]
Hello,

How to play Chroma Key Filtering video like (https://www.youtube.com/watch?v=68-bjoF1Vdk) using ARCore? Is there any Video texture available for video play?

**Comment by dsternfeld7** [comment]
Thanks for your report! This isn't possible in Sceneform 1.0. However, we are looking into a way to support this use case.

**Comment by dsternfeld7** [comment]
We just released Sceneform 1.4 that adds the ability to display an android SurfaceTexture on a 3D object in Sceneform using the Sceneform class ExternalTexture. This is a new sample [here](https://github.com/google-ar/sceneform-android-sdk/tree/master/chromakeyvideo) that shows how to use this to play chroma keyed videos.
