### ISSUE TITLE
from where can i get .fbx model and texture files for augmented faces arcore?

### ISSUE THREAD

**Issue by ishaang10** [google-ar/sceneform-android-sdk#540]

**Comment by tpsiaki** [comment]
The canonical facemesh can be found here: https://github.com/google-ar/sceneform-android-sdk/blob/master/assets/canonical_face_mesh.fbx

More info on how this can be used for creating augmented faces apps is here: https://developers.google.com/ar/develop/developer-guides/creating-assets-for-augmented-faces
