### ISSUE TITLE
Node translation by an angle

### ISSUE THREAD

**Issue by mainstreamowy** [google-ar/sceneform-android-sdk#543]
Hi!
I'm trying to rotate all of my nodes to be at the specific location.
But, everytime I do shift anchor, length of vector 0,0 -> points coords are getting smaller. 
First : I create bunch of nodes and add them to node list.
`Node aNode = new Node();
              aNode.setWorldPosition(wektor3);
              aNode.setParent(arFragment.getArSceneView().getScene());
              aNode.setRenderable(andyRenderable);
              anchor_list.add(aNode);`

Then I'm retrieving the nodes x,y,z : 
`
Vector3 temp_vector;
        double rad = Math.toRadians((alpha%360)*Math.PI/180);
        int it=0;
        for(Node al : anchor_list)
        {
            
            temp_vector = al.getWorldPosition();
            temp_vector.x = (float)(temp_vector.x * Math.cos(rad) - temp_vector.z* Math.sin(rad));
            temp_vector.z = (float)(temp_vector.x * Math.sin(rad) + temp_vector.z* Math.cos(rad));
            al.setWorldPosition(temp_vector);
            al.setRenderable(andyRenderable);
            it++;
        }`

After translating nodes they come and come closer to each other. Any clues ? Or is it a better way to do it different than with nodes? 
And last question : What is the best way to create renderable points with it's x,y,z downloaded from database, and then rotated by an angle ?

**Comment by chnouman** [comment]
@mainstreamowy how you resolved this?

**Comment by mainstreamowy** [comment]
> @mainstreamowy how you resolved this?

I did a stupid mistake while computing new x and z cooridantes.
I had to make a temp variable which hold x and z. Example:

```
temp_x = temp_vector.x ;
temp_z = temp_vector.z;
temp_vector.x = (float)(temp_x * Math.cos(rad) - temp_z* Math.sin(rad));
temp_vector.z = (float)(temp_x* Math.sin(rad) + temp_z* Math.cos(rad));
```
