### ISSUE TITLE
about the fbx animation

### ISSUE THREAD

**Issue by YaoYoYi** [google-ar/sceneform-android-sdk#545]
hi:
Ask a question....
How to add clips the animation like unity ? Are there any parameters?
sample:
{
   animations: [
    {
      clips: [
        {
          name: 'Take 001',
          runtime_name: 'xxg',
          **start_frame:0.0,
          end_frame:120.0,**
        },
      ],
      path: 'path/xxg.fbx',
    },
  ],
}

**Comment by tpsiaki** [comment]
There is not a way to trim the animation clip in our fbx animation import step.  We import all of the animation clips that were exported in the fbx containing animations, so in order to create trimmed clips you will have to set the start/end frames when creating the fbx.

**Comment by YaoYoYi** [comment]
Thanks!
