### ISSUE TITLE
Using SkeletonNode to identify and attach models to bones

### ISSUE THREAD

**Issue by YinXiuYu** [google-ar/sceneform-android-sdk#547]
I want to use the SkeletonNode to identify and attach models to bones , as in the Animation sample,I replaced Andy with another animation resource, but the hat didn't move with it .

**Comment by dsternfeld7** [comment]
My guess is that the model does not have a bone in it named "hat_point" like the example andy model does. You can look at the bones in modeling software like Maya or print them all out by using [ModelRenderable.getBoneName](https://developers.google.com/ar/reference/java/sceneform/reference/com/google/ar/sceneform/rendering/ModelRenderable#getBoneName(int)) and [ModelRenderable.getBoneCount](https://developers.google.com/ar/reference/java/sceneform/reference/com/google/ar/sceneform/rendering/ModelRenderable#getBoneCount())

**Comment by YinXiuYu** [comment]
The issue was solved quickly according to your suggestion. Thank you very much!
