### ISSUE TITLE
How to create animated model SkeletonNode with controls as TransformableNode?

### ISSUE THREAD

**Issue by dpproduction** [google-ar/sceneform-android-sdk#548]
I create SkeletonNode with animated fbx model. Animation is playing but I can't moving model by finger like TransformableNode with Andy model. I tried set parent TransformableNode to SkeletonNode and vice versa, in not works. How to integrate this classes?

**Comment by YinXiuYu** [comment]
You can create the transformable andy and add it to the anchor. The code example is as follows:
 // Create the transformable andy and add it to the anchor.
TransformableNode transformableNode = new 
     TransformableNode(arFragment.getTransformationSystem());
transformableNode.addChild(andy);
transformableNode.setParent(anchorNode);
transformableNode.select();

**Comment by dsternfeld7** [comment]
Were you able to get this working?

**Comment by dpproduction** [comment]
yes it works.

       `AnchorNode anchorNode = new AnchorNode(anchor);
        anchorNode.setParent(arFragment.getArSceneView().getScene());

        SkeletonNode dragon = new SkeletonNode();
        dragon.setRenderable(dragonRenderable);

        TransformableNode transformableNode = new
                TransformableNode(arFragment.getTransformationSystem());
        transformableNode.addChild(dragon);
        transformableNode.setParent(anchorNode);
        transformableNode.select();
`
