### ISSUE TITLE
Vertical Translation

### ISSUE THREAD

**Issue by AKKamath** [google-ar/sceneform-android-sdk#55]
I want to place objects on planes, similar to the hellosceneform example, but I want nodes placed on horizontal planes to only translate horizontally, and nodes on vertical planes to translate vertically. Currently only the horizontal translation is working. How would I go about changing it?

**Comment by malik-at-work** [comment]
We have added some support for vertical planes in the Transformation System in an upcoming release.  Version 1.0 was only designed for horizontal planes.

**Comment by malik-at-work** [comment]
Closing as this duplicates https://github.com/google-ar/sceneform-android-sdk/issues/24
