### ISSUE TITLE
how to set texture from image

### ISSUE THREAD

**Issue by ivstka95** [google-ar/sceneform-android-sdk#559]
how can i set a texture on a renderable on runtime? 
i am trying to change it in code
  `Texture.builder().setSource(this, Uri.parse("maxresdefault.jpg")).build().thenAccept(texture ->
                                    andyRenderable.getMaterial().setTexture(MATERIAL_TEXTURE, texture));`
but it seems to set main color of that image as renderable's solid color, not the actual image
this is the picture i expect to be drawn on the model
![maxresdefault](https://user-images.githubusercontent.com/23726353/53350338-8dfa2700-3927-11e9-9686-17f13806ceab.jpg)
this is how it actually looks
![photo_2019-02-25_18-05-01](https://user-images.githubusercontent.com/23726353/53350619-1bd61200-3928-11e9-90d6-73fe0c0dd272.jpg)

any help appreciated!

**Comment by dsternfeld7** [comment]
I suspect that the UV mapping for the model is not rendering the texture where you expect it. Assuming you made the model yourself, I suggest you try using this image in your 3D modeling software and seeing if you get the same result. If so, you can look at your UV map and update it accordingly.

**Comment by ivstka95** [comment]
@dsternfeld7 thanks, i will try
