### ISSUE TITLE
Sceneform FBX Asset - Messed Up UVs

### ISSUE THREAD

**Issue by chiaolinghong3d** [google-ar/sceneform-android-sdk#56]
I am just starting Sceneform for AR Core development. So I've been testing both .obj and .fbx...

For the obj file, the texture gets imported perfectly fine, but the fbx one's UV seems to be off in a weird way...I've tried just flipping the texture/rotating (who knows, might be Zbrush's flipped problem too), but it's not that simple...

My final result is I have to flip the UVs, rotate it by 180 degrees, then move it upwards, but still have some UV island being off.

Wonder if it's some auto center or UV re-layout thing going on with Sceneform.

I do prefer fbx than obj though, since it allows other texture maps like normal, roughness, metalness, ao...etc. Plus, I am still waiting on the fbx animation import option in the future. [here's what it looks like in Maya](https://i.stack.imgur.com/GHNDJ.jpg), then sceneform asset in obj & fbx Thanks!

* I've also attached the fbx and obj files. For the FBX, I have both just the simple phong material and PBS material (so far the maps get converted into "fbx_material.sfm" without a problem, just the UVs are totally off in a weird way)
[example.zip](https://github.com/google-ar/sceneform-android-sdk/files/2055101/example.zip)

**Comment by AdrianAtGoogle** [comment]
Hi @chiaolinghong3d,
This was an issue we discovered after ship - imported FBX files incorrectly flip the vertical texture coordinate.  This has been fixed locally and will be pushed into the next release.

**Comment by AdrianAtGoogle** [comment]
This is a dup of #27
