### ISSUE TITLE
Hello, excuse me, how can I get the coordinates in the screen of the mobile phone according to node. worldPosition?

### ISSUE THREAD

**Issue by apetoman** [google-ar/sceneform-android-sdk#561]
Hello, excuse me, how can I get the coordinates in the screen of the mobile phone according to node. worldPosition?

**Comment by dsternfeld7** [comment]
You can do this:

`Vector3 screenPoint = camera.worldToScreenPoint(node.getWorldPosition());`

**Comment by apetoman** [comment]
> 你可以这样做：
> 
> `Vector3 screenPoint = camera.worldToScreenPoint(node.getWorldPosition());`

 It seems that the camera does not have this function

         val camera = arSceneView.arFrame.camera
         var  screenPoint = camera.**worldToScreenPoint**(node.getWorldPosition())
