### ISSUE TITLE
ArSceneView with SharedCamera

### ISSUE THREAD

**Issue by dpproduction** [google-ar/sceneform-android-sdk#569]
I'm working on an application in which there are 2 modes Ar mode and NonAr mode. 
In Ar mode I use ArSceneView.
In NonAr mode I whant to draw camera on GlSurfaceView. 
I see sample with SharedCamera but there both modes draws in one GlSurfaceView.
Is it possible to use SharedCamera with ArSceneView in Ar mode and GlSurfaceView when NonAr mode?

**Comment by dpproduction** [comment]
You can close issue.
It is possible to draw camera in ArSceneView when ar mode and draw on GlSurfaceView when non-Ar mode. It works fine!

**Comment by tpsiaki** [comment]
Thanks @dpproduction

**Comment by ManuelTS** [comment]
@dpproduction may you please share your code how you accomplished that?

**Comment by lancefi** [comment]
> You can close issue.
> It is possible to draw camera in ArSceneView when ar mode and draw on GlSurfaceView when non-Ar mode. It works fine!

How did you do that?
