### ISSUE TITLE
How can I apply WrapMode into custom material

### ISSUE THREAD

**Issue by mpetlyuk** [google-ar/sceneform-android-sdk#570]
I want to set repeating mode into the texture of my custom material. How can I do this?

**Comment by dsternfeld7** [comment]
You can set the wrap mode in the .sfa file, which can be seen here: https://developers.google.com/ar/develop/java/sceneform/sfa

Also, if you are assigning the texture at runtime, you can use the Texture.Sampler class to set the wrap mode: https://developers.google.com/ar/reference/java/sceneform/reference/com/google/ar/sceneform/rendering/Texture.Sampler

**Comment by mpetlyuk** [comment]
Great thanks. You are right, but seems that now I a bit confusing with my task. Maybe can you help with any explanation? 

So, the global task looks like that I have a cube (start: Vector3(0, 0, 0), end Vector3(0, 0, -1)). And I have png image which I wanna put into the texture with repeat mode and move this texture with some fixed duration(something like endless progress for example).

**.sfa:** 
```
{
  materials: [
    {
      name: 'DefaultMaterial',
      parameters: [
        {
          route: 'arrow',
        },
        {
          repeat_x: 0,
        },
        {
          repeat_y: 0,
        }
      ],
      source: 'models/arrow_route/repeat_texture.mat',
    },
  ],
  model: {
    attributes: [
      'Position',
      'TexCoord',
      'Orientation',
    ],
    collision: {},
    file: 'models/arrow_route/arrow_holder.obj',
    name: 'arrow_holder',
    recenter: 'root',
  },
  samplers: [
      {
        file: 'models/arrow_route/arrow.png',
        name: 'arrow',
        params: {
            wrap_t: "Repeat",
        }
      },
  ],
  version: '0.54:1',
}
```

**.mat**
At first I assume that I will calculate offset of the repeating drawing .png on the texture inside the fragment shader by hand but I failed with aspect ratio and then I suppose that 'wrap_mode' will help me.
```
material {
   name : "RepeatingTexture",
    parameters : [
           {
              type : float,
              name : repeat_y
           },
           {
              type : float,
              name : delta_y
           },
           {
              type      : sampler2d,
              precision : high,
              name      : route
           }
       ],
       requires : [
           position,
           uv0
       ],
}
```

**Init model:**
```
ModelRenderable.builder()
                .setSource(activity, R.raw.arrow_holder)
                .build()
                .thenAccept {
                    lineRenderable = ShapeFactory.makeCube(Vector3(.01f, .01f, LINE_LENGTH), Vector3(.01f / 2f, .01f / 2f, LINE_LENGTH / 2), it.material)
                }
                .exceptionally { error ->
                    Log.e("MaterialFactory", "renderable error", error)
                    return@exceptionally null
                }
```

Any help will be appreciated.
