### ISSUE TITLE
Control the camera Exposure / AutoExposure

### ISSUE THREAD

**Issue by kunal-wayfair** [google-ar/sceneform-android-sdk#586]
Hi,

Is there a way to control the native camera properties like Exposure / AutoExposure using Sceneform. I cannot seem to find any way to access the camera and change its properties. I am trying to get a fixed exposure for multiple pixelCopy screenshots for a feature during a given AR session so that they look consistent.

Thanks!

**Comment by tpsiaki** [comment]
Thanks for the request.

This is being tracked in the ARCore Android SDK here: https://github.com/google-ar/arcore-android-sdk/issues/153
