### ISSUE TITLE
add runtime storage permission using customARFragment

### ISSUE THREAD

**Issue by ishaang10** [google-ar/sceneform-android-sdk#593]
I want to add WRITE_EXTERNAL_STORAGE permission also in ARFragment . so how can i do that??

i have made a CustomArfragment which extends ARFragment and looks like this

ublic class CustomARFragment extends ArFragment {
    @Override
    protected Config getSessionConfiguration(Session session) {
        Config config = new Config(session);
        config.setPlaneFindingMode(Config.PlaneFindingMode.HORIZONTAL);
        return config;
    }
}

**Comment by HEMAL-PATEL** [comment]
@ishaang10 

Override get additional permissions() method in your custom ARFragment class which can handle your permission at run time. Here Below, I showed you an example of that. Try that one.

```
    @Override
    public String[] getAdditionalPermissions() {
        String[] additionalPermissions = super.getAdditionalPermissions();

        int permissionLength = additionalPermissions != null ? additionalPermissions.length : 0;

        String[] permissions = new String[permissionLength + 1];

        permissions[0] = Manifest.permission.WRITE_EXTERNAL_STORAGE;

        if (permissionLength > 0) {
            System.arraycopy(additionalPermissions,
                    0,
                    permissions,
                    1,
                    additionalPermissions.length);
        }

        return permissions;

        //return super.getAdditionalPermissions();
    }
```

**Comment by ishaang10** [comment]
thanks a lot sir...!!!
