### ISSUE TITLE
Failure to install/update ARCore 1.2 dependency

### ISSUE THREAD

**Issue by haroldmthyng** [google-ar/sceneform-android-sdk#6]
Upon launching HellowSceneForm sample on Galaxy S8 with a previous existing version of ARCore on the device, you are presented with a dialog stating: `This application requires the latest version of ARCore. Continue`

However when you continue, the sample app redirects you to the ARCore 1.1 listing and never installs or updates the ARCore service. You are presented with a play store dialog, but only have the option to uninstall. 

I've tried uninstalling and re-installing ARCore with no luck. It does not fix this issue either. If you proceed launching the sample app, you receive the toast `Failed to create AR session.`

**Comment by jwmcglynn** [comment]
ARCore 1.2 is currently rolling out, but is not currently available to 100% of Play Store users.  In the mean time, you can manually install the 1.2 APK by following the sideload instructions on this page: https://developers.google.com/ar/develop/downloads

**Comment by haroldmthyng** [comment]
That works. Gracias!!!
