### ISSUE TITLE
Get object meshes count not the materials count

### ISSUE THREAD

**Issue by bobekos** [google-ar/sceneform-android-sdk#610]
Hi,

why is the submeshCount method returning the amount of the materials not the amount of meshes. What if i have a object with for example two meshes which both have the same material and i want to change the material of only on one of them?

Is that possible at this time?

**Comment by tpsiaki** [comment]
Currently we deduplicate material instances by default, so if you want to set different material parameters on a particular mesh in a model, you should create a copy of the material instance used on that mesh, set that copy as the material to draw that mesh, and set the parameters you wish to use on the material instance copy.
