### ISSUE TITLE
"Import Sceneform Asset" option not shown on right click of .obj

### ISSUE THREAD

**Issue by risingsunomi** [google-ar/sceneform-android-sdk#612]
Hello,
I have the current plugin installed and set in my project's build.grandle file
```
dependencies {
    ...
    classpath 'com.google.ar.sceneform:plugin:1.7.0'
}
```
When right clicking on [this sun's](https://poly.google.com/view/1Zo-IZ5W-gR) .obj file, I only see "New..". 

**Are there further things to install for the right click option to appear?**

My module build.gradle
```
dependencies {
    ...
    implementation 'com.google.ar:core:1.7.0'
    implementation 'com.google.ar.sceneform.ux:sceneform-ux:1.7.0'
    implementation 'com.google.ar.sceneform:core:1.7.0'
}
```

I am running Android Studio 3.3.2 on macOS 10.14.3 Mojave

Thank you

**Comment by tpsiaki** [comment]
Will you double-check that the Android Studio Google Sceneform Tools (Beta) plugin is enabled?

Android Studio > Preferences > Plugins

Find "Google Sceneform Tools (Beta)" and ensure that it is present, and the checkbox next to it is checked.  If it is unchecked try checking it and restarting.

**Comment by risingsunomi** [comment]
> Will you double-check that the Android Studio Google Sceneform Tools (Beta) plugin is enabled?
> 
> Android Studio > Preferences > Plugins
> 
> Find "Google Sceneform Tools (Beta)" and ensure that it is present, and the checkbox next to it is checked. If it is unchecked try checking it and restarting.

That worked. Sorry didn't see this in [the instructions](https://developers.google.com/ar/develop/java/sceneform/import-assets). Thank you very much!
