### ISSUE TITLE
Not Working in Kotlin

### ISSUE THREAD

**Issue by vishalvanpariya** [google-ar/sceneform-android-sdk#614]
This Code is Completly Working in java But whenever I am doing the same thing in Kotlin it is not working.

with the kotlin, it is not detected surface.

Please Give some solution to me.
Thank You

**Comment by bobekos** [comment]
My whole project is in kotlin and uses all features of the sceneform sdk without any problems. Can you please be more specific about what's not working?

**Comment by vishalvanpariya** [comment]
@bobekos there is no any project related Sceneform in your Repositories.

**Comment by bobekos** [comment]
No i have no open repo with a sample. But i am working on many different projects which are written in kotlin and uses the sceneform sdk. So my question was where are you specific problems with sceneform and kotlin? I mean Java is 100% compatible with kotlin and vice versa.

**Comment by vishalvanpariya** [comment]
@bobekos I know that but in ARCore there is something different in it.
now the problem has been solved.
Thank
