### ISSUE TITLE
How to detect only table surface, not floor suface?

### ISSUE THREAD

**Issue by vishalvanpariya** [google-ar/sceneform-android-sdk#618]
am trying to detect only table surface but this is detected Floor and table surface give some solution related to it.
            `arFragment.setOnTapArPlaneListener { hitResult, plane, motionEvent ->
            if(andyRenderable == null){
                return@setOnTapArPlaneListener
            }
            var anchor = hitResult.createAnchor()
            var anchorNode = AnchorNode(anchor)
            anchorNode.setParent(arFragment.arSceneView.scene)
            var transformableNode =TransformableNode(arFragment.transformationSystem)
            transformableNode.setParent(anchorNode)
            transformableNode.setRenderable(andyRenderable)
            transformableNode.localPosition = Vector3(0f,0f,0f)
            transformableNode.select()
        }`
Give me some idea for differentiate it.
Thank you

**Comment by ishaang10** [comment]
ARCore detects the horizontal/vertical plane according the the feature points and flatness of the things around you . so if you have a table before your floor which is not perfectly white in color then it would detect it as a surface as well
