### ISSUE TITLE
3D model has no color after importing via sceneform plugin

### ISSUE THREAD

**Issue by devpranav21** [google-ar/sceneform-android-sdk#622]
Hi there,
I downloaded a model from POLY  - https://poly.google.com/view/0BnDT3T1wTE
But, when I imported it using Sceneform Plugin, it lost all the color and was totally greyed out.
And this happens with other few models as well, not all but quite a few. (Screenshot Attached)
Also attaching the generated SFA file.
[dog_1.sfb.txt](https://github.com/google-ar/sceneform-android-sdk/files/3005824/dog_1.sfb.txt)

Any Idea? Why is it ? or what is the solution? 
![image](https://user-images.githubusercontent.com/47368815/54959221-69bd5480-4f7e-11e9-9c97-d52e653f5b36.png)

**Comment by cktamucalgary** [comment]
You need to add the textures into the sampledata file as well. So copy Tex_Beagle.png to the folder and re-import the model.

**Comment by devpranav21** [comment]
yes....I missed that
Thanks for the help...
