### ISSUE TITLE
Object position when tracking state lost

### ISSUE THREAD

**Issue by mpetlyuk** [google-ar/sceneform-android-sdk#625]
I did not use anchors and I wanna just put the object relative to camera pose with specific rotation. When camera tracking state lost, node with object ignores calculated position & rotation and is moving with camera device. How can keep the object in the previous position, when AR camera tracking state is lost?

**Comment by fredsa** [comment]
We recommend using anchors as objects attached to anchors will appear to be attached to the world, whereas objects placed in world space will appear to drift and feel detached.
