### ISSUE TITLE
Load SFB at runtime (without Sceneform plugin/gradle combo)

### ISSUE THREAD

**Issue by fzaiatz** [google-ar/sceneform-android-sdk#636]
Is it possible to generate a SFB file outside of Android Studio? Something like a Blender plugin / a console script, so we can load SFB models at runtime (taking advantage of model animations for instance).

**Comment by bobekos** [comment]
You can use the converter also outside of android studio. Check this here:
https://github.com/gdamoreira/google-ar-asset-converter

**Comment by tpsiaki** [comment]
Currently the only supported way to generate SFBs to use the [Sceneform gradle plugin](https://developers.google.com/ar/reference/java/gradle/reference/com/google/ar/sceneform/plugin/package-summary) (either inside an android studio project, or in a standalone gradle build).

As pointed out by @bobekos, there is an underlying command line tool that gets called by the Sceneform plugin.  When you run a gradle build using the Sceneform plugin, right now the command line tool is unzipped into the build/sceneform_sdk directory and could theoretically be used directly.  Note a couple of important details with the converter command line tool:
- The matc command line tool alongside of the converter also needs to be accessible from the converter.
- Paths referenced in sfa files are generally interpreted as relating to the directory from which you *run* converter and so you'll need to use care with how you run it.
- You'll want to make sure that the version of Converter and Matc match the version of the Sceneform sdk that you're using (these tools generally get updated every release).
- Finally, I'll reiterate - this is not currently a supported path, and the internal details of how these tools are used by the gradle plugin (and therefore their general availability) may need to change in the future.

**Comment by fzaiatz** [comment]
Thanks @bobekos for linking to the converter, didn't know about that one. Also thanks @tpsiaki for those notes about it :)

**Comment by jungwonwoong** [comment]
your_project_work_directory\app\build\sceneform_sdk\windows\converter.exe

windows10 cmd bat file

[convert.bat.txt](https://github.com/google-ar/sceneform-android-sdk/files/4298722/convert.bat.txt)
