### ISSUE TITLE
Error in rendering after update 1.8.0

### ISSUE THREAD

**Issue by ivstka95** [google-ar/sceneform-android-sdk#639]
after updating to 1.8.0 i see wrong colors in rendered models

this was in 1.7.0
![photo_2019-04-02_15-30-16](https://user-images.githubusercontent.com/23726353/55402521-543ac280-555c-11e9-8d91-9f9e3f701506.jpg)
and this is what i see after update to 1.8.0
![photo_2019-04-02_15-30-28](https://user-images.githubusercontent.com/23726353/55402555-66b4fc00-555c-11e9-82ac-b9133eb8359a.jpg)
the model is generated by sceneform plugin long time ago, so it was not affected by any changes

**Comment by romainguy** [comment]
You might need to reimport the model because of changes in the shader system.

**Comment by ivstka95** [comment]
> You might need to reimport the model because of changes in the shader system.
i can't, the model is converted on the server

**Comment by ivstka95** [comment]
> You might need to reimport the model because of changes in the shader system.

the model is converted and stored on the server

**Comment by kewalkishang** [comment]
Hi after the new update the model viewer doesnt show any texture and the model is rendered as such
![Screenshot (6)](https://user-images.githubusercontent.com/13698461/56200655-d21ec380-605c-11e9-80a5-266a72e4734a.png)
It was fine before the recent update ( link to original model https://poly.google.com/view/88nXdqyGV06 )

**Comment by fredsa** [comment]
To fix the issue, please recreate the .sfb from the .sfa, see https://developers.google.com/ar/develop/java/sceneform/import-assets

**Comment by ivstka95** [comment]
fine with 1.9
