### ISSUE TITLE
The camera has no focus 

### ISSUE THREAD

**Issue by siny-yao** [google-ar/sceneform-android-sdk#643]
In 'augmentedimage' demo
The camera has no focus when the image recognition.
Is there a way to solve it?

**Comment by siny-yao** [comment]
Config config = super.getSessionConfiguration(session);
config.setFocusMode(Config.FocusMode.AUTO);

**Comment by yongzhenzou** [comment]
> In 'augmentedimage' demo
> The camera has no focus when the image recognition.
> Is there a way to solve it?

thanks

**Comment by yongzhenzou** [comment]
> Config config = super.getSessionConfiguration(session);
> config.setFocusMode(Config.FocusMode.AUTO);

thank you
