### ISSUE TITLE
How to place a single infinite plane? 

### ISSUE THREAD

**Issue by yuly830914** [google-ar/sceneform-android-sdk#647]
Hello all,

I am currently looking to find a way to limit plane tracking to a single infinite plane. That is to say, when I open the ARCore app, scan the environment and get the coordinates for a single plane.

Now I can get get a plane, but it is not extended(infinite)
How can i place an object to the plane using Sceneform ?

Thank you

**Comment by yuly830914** [comment]
Found the solution.

**Comment by dpacholczyk** [comment]
@yuly830914 could you share the solution?
