### ISSUE TITLE
Change transformableNode  Y coordinates 

### ISSUE THREAD

**Issue by apetoman** [google-ar/sceneform-android-sdk#651]
I changed the value of the Transformable Node Y coordinate by a button. It worked, but when I moved the Transformable Node, the value of its Y coordinate returned to its original state. Why? Who can tell me what to do?

**Comment by ishaang10** [comment]
Try using a Node instead of Transformable node.. and if you want to use the transformable node methods create a empty transformable node and add the model node as its child.


(Empty Tranformable node)
              |
              |
     (model node)

**Comment by apetoman** [comment]
> 尝试使用Node而不是Transformable节点..如果要使用可转换节点方法，请创建一个空的可转换节点，并将模型节点添加为其子节点。
> 
> （空转换节点）
> | 
> | 
> （模型节点）

Thank you, this is no good, TransformableNode must have an AnchorNode as a parent, I move model node, the TransformableNode Y returned to the place to start
