### ISSUE TITLE
How to set doubleSided to material if create model without 3D Asset?

### ISSUE THREAD

**Issue by artur0503** [google-ar/sceneform-android-sdk#658]
`ModelRenderable boxModel = ShapeFactory.makeCube(size, center, material);`
I create model without any asset files, so how can i set doubleSided in runtime? Maybe I can set *.mat file to my material?

**Comment by bobekos** [comment]
The only solution that i know is to create a default model over sfb (like a simple triangle) and give it a custom material with the double sided attribute. Now at runtime you can load the sfb model copy the material from it and set it to your created renderable.

This was already discussed here on GitHub you can search for #public material builder

**Comment by artur0503** [comment]
Thanks for reply)
