### ISSUE TITLE
SceneView CaptureScreenshot() method not working as expected

### ISSUE THREAD

**Issue by LukasStancikas** [google-ar/sceneform-android-sdk#66]
Hello, i've tried the `sceneView.getRenderer().captureScreenshot( listener)`

And i've noticed some problems with it. I've tried creating a bitmap from the ByteBuffer and widht, height that i get in my result, but the image output is almost twice as small than the supplied width and height.
This is how i generate the bitmap:
```
fun onCameraClick(buffer: ByteBuffer, width : Int, height: Int): Bitmap {
		buffer.rewind()
		val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
		bitmap.copyPixelsFromBuffer(buffer)
		return bitmap
}
```
The width and height i always get is 1440x2736 (this is presumably my sceneview (aka surfaceView) size, but the bitmap is just 538x1024 size, and everything else is just transparent area.

What is even weirder is after trying to capture the image a second time, the height/width returns same size values, but bitmap is duplicated inside: [Heres a screenshot](http://oi67.tinypic.com/es6x5k.jpg)

Also, https://developers.google.com/ar/reference/java/com/google/ar/sceneform/SceneView leads to a 404 to any documentation about what SceneView has to offer

**Comment by malik-at-work** [comment]
In V1.0 SceneView, Renderer etc is marked @hide.  SceneView will be exposed in the upcoming release, but I'd advise against using it until then.

**Comment by claywilkinson** [comment]
A better way to capture a screenshot is to use [PixelCopy](https://developer.android.com/reference/android/view/PixelCopy) which captures a Surface to a Bitmap.

The [Codelab for Sceneform](https://codelabs.developers.google.com/codelabs/sceneform-intro/index.html?index=..%2F..%2Findex#14) has an example on how to do this.
