### ISSUE TITLE
Remove HandMotionAnimation

### ISSUE THREAD

**Issue by nitram2101** [google-ar/sceneform-android-sdk#68]
Hi, 
is it possible to start Arcore/sceneform without the HandMotionAnimation? I Can't find an easy way to switch it off. 
For example in the hello-arcore app for java.

Best regards and thank you!

**Comment by malik-at-work** [comment]
You will wantr to do something like:
ArFragment.getDiscoveryController().hide();
ArFragment.getDiscoveryController().setInstructionView(null);

if you inherit ArFragment you can call these in your fragment's onCreateView

**Comment by nitram2101** [comment]
It worked, Thank you!

**Comment by hcjung2000** [comment]
@malik-at-work, I have similar question. how can I notice plane detect is done?
is there any callback function?

**Comment by malik-at-work** [comment]
Currently there is no callback.  

PlaneDiscoveryController is driven from onUpdate, so you could add code to trigger your new behavior there as well

 @Override
  public void onUpdate(FrameTime frameTime) {
   super.onUpdate(frameTime);
    for (Plane plane : frame.getUpdatedTrackables(Plane.class)) {
      if (plane.getTrackingState() == TrackingState.TRACKING) {
        // Once there is a tracking plane, plane discovery stops.
        // do your callback here.
      }
    }
  }

**Comment by hcjung2000** [comment]
@malik-at-work, Thanks very much!

**Comment by izdi** [comment]
@malik-at-work Hello!

I don't want create another issue, but I'd like some help because I feel like it's related.

The question is: how do I also hide rendered plane? (link below)

[image](https://user-images.githubusercontent.com/6037501/42244947-a69942fe-7f1f-11e8-94f7-9aed8218414f.png)

**Comment by okonor** [comment]
To turn off the plane renderer you should disable `planeRenderer` - https://developers.google.com/ar/reference/java/com/google/ar/sceneform/rendering/PlaneRenderer.

You can do it by changing `arSceneView.getPlaneRenderer().setEnabled` to `false`.

Or use `setVisible' if you are going to render plane and hide visualization only.

**Comment by kenyee** [comment]
@malik-at-work: also had to do that override for plane detection complete.  Would be nice to add an official callback for it 🙂

**Comment by sarahthe** [comment]
Did you change the API for hiding the hand motion? I have an ArFragment and used the `getPlaneDiscoveryController()` instead because `getDiscoveryController()` doesn't exist.

When setting instruction view to null, the hand is still shown.

This is my code in `onResume`:
```
arFragment = (ArFragment) getChildFragmentManager().findFragmentById(R.id.ar_fragment);
if (arFragment != null) {
            // hiding the plane discovery
            arFragment.getPlaneDiscoveryController().hide();
            arFragment.getPlaneDiscoveryController().setInstructionView(null);
            arFragment.getArSceneView().getPlaneRenderer().setEnabled(false);
}
// setup session etc.
```

**Comment by khurramengr** [comment]
> Currently there is no callback.
> 
> PlaneDiscoveryController is driven from onUpdate, so you could add code to trigger your new behavior there as well
> 
> @override
> public void onUpdate(FrameTime frameTime) {
> super.onUpdate(frameTime);
> for (Plane plane : frame.getUpdatedTrackables(Plane.class)) {
> if (plane.getTrackingState() == TrackingState.TRACKING) {
> // Once there is a tracking plane, plane discovery stops.
> // do your callback here.
> }
> }
> }

@malik-at-work  While extending **ArFragment** and overriding the **onUpdate()** it turned out that all the variable in **BaseArFragment** are private, so we can't access anything there.
e.g `frame.getUpdatedTrackables` gives error.

**Comment by denzerd** [comment]
It is some time since you asked that and sure you solved it by now, but for future reference (as this is the first that showed up on Google for me...)

What is needed right now is to call hide() and setInstructionView(null) in this order but within the onResume after super.onResume was executed.

`@Override
    public void onResume() {
        super.onResume();
        getPlaneDiscoveryController().hide();
        getPlaneDiscoveryController().setInstructionView(null);
    }`

Then it worked for me
