### ISSUE TITLE
Cannot import model with opacity map

### ISSUE THREAD

**Issue by Consti10** [google-ar/sceneform-android-sdk#696]
Hello,

When importing models with an opacity map (opacity maps are irreplacable for plants or feathers ) the Sceneform importer throws the known `Validating Materials: Validating material: Jsonnet Error: [1]: RUNTIME ERROR: duplicate field name: "BaseColor"` error.

Here is the model we have issues with:
**1 without opacity ma**p and only 1 material -> works
**2 with opacity map** and only 1 material -> described error when importing

[example.zip](https://github.com/google-ar/sceneform-android-sdk/files/3186749/example.zip)

**Comment by Consti10** [comment]
After making me more familiar with this topic I found a solution.
(requires multiple steps,though)
Images of incorrect and correct rendering:
![Transparent_funktioniert_nicht](https://user-images.githubusercontent.com/16462285/58160411-b40d3a00-7c7e-11e9-92b6-2bbe06f17ee4.PNG)
![transparent_funktioniert_einigermaßen](https://user-images.githubusercontent.com/16462285/58160416-b7a0c100-7c7e-11e9-9fad-78b28daf3322.PNG)


**_1)_** To work around the 'Sceneform importer issue' we tried 2 approaches:
_a)_ Removing the Opacity map texture from the asset before importing, then copy-paste it into .fbm folder. Later add it via **injections** as described under **Replacing or adding textures** here:
https://developers.google.com/ar/develop/java/sceneform/sfa
_b)_ Including alpha channel in the baseColorMap texture ( e.g no opacity map )

**_2)_** Rendering the model with transparency enabled:
While using method a) we were able to get the information into the asset, I was not able to render a transparent object using the opacity map. However, using method b) was succesfull after modifying the .sfm file ( replace source: with 'my_materials/my_fbx_material.sfm' and creating a modifed copy of fbx_material.sfm ).
Here are the modifications:
a) add `blending: "transparent",` 
b) uncomment its already existing definitions
Example (starting at line 137 in the default shader)
`{
        name: "opacity",
        description: "Conditionally enabled transparency",
        options: [
          {
            default: null,
            valid_if: propUseOpacityMap != 1.0,
            //blending: "opaque",
            fragment: ""
          }, {
            default: null,
            valid_if: propUseOpacityMap == 1.0,
            //blending: "transparent",
            fragment: ""
          }
        ]
      }
    ],
    requires: [
      "position",
    ],
    shadingModel: "lit",
    blending: "transparent",`

**Comment by Consti10** [comment]
However, fixing the `Validating Materials: Validating material: Jsonnet Error: [1]: RUNTIME ERROR: duplicate field name: "BaseColor"` issue with the importer directly would make the process of importing .fbx files with multiple materials / multiple textures much easier.

**Comment by Consti10** [comment]
Update:
When rendering an asset that has alpha values of either 'visible' or 'invisible' the correct value for blending is masked. e.g.
blending: "masked",
Else the material is not fully transparent with an alpha value of 0.

**Comment by ManjuAR** [comment]
Hi Im trying to apply the gradient png texture to the plain I was getting the plain reflections as you shown in the above and I have used the blending: "masked", it was working fine without reflections but gradient is not working 
gradient PNG
https://drive.google.com/file/d/17lMgriDnR-x634RVK6gaR4veQqvK5ooC/view?usp=sharing
Texture mapping Sceneform
https://drive.google.com/file/d/1x1tIPzqcF5y9aOiOXCJ6uIzGxafH86P9/view?usp=sharing
blending: "masked",
https://drive.google.com/file/d/1IZGfeHv5NUqJ9h8zYNvSFrKQjfnZn8r2/view?usp=sharing

after blending: "masked", its displaying like this can you please help me to solve this please 

thank you

**Comment by ManjuAR** [comment]
Hi Im trying to apply the gradient png texture to the plain I was getting the plain reflections as you shown in the above and I have used the blending: "masked", it was working fine without reflections but gradient is not working
gradient PNG
https://drive.google.com/file/d/17lMgriDnR-x634RVK6gaR4veQqvK5ooC/view?usp=sharing
Texture mapping Sceneform
![Text](https://user-images.githubusercontent.com/60890049/74213684-5c0cdc80-4cc0-11ea-983d-d9346c33706f.JPG)
blending: "masked",
![Text2](https://user-images.githubusercontent.com/60890049/74213701-721a9d00-4cc0-11ea-91fb-612ed1def416.JPG)
after blending: "masked", its displaying like this can you please help me to solve this please

thank you
