### ISSUE TITLE
Sceneform Environment Map (Reflection Map)

### ISSUE THREAD

**Issue by chiaolinghong3d** [google-ar/sceneform-android-sdk#73]
Hi,

I've been trying to figure out how sceneform/android studio reference the reflection/environment map. On my super shiny 3D models I can see a sandy land with sky image, but couldn't find that image referenced in any of the example codes. Wonder if there's a way to change/customize the environment map for reflections or not. Thanks!

**Comment by tpsiaki** [comment]
@chiaolinghong3d - There is a bug in our 1.0 Android Studio plugin release where the lighting applied in the Android Studio viewer is not the same as in the Android runtime.

The result is that the reflections you see are a different map than will be used in the runtime, and the objects will appear shinier than they will in the runtime.  It sounds like this is what you're seeing.  We have a fix internally which will be available in an upcoming release to make the lighting match the runtime.

Unfortunately, we don't yet support customizing the environment map for reflections.

**Comment by tpsiaki** [comment]
The Android Studio plugin lighting environment now matches the runtime environment in the latest version (1.4.0).

**Comment by ryan-hodgman** [comment]
> Unfortunately, we don't yet support customizing the environment map for reflections.

Can we add this as a feature request?

I'm currently working with a highly metallic material in which I can see the default environment map, which appears to be someone's room? This obviously breaks realism pretty dramatically, so I'm looking for a way to customize the map.

If this isn't currently supported by the Sceneform APIs, can you suggest a workaround? Do I need to include it in a material imported from a modelling tool somehow?


Visual from Filament that depicts the desired customization. 

![filament_reflections](https://user-images.githubusercontent.com/26558824/48462263-9b354f00-e82b-11e8-97e2-6168626db2e0.png)
([Source](https://github.com/google/filament))
