### ISSUE TITLE
Runtime error after update to 1.10.0

### ISSUE THREAD

**Issue by Consti10** [google-ar/sceneform-android-sdk#747]
After updating to Sceneform 1.10.0 from 1.09.0 (and also updating the Sceneform importer) I get the following runtime error resulting in a crash when loading models:

`Panic
    in filament::Material *filament::Material::Builder::build(filament::Engine &):86
    reason: Material version mismatch. Expected 3 but received 2.
2019-06-26 18:03:11.584 18404-18404/com.lrz.mosaik E/Filament: --------- beginning of crash
2019-06-26 18:03:11.585 18404-18404/com.lrz.mosaik A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 18404 (com.lrz.mosaik), pid 18404 (com.lrz.mosaik)`

Downgrading back to 1.09.0 works.

**Comment by Jei** [comment]
I'm having the same issue. I've also tried to import my model again after the update.

**Comment by nasko700** [comment]
Did you update the version in gradle project file to classpath 'com.google.ar.sceneform:plugin:1.10.0' ?

**Comment by Consti10** [comment]
No,I did not. 
Can't test it right now, but sounds like a solution.
Note that the sceneform plugin is in your top level gradle file, like this:
`classpath 'com.android.tools.build:gradle:3.4.1'
classpath 'com.google.ar.sceneform:plugin:1.9.0'
`

**Comment by Jei** [comment]
@nasko700 that solved it for me, thanks.

**Comment by kenyee** [comment]
FYI, this can also happen if you only checked in the .SFB/.SFA file into your project.  These files are *not* backwards compatible w/ later versions of Filament/Sceneform.  Always set up the importer plugin instead...I have to fix the project I'm on to use the importer :-)

**Comment by Consti10** [comment]
@nasko700 
Solved it for me,too.
Note that updating the importer via the 'update available' prompt from android studio did not update the version in my gradle file.

**Comment by tonilsz** [comment]
I allways get this error when I update scenefrom, you only have to delete your sfb files and rebuild.

Please close that threat
