### ISSUE TITLE
How to place an Ray at center of screen and move it with respect to camera movement and Tilt Angle?

### ISSUE THREAD

**Issue by bravewilliam** [google-ar/sceneform-android-sdk#749]
Below is the code which I have tried.
 private val TAG = MainActivity::class.java!!.simpleName

    private val MIN_OPENGL_VERSION = 3.0

    private var fragment: ArFragment? = null

    var isTracking = false

    var cylinderRenderable: ModelRenderable? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        initRender()
        fragment = supportFragmentManager.findFragmentById(R.id.ux_fragment) as ArFragment?

        fragment!!.arSceneView.scene.addOnUpdateListener { frameTime ->
            fragment!!.onUpdate(frameTime)
            val frame = fragment!!.arSceneView.arFrame ?: return@addOnUpdateListener

            if (frame!!.camera.trackingState != TrackingState.TRACKING) {
                return@addOnUpdateListener
            }
            onUpdate()
        }

    }
    

    private fun initRender() {
        makeCylinder()
    }

    var anchorNode : AnchorNode? = null
    var node : TransformableNode? = null

    private fun onUpdate() {
        if(cylinderRenderable == null){
            return
        }
        val frame = fragment!!.arSceneView.arFrame
        val updateTracking = updateTracking()
        val isAttachCamera = false
        if(updateTracking || !isAttachCamera){
            if(isTracking){
                removePointer()
                val cameraPos = fragment!!.arSceneView.scene.camera.worldPosition
                val cameraForward = fragment!!.arSceneView.scene.camera.forward
                val position = Vector3.add(cameraPos, cameraForward.scaled(1.0f))

                val centerRay = getCenterRay()
                val pos = Vector3.add(centerRay.origin, centerRay.direction)
                // Create an ARCore Anchor at the position.
                val pose = Pose.makeTranslation(pos.x, pos.y, pos.z)
                val anchor = fragment!!.arSceneView.session!!.createAnchor(pose)

                anchorNode = AnchorNode(anchor)
                anchorNode!!.setParent(fragment!!.arSceneView.scene)

                val transformationSystem = fragment!!.transformationSystem
                node = TransformableNode(transformationSystem)
                node?.let {
                    it.renderable = cylinderRenderable
                    it.setParent(anchorNode)
                    it.select()
                }
            }else{
                removePointer()
            }
        }

    }

    private fun makeCylinder() {
        MaterialFactory.makeOpaqueWithColor(this@MainActivity, com.google.ar.sceneform.rendering.Color(Color.GREEN))
            .thenAccept { material ->
                cylinderRenderable = ShapeFactory.makeCylinder(0.01f, 1.0f, Vector3(0.0f, 0.15f, 0.0f), material)
                cylinderRenderable?.setRenderPriority(Renderable.RENDER_PRIORITY_LAST)
                cylinderRenderable?.setShadowCaster(false)
            }
            .exceptionally {
                Log.d(TAG,"make cylinder error")
                null
            }
    }

    private fun updateTracking(): Boolean {
        val frame = fragment!!.arSceneView.arFrame
        val wasTracking = isTracking
        isTracking = frame != null && frame!!.camera.trackingState == TrackingState.TRACKING
        return isTracking != wasTracking
    }

    private fun removePointer() {
        anchorNode?.let { anchor ->
            anchor.parent?.removeChild(anchor)
            node?.let { it ->
                anchor.removeChild(it)
                node = null
            }
            anchorNode = null
        }
    }

    private fun getCenterRay(): Ray {
        val vw = findViewById<View>(android.R.id.content)
        return fragment!!.arSceneView.scene.camera.screenPointToRay(vw.width/2.toFloat(),vw.height/2.toFloat())
    }
It is all right the the begining.But when I move the phone,the ray doesn't place the right place.
It is suppose to place at center of screen,by show like the picture below.It seems like the length of cylinder is too long.Anyone can help?Thanks in advance.
![Screenshot_20190628-100220_SceneForm](https://user-images.githubusercontent.com/38775225/60313095-5f9d5e80-9990-11e9-95e7-502f07bda2c3.jpg)

**Comment by bravewilliam** [comment]
I had make a stupid mistake.

**Comment by chnouman** [comment]
@bravewilliam can you share.
