### ISSUE TITLE
rotating a node 

### ISSUE THREAD

**Issue by ishaang10** [google-ar/sceneform-android-sdk#762]
how can i constantly keep rotating a node using a click of a button??
example i have a fan . now i need to rotate it when button is pressed. how can i ?

**Comment by tonilsz** [comment]
You can follow this tutorial, on it you will found a rotable node: 
https://proandroiddev.com/building-arcore-apps-using-sceneform-part-4-9bb8374eaab4

You only have to edit the update and add an active boolean to rotate or not.

**Comment by aurangzaibumer777** [comment]
if your using a custom node class (that must be extending to Node)

override this method and paste this code

override fun onUpdate(p0: FrameTime?) {
        super.onUpdate(p0)
        worldRotation = Quaternion.axisAngle(Vector3.up(), ++rotationY)
    }

**Comment by ishaang10** [comment]
@aurangzaibumer777 thanks for your response. can you tell me how can i create a custom node class and use it. coz i am a ittle new to this and also the class which i am doing all the stuff is already extending appcompatactivity.

**Comment by aurangzaibumer777** [comment]
send me your snippet on
umer.aurangzaib92@gmail.com

**Comment by ishaang10** [comment]
wait. ive made the custom class and used it. now just tell me how and where to use the worldrotation and rotationy variables

**Comment by ishaang10** [comment]
how can i use those variables?

**Comment by aurangzaibumer777** [comment]
i sent you the snippet above, override the mentioned method and it will rotate your object per frame

**Comment by ishaang10** [comment]
how to declare the worldrotation and rotationy variables? where and with what initial values?

**Comment by ishaang10** [comment]
@aurangzaibumer777 thanks a lot sir....thumbs up to you .i figured this out . thanks
