### ISSUE TITLE
Custom plane 

### ISSUE THREAD

**Issue by ishaang10** [google-ar/sceneform-android-sdk#776]
Can we create a custom horizontal plane at certain height??? if yes then how.? if not then i request the team to make this a feature request.

**Comment by tonilsz** [comment]
Yes it is, I have told you how but I will go more deeper .

You make a flat cube like this:
val modelRenderable = ShapeFactory.makeCube(
            Vector3(1f, .0001f, 1f),
            Vector3.zero(), material
        )

Then you asign that model to your node (child of anchorNode):
this.renderable = modelRenderable

and finally, set your desired height to the plane:
this.localPosition.y = value 

I put all this code in the init of my objectNode who extends (BaseTransformableNode)

hope that will help you

**Comment by ishaang10** [comment]
yeaqh thanks ive solved it..
