### ISSUE TITLE
DeadlineExceededException in acquireCameraImage()

### ISSUE THREAD

**Issue by michael6666666** [google-ar/sceneform-android-sdk#805]
I used the following code in the AugmentedFace example to access the CPU image. It worked fine before Aug 1st but started to throw "DeadlineExceededException" 2 seconds after running the app. 

Did I change something wired or was there an update from ArCore? What is the appropriate way to call acquireCameraImage() in Sceneform? Thanks!

```
Frame frame = arFragment.getArSceneView().getArFrame();
if (frame == null) {
      return "Frame is null";
}

synchronized (frameImageInUseLock) {
      try (Image image = frame.acquireCameraImage()) {
        if (image.getFormat() != ImageFormat.YUV_420_888) {
          throw new IllegalArgumentException(
              "Expected image in YUV_420_888 format, got format " + image.getFormat());
        }
        //do something with image...
      } catch (NotYetAvailableException e) {
        Log.e(TAG, "NotYetAvailableException", e);
      } catch (DeadlineExceededException e){
        Log.e(TAG, "DeadlineExceededException", e);
      } catch (Exception e) {
        Log.e(TAG, "Image copy exception", e);
      }
    }
```

**Comment by michael6666666** [comment]
For those faces the same issue, it may be wise to access the camera image via GPU texture instead.

**Comment by Tushar-kant-Deo** [comment]
hello michael, I am new in ARCore. Will you please provide some reference for accessing camera image, as I am facing the same issue. I am not aware of GPU textures. Thanks in advance.

**Comment by michael6666666** [comment]
Hi, maybe you could get some useful information from the [computervision_java](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/computervision_java) example in the arcore-android-sdk repository. I've copied a few files from that project to retrieve the GPU image.
