### ISSUE TITLE
Dynamic texture creation

### ISSUE THREAD

**Issue by evodabas** [google-ar/sceneform-android-sdk#81]
Is there any way to populate a Texture object from data generated at runtime rather than just a file or resource (analogous to using RenderableDefinition.Builder to create a Renderable object from raw vertex/index values)?

Going even further, is there any plan to allow for plugins that can interact with SceneForm objects at the OpenGL/Vulkan level?

Thanks,
Evan

**Comment by malik-at-work** [comment]
We have not created API for this yet.  I'll add it as a feature request.

**Comment by dsternfeld7** [comment]
It is now possible to create dynamic textures as of Sceneform 1.4.

`CompletableFuture<Texture> bitmapTextureFuture = Texture.builder().setSource(bitmap).build();`

Please feel welcome to create a separate issue for the feature request of being able to use openGL directly with Sceneform. However, we don't have plans to add that  feature at this time.
