### ISSUE TITLE
Error updating Sceneform Tools 1.11.0 

### ISSUE THREAD

**Issue by larissayasin** [google-ar/sceneform-android-sdk#812]
When I updated the plugin Google Sceneform Tools (Beta) to v.1.11.0, I started to get this error message:

> Plugin 'google-sceneform-tools' failed to initialize and will be disabled.  Please restart Android Studio.
> 
> java.lang.UnsatisfiedLinkError: /tmp/sceneform-loader-jni2523188150614532625/libloader-jni.so: /tmp/sceneform-loader-jni2523188150614532625/libloader-jni.so: undefined symbol: _ZN8filament6Engine7destroyEPKNS_12VertexBufferE
>     at java.lang.ClassLoader$NativeLibrary.load(Native Method)
>     at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
>     at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
>     at java.lang.Runtime.loadLibrary0(Runtime.java:870)
>     at java.lang.System.loadLibrary(System.java:1122)
>     at com.google.ar.sceneform.plugin.viewer.SceneformSFBProvider.startEngine(SceneformSFBProvider.java:129)
>     at com.google.ar.sceneform.plugin.viewer.SceneformSFBProvider.initComponent(SceneformSFBProvider.java:37)
>     at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:486)
>     at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:104)
>     at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:447)
>     at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
>     at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
>     at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
>     at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
>     at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
>     at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:471)
>     at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
>     at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:405)
>     at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:391)
>     at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:217)
>     at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:77)
>     at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
>     at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
>     at java.awt.EventQueue.access$500(EventQueue.java:98)
>     at java.awt.EventQueue$3.run(EventQueue.java:715)
>     at java.awt.EventQueue$3.run(EventQueue.java:709)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
>     at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
>     at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
>     at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
>     at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
>     at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
>     at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

The 1.10.0 version was working fine, now the plugin doesn't work anymore. 

OS is Ubuntu 18.04.3 LTS
Android Studio is 3.4.2

**Comment by ankitdgolatkar** [comment]
I have the same issue. 
I also tried Android studio 3.4.1

The only solution I found was to use the Sceneform plugin version 1.7.0 from https://github.com/google-ar/sceneform-android-sdk/releases. This works with studio version 3.4.2
But it gives me some API warnings

> WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
> It will be removed at the end of 2019.
> For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
> To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
> Affected Modules: app

Also, it does not generate the sfb file.

**Comment by YinXiuYu** [comment]
I have the same issue too。

**Comment by tpsiaki** [comment]
Thanks for the report.  We are working on a fix for the Sceneform plugin.

**Comment by Dosssik** [comment]
I've got the same problem, Android Studio 3.4.2 plugin v1.11.0.

But, as a temporary workaround it's possible to use scenefrom assert converter by command line - it generates .sfb and works fine in application, but, sure, no any preview in studio
Link to converter - https://github.com/gdamoreira/google-ar-asset-converter
Hope it'll help someone

**Comment by tpsiaki** [comment]
We just released v1.11.1 which has the fix for this issue which occurred on Linux and Windows machines.

**Comment by kobe-anacoimbra** [comment]
I still have this problem in MAC OS.

**Comment by ankitdgolatkar** [comment]
I updated my android studio version to 3.5 and the sceneform to v1.11 (latest version) but then the program crashes with a javaLang error

**Comment by vortice3D** [comment]
Hi there:

Android Studio 3.5 + Sceneform plugin v1.11.1 combo seems not to work properly, as it's not able to generate SFA nor SFB files from a FBX file.

Coming back to a fresh Android Studio 3.4 at the moment.
