### ISSUE TITLE
Saturated Camera output in Sceneform

### ISSUE THREAD

**Issue by khonakr** [google-ar/sceneform-android-sdk#82]
Hello,

I realized that the Sceneform Camera output is more saturated / brighter than the ARCore Unity counterpart.
The Unity camera looks more realistic like normal camera whereas the Sceneform one looks like one with a filter and lesser details.

Is there some way to avoid the saturated camera output? 

(Not a very good sample image, sorry about that)
Sceneform:
![screenshot_20180606-170326](https://user-images.githubusercontent.com/3877104/41065325-5451a334-69ac-11e8-8caf-8b481c6c5db7.png)

Unity:
![screenshot_20180606-170335](https://user-images.githubusercontent.com/3877104/41065335-58dada24-69ac-11e8-95d4-60e585c8fb39.png)

**Comment by malik-at-work** [comment]
We can confirm this difference.  We will update with a workaround or update.

**Comment by romainguy** [comment]
This issue has been fixed internally.

**Comment by dsternfeld7** [comment]
This is now fixed in Sceneform 1.4.
