### ISSUE TITLE
File was loaded with the wrong encoding:UTF-8

### ISSUE THREAD

**Issue by newmluser** [google-ar/sceneform-android-sdk#835]
I created a basic project and am trying to create SFA and SFB.

Added with a standard 3D obj and tried to create SFA and SFB.
Getting this Error. how can I fix this Error.
After this Error even the SFB is created in the assets folder I cannot open it

**Comment by bobekos** [comment]
Duplicate of #815

**Comment by nasko700** [comment]
I downgraded the plugin, but in AS 3.5 but I still have this problem.
Here are the versions of the plugin: https://plugins.jetbrains.com/plugin/10698-google-sceneform-tools-beta-/versions

**Comment by bobekos** [comment]
@newmluser 
Ah ok. With AS 3.4 and Plugin 1.11 everything works correctly on my mac. The last version which i have tested on windows was 3.4 and 1.10.

**Comment by tpsiaki** [comment]
Thank you - I believe this is a dupe of #815 - we have a fix internally which will be available in our next release.
