### ISSUE TITLE
Converting x,y coordinates from MotionEvent into world coordiantes

### ISSUE THREAD

**Issue by phoenixxt** [google-ar/sceneform-android-sdk#84]
Hello! How to properly convert between x,y coordinates that you get from a MotionEvent into world coordinates if I don't really care about a y-world coordinate? What I'm trying to achieve is recreate something like https://github.com/googlecreativelab/ar-drawing-java using sceneform.

**Comment by dsternfeld7** [comment]
I think this is what you're looking to do:

```
// Get a position 0.25 meters forward into the camera from the position of the motion event.
int index = motionEvent.getActionIndex();
Ray ray =
    arSceneView
        .getScene()
        .getCamera()
        .screenPointToRay(motionEvent.getX(index), motionEvent.getY(index));
Vector3 position = ray.getPoint(0.25f);
```

**Comment by phoenixxt** [comment]
Thanks, works like a charm! :) Also, one small question, right now I use small spheres created by Material and Shape factories for drawing and it works okay, but after creating a hundred different lines and that means thousands of spheres the app starts to lag a little (samsung s8 plus). Is there maybe a better way that sceneform provides to enable drawing in space?

**Comment by dsternfeld7** [comment]
Glad it worked!

Rendering thousands of nodes will definitely cause slowdown. It would be better to have a Renderable per stroke created by the user instead. I would recommend creating the geometry for the drawing procedurally using the [RenderableDefinition](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/rendering/RenderableDefinition) API. If you represent each stroke as a sequence of points, you can then generate the vertices and triangles for the stroke yourself. This also gives you the ability to effectively control the properties of the stroke, for instance it's shape and size.

I'm also curious, how many ARCore anchors are you creating for the drawing?

**Comment by phoenixxt** [comment]
Thanks for the advice! Do you, by any chance, know any article, documentation or maybe an example with that api used, so it could help me get a feel of how things work there better?

**Comment by dsternfeld7** [comment]
Closing because the followup question is being discussed in issue [https://github.com/google-ar/sceneform-android-sdk/issues/100](https://github.com/google-ar/sceneform-android-sdk/issues/100)
