### ISSUE TITLE
FBX's object's local space pivots problem

### ISSUE THREAD

**Issue by vortice3D** [google-ar/sceneform-android-sdk#842]
Hi there:

We are experiencing issues with animated objects exported to FBX format (offering prayers in order to have GLTF/GLTF animations implemented in ARCore ASAP).

If the object's local space pivots (rotate and scale pivots) are non zero, then the object moves away **### when activating its animation inside a Sceneform** (if you don't activate the animation, the object is shown in its right place).

In order to avoid this issue, we had to completely flatten all the hierarchies AND zeroed out the local space pivots (and inversely correct their animation curves because zero those pivots modifies the curves).

Thanks for your time.

**Comment by tonilsz** [comment]
Hi there:

I'm experimenting the same issues with animations I have and fbx composed by 3 objects 2 of them animated if I play the clip I only can see one of the animated object the other ones disappear. I have spitted them into different fbx, but the position is not the same. 

I have another model that have too much objects animated in the same fbx and I can't apply the same tecnique and correct all positions manuality.

My models are displayed well in Unity3d.

Thanks in advance

**Comment by vortice3D** [comment]
Hi **Tolnilsz**:

From my own experience, the Sceneform FBX importer (Android Studio Sceneform plugin) is really tricky (think about it as a pre-beta sotware).

By example, you can´t trust on it when generating SFA/SFB compiled files, and is needed to review line by line that all materials are well linked, and so on.

Said this, in your case I think the problem lies in the FBX itself. Being sure all the (keyframe) animations are **baked in world-coordinates** usually will work.

Best regards.
