### ISSUE TITLE
can't sync sceneform 1.11.1

### ISSUE THREAD

**Issue by tommigun97** [google-ar/sceneform-android-sdk#858]
Hi, when i try to sync:
ERROR: Failed to resolve: com.google.ar.sceneform.ux:sceneform-ux:1.11.1
I can't use this version of sceneform.

**Comment by tpsiaki** [comment]
There is not a 1.11.1 version of the sceneform ux package.  If you are looking for 1.11 the correct version is 1.11.0, and the most recent shipped sceneform ux package (as of yesterday) is 1.12.0
