### ISSUE TITLE
Which format is best for models with textures?

### ISSUE THREAD

**Issue by chnouman** [google-ar/sceneform-android-sdk#864]
I'm curious about the selection of format for my models. I have searched in documentation and on other places but haven't found any comparison and advantages of one on another. Can any body refer me any blog post or any comparision table for these supported formats i.e fbx, gltf and obj.

**Comment by vortice3D** [comment]
Hi **chnouman**:

The only way to go in 2019 is **GTLF/GLB**. Of course always with **PBR** materials.

Anyway, please note that in the case you are needing animated models, (very) sadly the current **Scenefom** implementation only observes**FBX** (and believe be, is a mess to work with that old format)

In the other way, if you want to use **ARCore** on the Web, by means of the model-viewer web component (**Scene Viewer**) you won´t have any problem with animated GLTF/GLB, and indeed they are the only allowed formats.

Best regards.

**Comment by chnouman** [comment]
@vortice3D thank you for your response. I'll go with GLTF models format because currently, I don't have animations. thanks.
