### ISSUE TITLE
In solarsystem sample the planets don't rotate

### ISSUE THREAD

**Issue by ToniCors** [google-ar/sceneform-android-sdk#914]
In solarsystem sample the planets are completely still

**Comment by artemisia** [comment]
add more details? such as what's your device, android studio version, arcore version, etc

**Comment by ToniCors** [comment]
i am using HUAWEI p30 pro (EMUI 9.1.0). I downloaded this sample:  [ https://github.com/google-ar/sceneform-android-sdk/tree/master/samples/solarsystem](url), that use 'com.google.ar.sceneform:plugin:1.13.0' . My android studio versione is 3.5. 
please, can you try to istall the same app, and tell me if you have the same problem?

**Comment by ToniCors** [comment]
i revolve my issue. In develiper options, all animatione settings were off.
