### ISSUE TITLE
How to Add some animation or effect when dropping or placing model?

### ISSUE THREAD

**Issue by chnouman** [google-ar/sceneform-android-sdk#937]
I recently saw an Ikea app it is build in Unity and have very nice gravity effect which means when you drag the item and place it it shows some gravity effect. How can I achieve something similar to it?

**Comment by Farah7402** [comment]
Do you know in image detection android app when we place model on image after image detected how can we rotate and zoom that model using gestures in SceneView?This functionality is easily implemented when I had created surface detection android app using ArFragments but using SceneView or ArSceneView I do not find any solution

**Comment by hardik-intellify** [comment]
You can use `ObjectAnimator` in order to achieve that functionality.

**Comment by chnouman** [comment]
@hardik-intellify thank you for your suggestion. I already have followed this and achieved the required results.
