### ISSUE TITLE
I want the model to be downloaded from the server,

### ISSUE THREAD

**Issue by ToadPrincess** [google-ar/sceneform-android-sdk#94]
The requirement is that the model be downloaded from the server, not preset in APK,
How do we solve this,thank.

**Comment by Toione** [comment]
@ToadPrincess You can create your model using the URI os the model in server.

For example:
`ModelRenderable.builder().setSource(this, Uri.parse("http://www.example.com/model.sfb")).build()`

**Comment by ToadPrincess** [comment]
It turned out that only one SFB file was needed.I saw the address of the model file in the FBX file, so I think I still need the file under sampledata. Thank you
