### ISSUE TITLE
Question: core methods accessibility from scenefrom

### ISSUE THREAD

**Issue by abbana** [google-ar/sceneform-android-sdk#95]
Hi,

we have a core session we want to migrate to ArFragment to be able to use its methods.

It is possible to use the standard core methods from within ArFragment and just add the desired functionalities or we have to re write all the code for ArFragment?

Do we have any example?

Thanks.

**Comment by malik-at-work** [comment]
If I'm reading this correctly, you already have an ArCore Session and you'd like to reuse it in ArFragment.  In v1.0 there is no API to use a Session created elsewhere.  I'll record that as a feature request.

If you want to call you own functions on the Session we have created this is possible.  You need to get the [ArSceneView](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/ArSceneView) via ArFragment.getArSceneView()


Then call ArSceneView.getSession().

**Comment by abbana** [comment]
Hi,

I have my own methods impelemented in a core Session. I am using GLES shaders and a lot of code working without sceneform.

Question is, may use the core functionalities inside sceneform ArFragment ARcore session?

This way with little work I can cut&paste the actual code to the ArFragment and avail of the new features without the need to rewrite it. EG: I can keep my shaders and mix them with the new code which will use sceneform specific content.

**Comment by malik-at-work** [comment]
Can we get more info about exactly what you are doing?  

Unfortunately, you can not add handwritten OpenGL into Sceneform as of V1.0.  Our next release will have more shader functionality so we may be able to achieve a similar effect, but you still will not be able to copy and paste a shader over.

**Comment by abbana** [comment]
Ok,

I ll continue to work with the core functionalities then until will be quick to migrate on this.

Thanks again, you can close the case.
