### ISSUE TITLE
ARCore image detected but not tracking

### ISSUE THREAD

**Issue by jnawaz** [google-ar/sceneform-android-sdk#952]
I have added some of my own example images to the AugmentedImages sample project. 

When trying to scan these using the Samsung Galaxy S7 the image is detected but it won't enter the tracking phase in order to be able to add nodes. 

Is anybody able to provide insight into what would cause the `trackingState` to enter `TRACKING` ?

**Comment by hardik-intellify** [comment]
I'm having the same issue.
Android Studio : 3.5.3
Sceneform: 1.14.0


`augmentedImage.getTrackingState()` always returns `PAUSED`.

**Comment by jnawaz** [comment]
After a lot of investigation with images. 

I can conclude the following information helped. https://developers.google.com/ar/develop/java/augmented-images/#requirements
