### ISSUE TITLE
How can I convert frame to jpg file ?

### ISSUE THREAD

**Issue by claireliu14** [google-ar/sceneform-android-sdk#965]
I can get frame image by calling frame.acquireCameraImage(), and then it returns a YUV_420_888 format image to me, but I cannot find any solutions to get jpg file. Please help!

**Comment by DoctorB** [comment]
`    public static byte[] NV21toJPEG(byte[] nv21, int width, int height) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        YuvImage yuv = new YuvImage(nv21, ImageFormat.NV21, width, height, null);
        yuv.compressToJpeg(new Rect(0, 0, width, height), 100, out);
        return out.toByteArray();
    }

    public static byte[] YUV_420_888toNV21(Image image) {
        byte[] nv21;
        ByteBuffer yBuffer = image.getPlanes()[0].getBuffer();
        ByteBuffer uBuffer = image.getPlanes()[1].getBuffer();
        ByteBuffer vBuffer = image.getPlanes()[2].getBuffer();

        int ySize = yBuffer.remaining();
        int uSize = uBuffer.remaining();
        int vSize = vBuffer.remaining();

        nv21 = new byte[ySize + uSize + vSize];

        //U and V are swapped
        yBuffer.get(nv21, 0, ySize);
        vBuffer.get(nv21, ySize, vSize);
        uBuffer.get(nv21, ySize + vSize, uSize);

        return nv21;
    }`

**Comment by claireliu14** [comment]
@DoctorB Thanks! That is what I'm looking for.

To add that, using code below can rotate the image to right angle.
```java
            // rotate image
            Bitmap bitmap = BitmapFactory.decodeByteArray(data, 0, data.length);
            final int rotate = 90;

            Matrix matrix = new Matrix();
            matrix.postRotate(rotate);

            return Bitmap.createBitmap(bitmap, 0, 0, bitmap.getWidth(),
                    bitmap.getHeight(), matrix, true);
```
