### ISSUE TITLE
Sceneform Gradle Plugin for IntelliJ - SFB Viewer doesn't work in Linux

### ISSUE THREAD

**Issue by Toione** [google-ar/sceneform-android-sdk#97]
Hello you all.

Since I've installed the Gradle plugin in my IntelliJ IDE, the feature for viewer, and just this, doesn't work and, then, I can't see my SFB model.

Can anyone help me?

**Comment by terezo** [comment]
I am having same issue on my Ubuntu 16.04 + AS 3.1.1

**Comment by romainguy** [comment]
Do you get any errors in IntelliJ's logs? Could you also please tell me what GPU and graphics drivers your machine uses? Thanks!

**Comment by Toione** [comment]
Hello guys.

I did made my viewer work fine. I just see the logs and realize that my OpenGL ES is a version is below than 3.1, that's why the viewer doesn't works fine. I changed my GPU card to a new one who have support for OpenGL ES 3.1 or high version.

This issue isn't a bug, it's hardware/software issue.
You need a GPU card who have support for a OpenGl ES 3.1 or high version.

Thanks for your attention.
Regards.

**Comment by romainguy** [comment]
OpenGL ES 3.1 is what is required on Android, but on Linux we require OpenGL (not ES) 4.1.

**Comment by Toione** [comment]
But the IntelliJ logs told me I should have version 3.1 of OpenGL ES.
Only when I got the version of OpenGL ES 3.1 did the viewer work.
