### ISSUE TITLE
How to disable the rotation (twist) of ar object 

### ISSUE THREAD

**Issue by suraj-0387** [google-ar/sceneform-android-sdk#983]
I am working on ar application and I have to place a painting on the wall.I can place the painting but do not want the painting to be rotated .So how can I restrict the rotation (twisting) of ar object

**Comment by hardik-intellify** [comment]
I assume that you are using `TransformableNode`,
so you can do like,
`transformableNode.rotationController.isEnabled = false`

**Comment by suraj-0387** [comment]
@hardik-intellify Thanks for the answer
