### ISSUE TITLE
Sceneform plugin v1.15.0 not working w/Android Studio 3.6 stable (or Android Studio 4 Canary 9)

### ISSUE THREAD

**Issue by tellypresence** [google-ar/sceneform-android-sdk#989]
SceneForm 1.15.0 plugin installed for three versions of Android Studio.  Asset imports perfectly in legacy stable Android Studio (3.5.3) but not in 
* latest stable (3.6)
* latest preview (4 canary 9)

Android Studio 3.5.3
![import_sceneform_asset_android_studio_3 5 3](https://user-images.githubusercontent.com/26958898/74486419-42f26e80-4f00-11ea-84b0-39d3ddb5780c.png)

Android Studio 4 Canary 9
![import_sceneform_asset_android_studio_4_canary_9](https://user-images.githubusercontent.com/26958898/74486257-ea22d600-4eff-11ea-8046-d572fa80d55e.png)

**Comment by AndreaGrizzi** [comment]
issue found on Android Studio 3.6 on stabile channel.
import .obj file result in Error: java.lang.RuntimeException: java.lang.NoSuchMethodError: com.android.tools.idea.templates.recipe.RecipeExecutor.append(Ljava/io/File;Ljava/io/File;)

**Comment by dawcules** [comment]
Updated to Androis Studio 3.6 and Sceneform 1.15.0. Every .obj and .fbx import results to: Error: java.lang.RuntimeException: java.lang.NoSuchMethodError: com.android.tools.idea.templates.recipe.RecipeExecutor.append(Ljava/io/File;Ljava/io/File;)

- Tried to re-install sceneform -> no effect

**Comment by tellypresence** [comment]
Confirm broken w/3.6 stable as well, changing title

**Comment by VCDo** [comment]
After Android Studio update from stable 3.5.x to 3.6 the Sceneform Import stopped working! Updating tools and gradle versions did not fix this problem...

**Comment by VCDo** [comment]
Since the plugin is not working anymore, is it possible to import a sceneform asset without android studio?

**Comment by tellypresence** [comment]
@VCDo for now suggest having Android Studio 3.5.3 co-installed and doing all sceneform importing there; copy all the generated assets (build.gradle block, .sfa/.sfb etc) to your actual working project (using Android Studio 3.6.X or 4.X) and it should work fine -- IIRC using the .sfb isn't the problem, it's just the import process itself that's broken

**Comment by BhaktijPatil** [comment]
Do we have any official confirmation from the Sceneform team as to when this issue will be addressed?

**Comment by YinXiuYu** [comment]
I have the same issue.

**Comment by FabianSchmiedlechner** [comment]
+1

**Comment by sameerjj** [comment]
+1

**Comment by A-khames** [comment]
I have the same issue

**Comment by tellypresence** [comment]
IIUC Sceneform v1.16.0 deprecates the entire SceneForm plugin and .sfa/.sfb workflow instead migrating to direct support for .gltf/.glb format assets

**Comment by saechimdaeki** [comment]
same issue in 3.6.3
