### ISSUE TITLE
how to change original floor tiles ?

### ISSUE THREAD

**Issue by ashokkumarfun** [google-ar/sceneform-android-sdk#99]
Change original floor tile with virtual tile and want to replace the only real floor with AR plan and all real objects are still visible not hide by the virtual plan.

**Comment by malik-at-work** [comment]
Are you asking to create AR objects which would cover the floor, but you want objects in Camera on the floor to still be visible?

This kind of occlusion, mixing virtual and real objects is not supported as of V1.0

**Comment by ashokkumarfun** [comment]
Thank you so much, sir.
yes, you are right. can we achieve this goal using ARCore, computer vision, OpenGL or any other way to get this without Sceneform SDK?

**Comment by malik-at-work** [comment]
It's possible, but this isn't part of our API as of v1.0..  If you look online you can see many videos of AR occlusion.  


In the meantime I'll add this as a feature request and we will consider it for future releases of Sceneform.

**Comment by malik-at-work** [comment]
See also https://github.com/google-ar/arcore-unity-sdk/issues/184
